// Command runtimegen turns the OpenAPI document into the browser's runtime
// validation table. Type generation alone cannot protect an API boundary:
// JSON.parse still returns untrusted values at runtime.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type document struct {
	Paths      map[string]pathItem `yaml:"paths"`
	Components struct {
		Schemas map[string]any `yaml:"schemas"`
	} `yaml:"components"`
}

type pathItem struct {
	Get    *operation `yaml:"get"`
	Post   *operation `yaml:"post"`
	Put    *operation `yaml:"put"`
	Patch  *operation `yaml:"patch"`
	Delete *operation `yaml:"delete"`
}

type operation struct {
	RequestBody *body               `yaml:"requestBody"`
	Responses   map[string]response `yaml:"responses"`
}

type body struct {
	Required bool                   `yaml:"required"`
	Content  map[string]mediaSchema `yaml:"content"`
}

type response struct {
	Reference string                 `yaml:"$ref"`
	Content   map[string]mediaSchema `yaml:"content"`
}

type mediaSchema struct {
	Schema any `yaml:"schema"`
}

type endpoint struct {
	Method          string         `json:"method"`
	Path            string         `json:"path"`
	RequestRequired bool           `json:"requestRequired,omitempty"`
	Request         any            `json:"request,omitempty"`
	Responses       map[string]any `json:"responses"`
}

func main() {
	spec := flag.String("spec", "", "OpenAPI input")
	output := flag.String("output", "", "TypeScript output")
	flag.Parse()
	if *spec == "" || *output == "" || flag.NArg() != 0 {
		fatal("usage: runtimegen -spec <openapi.yaml> -output <validators.generated.ts>")
	}
	contents, err := os.ReadFile(*spec)
	if err != nil {
		fatal("read OpenAPI: %v", err)
	}
	var parsed document
	if err := yaml.Unmarshal(contents, &parsed); err != nil {
		fatal("parse OpenAPI: %v", err)
	}
	if len(parsed.Components.Schemas) == 0 || len(parsed.Paths) == 0 {
		fatal("OpenAPI has no paths or component schemas")
	}

	endpoints := collectEndpoints(parsed)
	schemasJSON, err := marshalStable(parsed.Components.Schemas)
	if err != nil {
		fatal("encode schemas: %v", err)
	}
	endpointsJSON, err := marshalStable(endpoints)
	if err != nil {
		fatal("encode endpoints: %v", err)
	}

	generated := strings.ReplaceAll(runtimeTemplate, "__SCHEMAS__", string(schemasJSON))
	generated = strings.ReplaceAll(generated, "__ENDPOINTS__", string(endpointsJSON))
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fatal("create output directory: %v", err)
	}
	if err := os.WriteFile(*output, []byte(generated), 0o644); err != nil {
		fatal("write output: %v", err)
	}
}

func collectEndpoints(parsed document) []endpoint {
	paths := make([]string, 0, len(parsed.Paths))
	for path := range parsed.Paths {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var endpoints []endpoint
	for _, path := range paths {
		item := parsed.Paths[path]
		operations := map[string]*operation{
			"delete": item.Delete,
			"get":    item.Get,
			"patch":  item.Patch,
			"post":   item.Post,
			"put":    item.Put,
		}
		methods := make([]string, 0, len(operations))
		for method, operation := range operations {
			if operation != nil {
				methods = append(methods, method)
			}
		}
		sort.Strings(methods)
		for _, method := range methods {
			operation := *operations[method]
			item := endpoint{Method: strings.ToUpper(method), Path: path, Responses: map[string]any{}}
			if operation.RequestBody != nil {
				item.RequestRequired = operation.RequestBody.Required
				item.Request = jsonSchema(operation.RequestBody.Content)
			}
			statuses := make([]string, 0, len(operation.Responses))
			for status := range operation.Responses {
				statuses = append(statuses, status)
			}
			sort.Strings(statuses)
			for _, status := range statuses {
				response := operation.Responses[status]
				if response.Reference != "" {
					continue
				}
				if schema := jsonSchema(response.Content); schema != nil {
					item.Responses[status] = schema
				}
			}
			endpoints = append(endpoints, item)
		}
	}
	return endpoints
}

func jsonSchema(content map[string]mediaSchema) any {
	for _, contentType := range []string{"application/json", "application/problem+json"} {
		if media, ok := content[contentType]; ok {
			return media.Schema
		}
	}
	return nil
}

func marshalStable(value any) ([]byte, error) {
	// encoding/json orders string map keys, making generated files reproducible.
	return json.Marshal(value)
}

func fatal(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", arguments...)
	os.Exit(1)
}

const runtimeTemplate = `// Code generated by internal/api/cmd/runtimegen; DO NOT EDIT.
// Source: api/openapi.yaml

type Schema = Readonly<Record<string, unknown>>;
type Endpoint = Readonly<{
  method: string;
  path: string;
  requestRequired?: boolean;
  request?: Schema;
  responses: Readonly<Record<string, Schema>>;
}>;

const componentSchemas = __SCHEMAS__ as const satisfies Readonly<Record<string, Schema>>;
const endpoints = __ENDPOINTS__ as const satisfies readonly Endpoint[];

export type OpenAPISchemaName = keyof typeof componentSchemas;

function invalid(): never {
  throw new Error("invalid_response");
}

function record(value: unknown): Record<string, unknown> | null {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function resolve(schema: Schema): Schema {
  const reference = schema.$ref;
  if (typeof reference !== "string") return schema;
  const prefix = "#/components/schemas/";
  if (!reference.startsWith(prefix)) return invalid();
  const name = reference.slice(prefix.length) as OpenAPISchemaName;
  return componentSchemas[name] ?? invalid();
}

function validFormat(format: unknown, value: string): boolean {
  if (format === undefined || format === "binary") return true;
  if (format !== "date-time") return true;
  return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value)
    && Number.isFinite(Date.parse(value));
}

function validate(schemaInput: Schema, value: unknown, depth = 0): void {
  if (depth > 128) invalid();
  const schema = resolve(schemaInput);
  if (value === null && schema.nullable === true) return;

  const oneOf = schema.oneOf;
  if (Array.isArray(oneOf)) {
    let matches = 0;
    for (const candidate of oneOf) {
      try {
        validate(candidate as Schema, value, depth + 1);
        matches++;
      } catch { /* another variant may match */ }
    }
    if (matches !== 1) invalid();
    return;
  }
  const anyOf = schema.anyOf;
  if (Array.isArray(anyOf)) {
    for (const candidate of anyOf) {
      try {
        validate(candidate as Schema, value, depth + 1);
        return;
      } catch { /* try the next variant */ }
    }
    invalid();
  }
  const allOf = schema.allOf;
  if (Array.isArray(allOf)) {
    for (const candidate of allOf) validate(candidate as Schema, value, depth + 1);
    return;
  }

  const allowed = schema.enum;
  if (Array.isArray(allowed) && !allowed.some((candidate) => Object.is(candidate, value))) invalid();

  switch (schema.type) {
    case "string": {
      if (typeof value !== "string") invalid();
      if (typeof schema.minLength === "number" && value.length < schema.minLength) invalid();
      if (typeof schema.maxLength === "number" && value.length > schema.maxLength) invalid();
      if (typeof schema.pattern === "string" && !new RegExp(schema.pattern, "u").test(value)) invalid();
      if (!validFormat(schema.format, value)) invalid();
      return;
    }
    case "integer":
      if (typeof value !== "number" || !Number.isSafeInteger(value)) invalid();
      if (schema.format === "uint64" && value < 0) invalid();
      validateNumber(schema, value);
      return;
    case "number":
      if (typeof value !== "number" || !Number.isFinite(value)) invalid();
      validateNumber(schema, value);
      return;
    case "boolean":
      if (typeof value !== "boolean") invalid();
      return;
    case "array": {
      if (!Array.isArray(value)) invalid();
      if (typeof schema.minItems === "number" && value.length < schema.minItems) invalid();
      if (typeof schema.maxItems === "number" && value.length > schema.maxItems) invalid();
      if (schema.uniqueItems === true) {
        const fingerprints = value.map((item) => JSON.stringify(item));
        if (new Set(fingerprints).size !== fingerprints.length) invalid();
      }
      if (record(schema.items) !== null) {
        for (const item of value) validate(schema.items as Schema, item, depth + 1);
      }
      return;
    }
    case "object":
    case undefined:
      validateObject(schema, value, depth);
      return;
    default:
      invalid();
  }
}

function validateNumber(schema: Schema, value: number): void {
  if (typeof schema.minimum === "number" && value < schema.minimum) invalid();
  if (typeof schema.maximum === "number" && value > schema.maximum) invalid();
  if (typeof schema.exclusiveMinimum === "number" && value <= schema.exclusiveMinimum) invalid();
  if (typeof schema.exclusiveMaximum === "number" && value >= schema.exclusiveMaximum) invalid();
}

function validateObject(schema: Schema, value: unknown, depth: number): void {
  const object = record(value);
  if (object === null) invalid();
  const properties = record(schema.properties) ?? {};
  const required = Array.isArray(schema.required) ? schema.required : [];
  for (const name of required) {
    if (typeof name !== "string" || !Object.hasOwn(object, name)) invalid();
  }
  for (const [name, propertyValue] of Object.entries(object)) {
    const propertySchema = properties[name];
    if (record(propertySchema) !== null) {
      validate(propertySchema as Schema, propertyValue, depth + 1);
      continue;
    }
    if (schema.additionalProperties === false) invalid();
    if (record(schema.additionalProperties) !== null) {
      validate(schema.additionalProperties as Schema, propertyValue, depth + 1);
    }
  }
  const orderedPairs = schema["x-sshc-less-than-or-equal"];
  if (Array.isArray(orderedPairs)) {
    for (const pair of orderedPairs) {
      if (!Array.isArray(pair) || pair.length !== 2 || typeof pair[0] !== "string" || typeof pair[1] !== "string") invalid();
      const lower = object[pair[0]];
      const upper = object[pair[1]];
      if (typeof lower !== "number" || typeof upper !== "number" || lower > upper) invalid();
    }
  }
  const exclusiveGroups = schema["x-sshc-exactly-one"];
  if (Array.isArray(exclusiveGroups)) {
    for (const group of exclusiveGroups) {
      if (!Array.isArray(group) || group.length < 2 || group.some((name) => typeof name !== "string")) invalid();
      const present = group.filter((name) => Object.hasOwn(object, name as string)).length;
      if (present !== 1) invalid();
    }
  }
}

function pathMatches(template: string, actual: string): boolean {
  const expected = template.split("/");
  const received = actual.split("/");
  return expected.length === received.length && expected.every((part, index) =>
    /^\{[^}]+\}$/.test(part) ? (received[index]?.length ?? 0) > 0 : part === received[index]
  );
}

function endpointFor(method: string, path: string): Endpoint | undefined {
  return endpoints.find((candidate) => candidate.method === method.toUpperCase() && pathMatches(candidate.path, path));
}

export function validateOpenAPISchema<T>(name: OpenAPISchemaName, value: unknown): T {
  validate(componentSchemas[name], value);
  return value as T;
}

export function validateAPIRequest(method: string, path: string, value: unknown): void {
  const endpoint = endpointFor(method, path);
  // apiClient is also the low-level transport used by a few isolated callers and
  // contract tests. Only routes declared by this OpenAPI document are governed
  // here; a declared JSON route without a request schema is still an error.
  if (endpoint === undefined) return;
  if (endpoint.request === undefined) invalid();
  validate(endpoint.request, value);
}

export function validateAPIResponse<T>(method: string, path: string, status: number, value: unknown): T {
  const endpoint = endpointFor(method, path);
  if (endpoint === undefined) return value as T;
  const schema = endpoint?.responses[String(status)] ?? endpoint?.responses.default;
  if (schema === undefined) invalid();
  validate(schema, value);
  return value as T;
}
`
