import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Check,
  ChevronRight,
  Clock,
  CloudUpload,
  Copy,
  Cpu,
  Download,
  Ellipsis,
  File,
  FileCog,
  Files,
  Folder,
  FolderOpen,
  GlobeLock,
  GripVertical,
  House,
  Image,
  Keyboard,
  KeyRound,
  KeySquare,
  LockKeyhole,
  Maximize,
  Menu,
  Minus,
  PanelRight,
  Pause,
  Pencil,
  Play,
  Plus,
  RectangleEllipsis,
  RefreshCw,
  Scale,
  ScrollText,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Smartphone,
  SquareTerminal,
  Trash2,
  TriangleAlert,
  Unplug,
  Upload,
  X,
  type LucideIcon,
} from "lucide-react";

// 画面のアイコンは lucide（https://lucide.dev/icons/）から選び、形を手で描かない。
// 小さく手で描いた形は、似た別のもの（歯車と太陽など）に見えやすいからである。
// 名前は画面の中での役割で付け、どの lucide のアイコンを使うかはここだけで決める。
const shapes = {
  home: House,
  connections: Server,
  config: FileCog,
  groups: Folder,
  folder: Folder,
  file: File,
  openFile: FolderOpen,
  image: Image,
  keys: KeyRound,
  knownHosts: ShieldCheck,
  remoteKeys: CloudUpload,
  diagnostics: Activity,
  secrets: LockKeyhole,
  passwords: RectangleEllipsis,
  passphrases: KeySquare,
  otp: Smartphone,
  settings: Settings,
  engine: Cpu,
  keyboard: Keyboard,
  disconnect: Unplug,
  vpn: GlobeLock,
  files: Files,
  snippets: ScrollText,
  license: Scale,
  notification: Bell,
  sync: RefreshCw,
  history: Clock,
  inspector: PanelRight,
  moreHorizontal: Ellipsis,
  terminal: SquareTerminal,
  movePane: GripVertical,
  focus: Maximize,
  close: X,
  plus: Plus,
  minus: Minus,
  menu: Menu,
  search: Search,
  chevronRight: ChevronRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpDown: ArrowUpDown,
  arrowLeftRight: ArrowLeftRight,
  play: Play,
  pause: Pause,
  upload: Upload,
  download: Download,
  delete: Trash2,
  warning: TriangleAlert,
  edit: Pencil,
  copy: Copy,
  check: Check,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof shapes;

export const iconNames = Object.keys(shapes) as IconName[];

// iconStrokeWidth は、すべてのアイコンに共通の線の太さである。lucide の既定（2）では
// 隣に並ぶ文字よりアイコンが一段太く見えるので、それより細くする。
const iconStrokeWidth = 1.7;

export function Icon({ name, className = "h-4 w-4" }: { name: IconName; className?: string }) {
  const Shape = shapes[name];
  return <Shape aria-hidden="true" data-icon={name} className={`shrink-0 ${className}`} strokeWidth={iconStrokeWidth} />;
}
