import type { MessageKey } from "../i18n/messages";

// Engine failure codes that have their own wording in the sync screen.
export const syncRefusals: Record<string, MessageKey> = {
  not_configured: "sync.notConfigured",
  wrong_master_password: "sync.wrongMaster",
  wrong_passphrase: "sync.wrongKey",
  sync_key_missing: "sync.keyMissing",
  passphrase_too_short: "sync.keyTooShort",
  bucket_authentication_failed: "sync.bucketAuthenticationFailed",
  bucket_access_denied: "sync.bucketAccessDenied",
  bucket_rate_limited: "sync.bucketRateLimited",
  bucket_unavailable: "sync.bucketUnavailable",
  bucket_refused: "sync.unreachable",
  bucket_timeout: "sync.bucketTimeout",
  bucket_dns_failed: "sync.bucketDNSFailed",
  bucket_tls_failed: "sync.bucketTLSFailed",
  bucket_unreachable: "sync.bucketUnreachable",
  sync_failed: "sync.failed",
  sync_internal_failed: "sync.internalFailed",
  snapshot_download_incomplete: "sync.snapshotDownloadIncomplete",
  snapshot_cost_refused: "sync.snapshotCostRefused",
  snapshot_schema_unsupported: "sync.snapshotSchemaUnsupported",
  snapshot_rejected: "sync.snapshotRejected",
  snapshot_too_large: "sync.snapshotTooLarge",
  sync_no_snapshot: "sync.noSnapshot",
  endpoint_must_have_no_path: "sync.endpointPath",
  sync_remote_moved: "sync.remoteMoved",
  sync_remote_deleted: "sync.remoteDeleted",
  sync_key_recovery_required: "sync.keyRecoveryRequired",
  sync_key_recovery_target_change: "sync.keyRecoveryTargetChange",
  sync_history_key_loss_confirmation_required: "sync.keyHistoryLossConfirm",
  preview_stale: "sync.previewStale",
  sync_nothing_to_push: "sync.noLocalChanges",
  sync_commit_message_invalid: "sync.commitMessageInvalid",
  sync_ignore_invalid: "sync.exclusions.invalid",
  sync_setup_target_changed: "sync.setup.changed",
  sync_setup_target_incomplete: "sync.setup.incomplete",
  sync_local_changed: "sync.localChanged",
  sync_workspace_busy: "sync.workspaceBusy",
};
