import type { SyncStatus } from "../api/sync";
import { useTranslate } from "../i18n/context";
import { CheckboxField, sectionHeading } from "../ui/form";
import { Icon } from "../ui/icons";
import { PasswordInput } from "../ui/PasswordField";
import { Button } from "../ui/surface";
import type { SyncSetupForm } from "./useSyncSetupForm";

// The shared key that encrypts snapshots: generated by the engine or typed
// in, and replaceable at the cost of the history sealed with the old one.
export function SyncKeySection({ status, busy, form, onSave }: {
  status: SyncStatus;
  busy: boolean;
  form: Pick<SyncSetupForm, "chooseOwn" | "setChooseOwn" | "ownKey" | "setOwnKey" | "confirmHistoryLoss" | "setConfirmHistoryLoss">;
  onSave: () => void;
}) {
  const t = useTranslate();
  const { chooseOwn, setChooseOwn, ownKey, setOwnKey, confirmHistoryLoss, setConfirmHistoryLoss } = form;
  return (
    <section
      aria-labelledby="sync-key-heading"
      className="overflow-hidden rounded-md border border-line bg-card"
    >
      <header className="flex flex-wrap items-center justify-between gap-3 border-b border-line bg-toolbar px-4 py-3">
        <div className="flex items-center gap-2">
          <Icon name="sync" className="h-4 w-4 text-ink-muted" />
          <h3 id="sync-key-heading" className={sectionHeading}>
            {t("sync.key")}
          </h3>
        </div>
        <span
          className={`rounded-full px-2 py-1 text-xs font-medium ${status.keyConfigured ? "bg-select-fill text-accent" : "bg-notice text-notice-ink"}`}
        >
          {status.keyConfigured
            ? t("sync.keyReady")
            : t("sync.keyNeeded")}
        </span>
      </header>
      <div className="flex flex-col gap-3 p-4">
        <p className="text-sm leading-6 text-ink-muted">
          {t("sync.keyHint")}
        </p>
        <p className="text-sm font-medium text-ink">
          {t(status.keyConfigured ? "sync.keySet" : "sync.keyMissing")}
        </p>
        <div className="flex flex-col gap-3 border-t border-line pt-3">
          <CheckboxField label={t("sync.keyChooseOwn")} checked={chooseOwn} onChange={setChooseOwn} />
          {chooseOwn ? (
            <PasswordInput
              label={t("sync.keyOwnValue")}
              value={ownKey}
              onChange={setOwnKey}
            />
          ) : null}
          {status.keyConfigured ? (
            <CheckboxField label={t("sync.keyHistoryLossConfirm")} checked={confirmHistoryLoss} onChange={setConfirmHistoryLoss} tone="danger" />
          ) : null}
          <Button
            kind="primary"
            disabled={
              busy ||
              (chooseOwn && ownKey === "") ||
              (status.keyConfigured && !confirmHistoryLoss)
            }
            onClick={onSave}
            className="self-start"
          >
            {status.keyConfigured
              ? t("sync.keyReplace")
              : t("sync.keyCreate")}
          </Button>
        </div>
      </div>
    </section>
  );
}
