package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"sshc/cmd/sshc/internal/clispec"
)

func main() {
	output := flag.String("output", "", "generated Go output")
	flag.Parse()
	if *output == "" || flag.NArg() != 0 {
		fatal("usage: cligen -output <file>")
	}
	contents, err := generate()
	if err != nil {
		fatal("generate CLI contract: %v", err)
	}
	if err := os.WriteFile(*output, contents, 0o644); err != nil {
		fatal("write CLI contract: %v", err)
	}
}

func generate() ([]byte, error) {
	commands := clispec.Commands
	seenNames := map[string]bool{}
	seenSpellings := map[string]string{}
	seenRoutes := map[string]bool{}
	help := map[string]string{}
	var topLevel, helpTopics []string
	var source bytes.Buffer
	source.WriteString("// Code generated by cmd/sshc/internal/cligen; DO NOT EDIT.\n")
	source.WriteString("// Source: cmd/sshc/internal/clispec/spec.go\n\npackage main\n\n")
	source.WriteString("type cliCommandRoute uint8\n\nconst (\n\tcliCommandUnknown cliCommandRoute = iota\n")
	for _, command := range commands {
		if command.Name == "" || command.Route == "" || seenNames[command.Name] {
			return nil, fmt.Errorf("invalid or duplicate command %q", command.Name)
		}
		seenNames[command.Name] = true
		for _, spelling := range append([]string{command.Name}, command.Aliases...) {
			if spelling == "" {
				return nil, fmt.Errorf("command %q has an empty spelling", command.Name)
			}
			if owner, ok := seenSpellings[spelling]; ok {
				return nil, fmt.Errorf("command spelling %q is shared by %q and %q", spelling, owner, command.Name)
			}
			seenSpellings[spelling] = command.Name
		}
		if !seenRoutes[command.Route] {
			fmt.Fprintf(&source, "\tcliCommand%s\n", exported(command.Route))
			seenRoutes[command.Route] = true
		}
		if command.Help != "" {
			help[command.Name] = command.Help
			helpTopics = append(helpTopics, command.Name)
		}
		if command.Name[0] != '-' {
			topLevel = append(topLevel, command.Name)
		}
		for _, action := range command.Actions {
			topic := command.Name + " " + action.Name
			if action.Name == "" || action.Help == "" || help[topic] != "" {
				return nil, fmt.Errorf("invalid or duplicate action %q", topic)
			}
			help[topic] = action.Help
		}
	}
	for _, key := range []string{"completion-shells", "encodings", "wait-states", "serial-options", "telnet-options", "sftp-options", "sftp-settings-options"} {
		if len(clispec.Values[key]) == 0 {
			return nil, fmt.Errorf("CLI value set %q is empty or missing", key)
		}
	}
	source.WriteString(")\n\nfunc generatedCLICommand(word string) cliCommandRoute {\n\tswitch word {\n")
	for _, command := range commands {
		names := append([]string{command.Name}, command.Aliases...)
		fmt.Fprintf(&source, "\tcase %s:\n\t\treturn cliCommand%s\n", quotedList(names), exported(command.Route))
	}
	source.WriteString("\tdefault:\n\t\treturn cliCommandUnknown\n\t}\n}\n\n")
	source.WriteString("func canonicalCLICommand(route cliCommandRoute) string {\n\tswitch route {\n")
	for _, command := range commands {
		if command.Name[0] == '-' || command.Route != command.Name {
			continue
		}
		fmt.Fprintf(&source, "\tcase cliCommand%s:\n\t\treturn %s\n", exported(command.Route), strconv.Quote(command.Name))
	}
	source.WriteString("\tdefault:\n\t\treturn \"\"\n\t}\n}\n\n")

	source.WriteString("func validCLIAction(command, action string) bool {\n\tswitch command + \" \" + action {\n")
	for _, command := range commands {
		for _, action := range command.Actions {
			fmt.Fprintf(&source, "\tcase %s:\n\t\treturn true\n", strconv.Quote(command.Name+" "+action.Name))
		}
	}
	source.WriteString("\tdefault:\n\t\treturn false\n\t}\n}\n\n")
	source.WriteString("func validSyncAction(value string) bool { return validCLIAction(\"sync\", value) }\n")
	source.WriteString("func validTerminalAction(value string) bool { return validCLIAction(\"terminal\", value) }\n")
	source.WriteString("func validServiceAction(value string) bool { return validCLIAction(\"service\", value) }\n")
	source.WriteString("func validVaultAction(value string) bool { return validCLIAction(\"vault\", value) }\n")
	fmt.Fprintf(&source, "func validCompletionShell(value string) bool { return generatedStringSet(value, %s) }\n", stringSlice(clispec.Values["completion-shells"]))
	fmt.Fprintf(&source, "func validTerminalWaitState(value string) bool { return generatedStringSet(value, %s) }\n\n", stringSlice(clispec.Values["wait-states"]))
	source.WriteString("func generatedStringSet(value string, allowed []string) bool {\n\tfor _, candidate := range allowed { if value == candidate { return true } }\n\treturn false\n}\n\n")

	source.WriteString("func validHelpTopic(topic string) bool { _, ok := generatedCLIHelp[topic]; return ok }\n\n")
	fmt.Fprintf(&source, "const generatedGlobalHelp = %s\n\n", strconv.Quote(clispec.GlobalHelp))
	source.WriteString("var generatedCLIHelp = map[string]string{\n")
	keys := make([]string, 0, len(help))
	for key := range help {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(&source, "\t%s: %s,\n", strconv.Quote(key), strconv.Quote(help[key]))
	}
	source.WriteString("}\n\n")

	source.WriteString(`type completionGrammar struct {
	topLevel []string
	helpTopics []string
	syncActions []string
	terminalActions []string
	sftpActions []string
	serviceActions []string
	vaultActions []string
	encodings []string
	waitStates []string
	serialOptions []string
	telnetOptions []string
	sftpOptions []string
	sftpSettingsOptions []string
}

`)
	fmt.Fprintf(&source, "var cliCompletionGrammar = completionGrammar{\n\ttopLevel: %s,\n\thelpTopics: %s,\n", stringSlice(topLevel), stringSlice(helpTopics))
	for _, key := range []string{"sync", "terminal", "sftp", "service", "vault"} {
		fmt.Fprintf(&source, "\t%sActions: %s,\n", key, stringSlice(actionsFor(commands, key)))
	}
	fmt.Fprintf(&source, "\tencodings: %s,\n\twaitStates: %s,\n\tserialOptions: %s,\n\ttelnetOptions: %s,\n\tsftpOptions: %s,\n\tsftpSettingsOptions: %s,\n}\n",
		stringSlice(clispec.Values["encodings"]), stringSlice(clispec.Values["wait-states"]),
		stringSlice(clispec.Values["serial-options"]), stringSlice(clispec.Values["telnet-options"]),
		stringSlice(clispec.Values["sftp-options"]), stringSlice(clispec.Values["sftp-settings-options"]))
	return format.Source(source.Bytes())
}

func actionsFor(commands []clispec.Command, name string) []string {
	for _, command := range commands {
		if command.Name != name {
			continue
		}
		values := make([]string, 0, len(command.Actions))
		for _, action := range command.Actions {
			values = append(values, action.Name)
		}
		return values
	}
	return nil
}

func exported(value string) string {
	var result strings.Builder
	upper := true
	for _, character := range value {
		if character == '-' {
			upper = true
			continue
		}
		if upper {
			character = unicode.ToUpper(character)
			upper = false
		}
		result.WriteRune(character)
	}
	return result.String()
}

func quotedList(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return strings.Join(quoted, ", ")
}

func stringSlice(values []string) string {
	return "[]string{" + quotedList(values) + "}"
}

func fatal(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", arguments...)
	os.Exit(1)
}
