// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"encoding/json"
)

// Defines values for OpenTerminalSessionRequestKind.
const (
	OpenTerminalSessionRequestKindShell OpenTerminalSessionRequestKind = "shell"
	OpenTerminalSessionRequestKindSsh   OpenTerminalSessionRequestKind = "ssh"
)

// Valid indicates whether the value is a known member of the OpenTerminalSessionRequestKind enum.
func (e OpenTerminalSessionRequestKind) Valid() bool {
	switch e {
	case OpenTerminalSessionRequestKindShell:
		return true
	case OpenTerminalSessionRequestKindSsh:
		return true
	default:
		return false
	}
}

// Defines values for SyncDirection.
const (
	SyncDirectionBoth SyncDirection = "both"
	SyncDirectionPull SyncDirection = "pull"
	SyncDirectionPush SyncDirection = "push"
)

// Valid indicates whether the value is a known member of the SyncDirection enum.
func (e SyncDirection) Valid() bool {
	switch e {
	case SyncDirectionBoth:
		return true
	case SyncDirectionPull:
		return true
	case SyncDirectionPush:
		return true
	default:
		return false
	}
}

// Defines values for SyncOperationKind.
const (
	SyncOperationKindApply SyncOperationKind = "apply"
	SyncOperationKindPush  SyncOperationKind = "push"
)

// Valid indicates whether the value is a known member of the SyncOperationKind enum.
func (e SyncOperationKind) Valid() bool {
	switch e {
	case SyncOperationKindApply:
		return true
	case SyncOperationKindPush:
		return true
	default:
		return false
	}
}

// Defines values for TerminalSessionKind.
const (
	TerminalSessionKindShell TerminalSessionKind = "shell"
	TerminalSessionKindSsh   TerminalSessionKind = "ssh"
)

// Valid indicates whether the value is a known member of the TerminalSessionKind enum.
func (e TerminalSessionKind) Valid() bool {
	switch e {
	case TerminalSessionKindShell:
		return true
	case TerminalSessionKindSsh:
		return true
	default:
		return false
	}
}

// AgentIdentitiesResponse defines model for AgentIdentitiesResponse.
type AgentIdentitiesResponse struct {
	AgentAvailable bool            `json:"agentAvailable"`
	Id             string          `json:"id"`
	Identities     []AgentIdentity `json:"identities"`
}

// AgentIdentity defines model for AgentIdentity.
type AgentIdentity struct {
	Algorithm   string `json:"algorithm"`
	Bits        int    `json:"bits"`
	Comment     string `json:"comment"`
	Fingerprint string `json:"fingerprint"`
}

// AliasRequest defines model for AliasRequest.
type AliasRequest struct {
	Alias string `json:"alias"`
}

// AssignCredentialRequest defines model for AssignCredentialRequest.
type AssignCredentialRequest struct {
	Name    string `json:"name"`
	Subject string `json:"subject"`
}

// AuthenticationRequest defines model for AuthenticationRequest.
type AuthenticationRequest struct {
	AcknowledgeExecutable bool   `json:"acknowledgeExecutable"`
	Alias                 string `json:"alias"`
}

// AuthenticationResponse defines model for AuthenticationResponse.
type AuthenticationResponse struct {
	Authenticated bool   `json:"authenticated"`
	ElapsedMs     int    `json:"elapsedMs"`
	ExitCode      int    `json:"exitCode"`
	Outcome       string `json:"outcome"`
	Stderr        string `json:"stderr"`
	Truncated     bool   `json:"truncated"`
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// ChangeMasterPasswordRequest defines model for ChangeMasterPasswordRequest.
type ChangeMasterPasswordRequest struct {
	Current string `json:"current"`
	Next    string `json:"next"`
}

// ChangeMasterPasswordResult defines model for ChangeMasterPasswordResult.
type ChangeMasterPasswordResult struct {
	SnapshotProblem  *string             `json:"snapshotProblem,omitempty"`
	SnapshotResealed bool                `json:"snapshotResealed"`
	Vault            PasswordVaultStatus `json:"vault"`
}

// ChangePassphraseRequest defines model for ChangePassphraseRequest.
type ChangePassphraseRequest struct {
	CurrentPassphrase string `json:"currentPassphrase"`
	NewPassphrase     string `json:"newPassphrase"`
	Unencrypted       bool   `json:"unencrypted"`
}

// ChangePassphraseResponse defines model for ChangePassphraseResponse.
type ChangePassphraseResponse struct {
	Encrypted     bool     `json:"encrypted"`
	Id            string   `json:"id"`
	Notes         []string `json:"notes"`
	RelativePath  string   `json:"relativePath"`
	TransactionId string   `json:"transactionId"`
}

// ComplexityNote defines model for ComplexityNote.
type ComplexityNote struct {
	Code      string `json:"code"`
	Condition string `json:"condition"`
	Detail    string `json:"detail"`
	Line      int    `json:"line"`
	Path      string `json:"path"`
}

// ConfigCheckResponse defines model for ConfigCheckResponse.
type ConfigCheckResponse struct {
	Diagnostics []ConfigDiagnostic  `json:"diagnostics"`
	Files       []ConfigFileSummary `json:"files"`
	Root        string              `json:"root"`
}

// ConfigDiagnostic defines model for ConfigDiagnostic.
type ConfigDiagnostic struct {
	Code     string `json:"code"`
	Detail   string `json:"detail"`
	Line     int    `json:"line"`
	Path     string `json:"path"`
	Severity string `json:"severity"`
}

// ConfigFileSummary defines model for ConfigFileSummary.
type ConfigFileSummary struct {
	Editable bool   `json:"editable"`
	Includes int    `json:"includes"`
	Loads    int    `json:"loads"`
	Missing  bool   `json:"missing"`
	Path     string `json:"path"`
}

// ConflictReport defines model for ConflictReport.
type ConflictReport struct {
	BaseDigest     *string    `json:"baseDigest,omitempty"`
	DiskDigest     *string    `json:"diskDigest,omitempty"`
	ExternalChange []DiffLine `json:"externalChange"`
	LocalChange    []DiffLine `json:"localChange"`
	Path           string     `json:"path"`
}

// ConnectionIdentityFileChange defines model for ConnectionIdentityFileChange.
type ConnectionIdentityFileChange = json.RawMessage

// ConnectionIdentityFileSet defines model for ConnectionIdentityFileSet.
type ConnectionIdentityFileSet struct {
	Action string `json:"action"`
	KeyId  string `json:"keyId"`
}

// ConnectionInherit defines model for ConnectionInherit.
type ConnectionInherit struct {
	Action string `json:"action"`
}

// ConnectionKeyPassphraseSetDedicated defines model for ConnectionKeyPassphraseSetDedicated.
type ConnectionKeyPassphraseSetDedicated struct {
	KeyId      string `json:"keyId"`
	Kind       string `json:"kind"`
	Passphrase string `json:"passphrase"`
}

// ConnectionKeyPassphraseUnchanged defines model for ConnectionKeyPassphraseUnchanged.
type ConnectionKeyPassphraseUnchanged struct {
	Kind string `json:"kind"`
}

// ConnectionPortChange defines model for ConnectionPortChange.
type ConnectionPortChange = json.RawMessage

// ConnectionPortSet defines model for ConnectionPortSet.
type ConnectionPortSet struct {
	Action string `json:"action"`
	Value  int    `json:"value"`
}

// ConnectionStringChange defines model for ConnectionStringChange.
type ConnectionStringChange = json.RawMessage

// ConnectionStringSet defines model for ConnectionStringSet.
type ConnectionStringSet struct {
	Action string `json:"action"`
	Value  string `json:"value"`
}

// CreateConnectionAuthentication defines model for CreateConnectionAuthentication.
type CreateConnectionAuthentication = json.RawMessage

// CreateConnectionRequest defines model for CreateConnectionRequest.
type CreateConnectionRequest struct {
	Alias          string                         `json:"alias"`
	Authentication CreateConnectionAuthentication `json:"authentication"`
	Group          *string                        `json:"group,omitempty"`
	HostName       string                         `json:"hostName"`
	Port           *int                           `json:"port,omitempty"`
	User           *string                        `json:"user,omitempty"`
}

// CreateConnectionResponse defines model for CreateConnectionResponse.
type CreateConnectionResponse struct {
	Identity      HostIdentity `json:"identity"`
	Preview       SavePreview  `json:"preview"`
	TransactionId string       `json:"transactionId"`
}

// CreateDedicatedPasswordAuthentication defines model for CreateDedicatedPasswordAuthentication.
type CreateDedicatedPasswordAuthentication struct {
	Kind     string `json:"kind"`
	Password string `json:"password"`
}

// CreateIdentityFileAuthentication defines model for CreateIdentityFileAuthentication.
type CreateIdentityFileAuthentication struct {
	KeyId string `json:"keyId"`
	Kind  string `json:"kind"`
}

// CreateNewSharedPasswordAuthentication defines model for CreateNewSharedPasswordAuthentication.
type CreateNewSharedPasswordAuthentication struct {
	Credential string `json:"credential"`
	Kind       string `json:"kind"`
	Password   string `json:"password"`
}

// CreateSavedPasswordAuthentication defines model for CreateSavedPasswordAuthentication.
type CreateSavedPasswordAuthentication struct {
	Credential string `json:"credential"`
	Kind       string `json:"kind"`
}

// Credential defines model for Credential.
type Credential struct {
	Hosts []string `json:"hosts"`
	Kind  string   `json:"kind"`
	Name  string   `json:"name"`
	Uses  []string `json:"uses"`
}

// CredentialList defines model for CredentialList.
type CredentialList struct {
	Credentials             []Credential                  `json:"credentials"`
	DedicatedKeyPassphrases []DedicatedKeyPassphraseUsage `json:"dedicatedKeyPassphrases"`
	KeyHostUsageComplete    bool                          `json:"keyHostUsageComplete"`
}

// DedicatedKeyPassphraseUsage defines model for DedicatedKeyPassphraseUsage.
type DedicatedKeyPassphraseUsage struct {
	Hosts []string `json:"hosts"`
	Key   string   `json:"key"`
}

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Absolute *string `json:"absolute,omitempty"`
	Code     string  `json:"code"`
	Detail   *string `json:"detail,omitempty"`
	External *bool   `json:"external,omitempty"`
	Line     *int    `json:"line,omitempty"`
	Path     *string `json:"path,omitempty"`
	Severity string  `json:"severity"`
}

// DiffLine defines model for DiffLine.
type DiffLine struct {
	NewLine *int   `json:"newLine,omitempty"`
	OldLine *int   `json:"oldLine,omitempty"`
	Op      string `json:"op"`
	Text    string `json:"text"`
}

// EditRequest defines model for EditRequest.
type EditRequest struct {
	Alias            *string      `json:"alias,omitempty"`
	Base             *string      `json:"base,omitempty"`
	Comment          *string      `json:"comment,omitempty"`
	DestinationBase  *string      `json:"destinationBase,omitempty"`
	DestinationGroup *string      `json:"destinationGroup,omitempty"`
	DestinationPath  *string      `json:"destinationPath,omitempty"`
	Fields           *[]FieldEdit `json:"fields,omitempty"`
	Kind             string       `json:"kind"`
	Metadata         *Metadata    `json:"metadata,omitempty"`
	NewAlias         *string      `json:"newAlias,omitempty"`
	Path             *string      `json:"path,omitempty"`
	Raw              *string      `json:"raw,omitempty"`
}

// Effective defines model for Effective.
type Effective struct {
	Alias       string           `json:"alias"`
	Approximate bool             `json:"approximate"`
	Entries     []EffectiveEntry `json:"entries"`
	Notices     *[]Notice        `json:"notices,omitempty"`
}

// EffectiveChange defines model for EffectiveChange.
type EffectiveChange struct {
	After         []string  `json:"after"`
	AfterSources  *[]Source `json:"afterSources,omitempty"`
	Before        []string  `json:"before"`
	BeforeSources *[]Source `json:"beforeSources,omitempty"`
	Keyword       string    `json:"keyword"`
}

// EffectiveDiff defines model for EffectiveDiff.
type EffectiveDiff struct {
	Alias   string            `json:"alias"`
	Changes []EffectiveChange `json:"changes"`
}

// EffectiveEntry defines model for EffectiveEntry.
type EffectiveEntry struct {
	Keyword string   `json:"keyword"`
	Source  Source   `json:"source"`
	Values  []string `json:"values"`
}

// EffectiveResponse defines model for EffectiveResponse.
type EffectiveResponse struct {
	Alias                string                `json:"alias"`
	Complexities         []ComplexityNote      `json:"complexities"`
	Evaluated            bool                  `json:"evaluated"`
	ExecutableDirectives []ExecutableDirective `json:"executableDirectives"`
	Failure              OpenSSHFailure        `json:"failure"`
	RequiresConfirmation bool                  `json:"requiresConfirmation"`
	Route                []JumpStage           `json:"route"`
	Sources              []ValueSource         `json:"sources"`
	TokenWarning         string                `json:"tokenWarning"`
	Values               []EffectiveValue      `json:"values"`
}

// EffectiveValue defines model for EffectiveValue.
type EffectiveValue struct {
	Keyword string   `json:"keyword"`
	Values  []string `json:"values"`
}

// EmbeddedTerminal defines model for EmbeddedTerminal.
type EmbeddedTerminal struct {
	MaxSessions     *int `json:"maxSessions,omitempty"`
	ScrollbackBytes *int `json:"scrollbackBytes,omitempty"`
}

// ExecutableDirective defines model for ExecutableDirective.
type ExecutableDirective struct {
	Command     string `json:"command"`
	Condition   string `json:"condition"`
	Keyword     string `json:"keyword"`
	Line        int    `json:"line"`
	OnConnect   bool   `json:"onConnect"`
	OnEvaluate  bool   `json:"onEvaluate"`
	Overridable bool   `json:"overridable"`
	Path        string `json:"path"`
}

// FieldEdit defines model for FieldEdit.
type FieldEdit struct {
	Action  string    `json:"action"`
	Keyword *string   `json:"keyword,omitempty"`
	Line    *int      `json:"line,omitempty"`
	Values  *[]string `json:"values,omitempty"`
}

// FileContents defines model for FileContents.
type FileContents struct {
	Contents string  `json:"contents"`
	Digest   string  `json:"digest"`
	Editable bool    `json:"editable"`
	Exists   bool    `json:"exists"`
	File     FileRef `json:"file"`
}

// FileDiff defines model for FileDiff.
type FileDiff struct {
	Created   *bool      `json:"created,omitempty"`
	Lines     []DiffLine `json:"lines"`
	NewDigest *string    `json:"newDigest,omitempty"`
	OldDigest *string    `json:"oldDigest,omitempty"`
	Path      string     `json:"path"`
	Removed   *bool      `json:"removed,omitempty"`
	Truncated *bool      `json:"truncated,omitempty"`
}

// FileNode defines model for FileNode.
type FileNode struct {
	Editable bool                `json:"editable"`
	File     FileRef             `json:"file"`
	Includes *[]IncludeReference `json:"includes,omitempty"`
	Loads    int                 `json:"loads"`
	Missing  *bool               `json:"missing,omitempty"`
}

// FileRef defines model for FileRef.
type FileRef struct {
	Absolute string  `json:"absolute"`
	External *bool   `json:"external,omitempty"`
	Path     *string `json:"path,omitempty"`
}

// FormField defines model for FormField.
type FormField struct {
	Category  string   `json:"category"`
	Dangerous *bool    `json:"dangerous,omitempty"`
	Duplicate *bool    `json:"duplicate,omitempty"`
	Editable  bool     `json:"editable"`
	Keyword   string   `json:"keyword"`
	Line      int      `json:"line"`
	Values    []string `json:"values"`
}

// GenerateKeyRequest defines model for GenerateKeyRequest.
type GenerateKeyRequest struct {
	Algorithm   string  `json:"algorithm"`
	Bits        *int    `json:"bits,omitempty"`
	Comment     string  `json:"comment"`
	FileName    string  `json:"fileName"`
	Group       *string `json:"group,omitempty"`
	Passphrase  string  `json:"passphrase"`
	Unencrypted bool    `json:"unencrypted"`
}

// GenerateKeyResponse defines model for GenerateKeyResponse.
type GenerateKeyResponse struct {
	Bits               int    `json:"bits"`
	Encrypted          bool   `json:"encrypted"`
	Fingerprint        string `json:"fingerprint"`
	Id                 string `json:"id"`
	KeyType            string `json:"keyType"`
	PublicRelativePath string `json:"publicRelativePath"`
	RelativePath       string `json:"relativePath"`
	TransactionId      string `json:"transactionId"`
}

// GroupDeleteRequest defines model for GroupDeleteRequest.
type GroupDeleteRequest struct {
	Destination *string `json:"destination,omitempty"`
	Name        string  `json:"name"`
}

// GroupMetadata defines model for GroupMetadata.
type GroupMetadata struct {
	Colour   *string    `json:"colour,omitempty"`
	Hidden   *bool      `json:"hidden,omitempty"`
	Name     string     `json:"name"`
	Note     *string    `json:"note,omitempty"`
	Order    *int       `json:"order,omitempty"`
	Settings *[]Setting `json:"settings,omitempty"`
}

// GroupRenameRequest defines model for GroupRenameRequest.
type GroupRenameRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// GroupView defines model for GroupView.
type GroupView struct {
	Colour           *string    `json:"colour,omitempty"`
	Directory        string     `json:"directory"`
	DirectoryPresent bool       `json:"directoryPresent"`
	KeyDirectory     string     `json:"keyDirectory"`
	MemberCount      int        `json:"memberCount"`
	Name             string     `json:"name"`
	Note             *string    `json:"note,omitempty"`
	Order            *int       `json:"order,omitempty"`
	Parent           *string    `json:"parent,omitempty"`
	Settings         *[]Setting `json:"settings,omitempty"`
}

// HardwareCommandRequest defines model for HardwareCommandRequest.
type HardwareCommandRequest struct {
	Algorithm string  `json:"algorithm"`
	Comment   string  `json:"comment"`
	FileName  string  `json:"fileName"`
	Group     *string `json:"group,omitempty"`
}

// HardwareCommandResponse defines model for HardwareCommandResponse.
type HardwareCommandResponse struct {
	Algorithm string   `json:"algorithm"`
	Command   []string `json:"command"`
	Note      string   `json:"note"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// HistoryEntry defines model for HistoryEntry.
type HistoryEntry struct {
	FinishedAt *string   `json:"finishedAt,omitempty"`
	Id         string    `json:"id"`
	Operation  string    `json:"operation"`
	Paths      []string  `json:"paths"`
	Restorable *[]string `json:"restorable,omitempty"`
	StartedAt  string    `json:"startedAt"`
	Status     string    `json:"status"`
}

// HistoryList defines model for HistoryList.
type HistoryList struct {
	Entries []HistoryEntry `json:"entries"`
}

// HostDetail defines model for HostDetail.
type HostDetail struct {
	Effective Effective    `json:"effective"`
	File      FileContents `json:"file"`
	Form      HostForm     `json:"form"`
	Metadata  HostMetadata `json:"metadata"`
}

// HostEntry defines model for HostEntry.
type HostEntry struct {
	Duplicate *bool        `json:"duplicate,omitempty"`
	Editable  bool         `json:"editable"`
	File      FileRef      `json:"file"`
	Group     *string      `json:"group,omitempty"`
	Identity  HostIdentity `json:"identity"`
	Line      int          `json:"line"`
	Negated   *bool        `json:"negated,omitempty"`
	Patterns  []string     `json:"patterns"`
	Wildcard  *bool        `json:"wildcard,omitempty"`
}

// HostForm defines model for HostForm.
type HostForm struct {
	// Comment The comment lines attached above the Host line, with the '#' markers stripped. Empty when the block has none. ssh_config has no trailing comment syntax, so only whole lines are ever attached.
	Comment string `json:"comment"`

	// CommentLines How many physical lines the attached comment occupies. A client rewriting the whole file needs the count to include those lines; it cannot be derived from comment, whose markers and indentation were stripped.
	CommentLines int         `json:"commentLines"`
	Entry        HostEntry   `json:"entry"`
	Fields       []FormField `json:"fields"`
	Notices      *[]Notice   `json:"notices,omitempty"`
	Raw          string      `json:"raw"`
}

// HostIdentity defines model for HostIdentity.
type HostIdentity struct {
	Alias string `json:"alias"`
	Path  string `json:"path"`
}

// HostMetadata defines model for HostMetadata.
type HostMetadata struct {
	Colour    *string      `json:"colour,omitempty"`
	Favourite *bool        `json:"favourite,omitempty"`
	Identity  HostIdentity `json:"identity"`
	Note      *string      `json:"note,omitempty"`
	Order     *int         `json:"order,omitempty"`
	Orphan    *bool        `json:"orphan,omitempty"`
	Tags      *[]string    `json:"tags,omitempty"`
}

// IncludeReference defines model for IncludeReference.
type IncludeReference struct {
	Condition *string    `json:"condition,omitempty"`
	Line      int        `json:"line"`
	Matches   *[]FileRef `json:"matches,omitempty"`
	Pattern   string     `json:"pattern"`
}

// IssueActionRequest defines model for IssueActionRequest.
type IssueActionRequest struct {
	Kind   string `json:"kind"`
	Target string `json:"target"`
}

// IssueActionResponse defines model for IssueActionResponse.
type IssueActionResponse struct {
	ExpiresAt string `json:"expiresAt"`
	Token     string `json:"token"`
}

// JumpStage defines model for JumpStage.
type JumpStage struct {
	Complex  bool   `json:"complex"`
	Depth    int    `json:"depth"`
	Hop      string `json:"hop"`
	Hostname string `json:"hostname"`
	Order    int    `json:"order"`
	Parent   string `json:"parent"`
	Port     string `json:"port"`
	User     string `json:"user"`
}

// KeyAlgorithmsResponse defines model for KeyAlgorithmsResponse.
type KeyAlgorithmsResponse struct {
	Diagnostic string       `json:"diagnostic"`
	Source     string       `json:"source"`
	Variants   []KeyVariant `json:"variants"`
}

// KeyCertificate defines model for KeyCertificate.
type KeyCertificate struct {
	KeyId                string   `json:"keyId"`
	NeverExpires         bool     `json:"neverExpires"`
	Principals           []string `json:"principals"`
	SignedKeyFingerprint string   `json:"signedKeyFingerprint"`
	SignedKeyType        string   `json:"signedKeyType"`
	ValidBefore          int      `json:"validBefore"`
}

// KeyInventoryResponse defines model for KeyInventoryResponse.
type KeyInventoryResponse struct {
	AgentAvailable       bool                  `json:"agentAvailable"`
	AgentDelegations     []KeyReference        `json:"agentDelegations"`
	AgentIdentities      []AgentIdentity       `json:"agentIdentities"`
	Items                []KeyItem             `json:"items"`
	Unreadable           []UnreadableFile      `json:"unreadable"`
	UnresolvedReferences []UnresolvedReference `json:"unresolvedReferences"`
}

// KeyItem defines model for KeyItem.
type KeyItem struct {
	Algorithm      string          `json:"algorithm"`
	Bits           int             `json:"bits"`
	Certificate    *KeyCertificate `json:"certificate,omitempty"`
	Comment        string          `json:"comment"`
	Container      string          `json:"container"`
	Encrypted      bool            `json:"encrypted"`
	Fingerprint    string          `json:"fingerprint"`
	Id             string          `json:"id"`
	KeyType        string          `json:"keyType"`
	Kind           string          `json:"kind"`
	Notes          []string        `json:"notes"`
	Permission     string          `json:"permission"`
	PermissionRisk bool            `json:"permissionRisk"`
	References     []KeyReference  `json:"references"`
	RelativePath   string          `json:"relativePath"`
	SizeBytes      int             `json:"sizeBytes"`
}

// KeyReference defines model for KeyReference.
type KeyReference struct {
	Condition    string   `json:"condition"`
	ConfigPath   string   `json:"configPath"`
	Directive    string   `json:"directive"`
	HostPatterns []string `json:"hostPatterns"`
	Line         int      `json:"line"`
	Value        string   `json:"value"`
}

// KeyVariant defines model for KeyVariant.
type KeyVariant struct {
	Algorithm string `json:"algorithm"`
	Bits      int    `json:"bits"`
	InProcess bool   `json:"inProcess"`
	Label     string `json:"label"`
	Reason    string `json:"reason"`
}

// KnownHostCandidate defines model for KnownHostCandidate.
type KnownHostCandidate struct {
	Fingerprint string `json:"fingerprint"`
	Host        string `json:"host"`
	Key         string `json:"key"`
	KeyType     string `json:"keyType"`
	Port        int    `json:"port"`
	Verified    bool   `json:"verified"`
}

// KnownHostEntry defines model for KnownHostEntry.
type KnownHostEntry struct {
	Comment     string   `json:"comment"`
	Digest      string   `json:"digest"`
	Fingerprint string   `json:"fingerprint"`
	Hashed      bool     `json:"hashed"`
	Hosts       []string `json:"hosts"`
	KeyType     string   `json:"keyType"`
	Line        int      `json:"line"`
	Marker      string   `json:"marker"`
}

// KnownHostTarget defines model for KnownHostTarget.
type KnownHostTarget struct {
	Digest string `json:"digest"`
	Line   int    `json:"line"`
}

// KnownHostsAddRequest defines model for KnownHostsAddRequest.
type KnownHostsAddRequest struct {
	Acknowledged        bool   `json:"acknowledged"`
	ExpectedFingerprint string `json:"expectedFingerprint"`
	Host                string `json:"host"`
	Key                 string `json:"key"`
	KeyType             string `json:"keyType"`
	Port                int    `json:"port"`
}

// KnownHostsChangeResponse defines model for KnownHostsChangeResponse.
type KnownHostsChangeResponse struct {
	Changed       bool   `json:"changed"`
	TransactionId string `json:"transactionId"`
}

// KnownHostsDeleteRequest defines model for KnownHostsDeleteRequest.
type KnownHostsDeleteRequest struct {
	Entries []KnownHostTarget `json:"entries"`
}

// KnownHostsResponse defines model for KnownHostsResponse.
type KnownHostsResponse struct {
	Entries []KnownHostEntry `json:"entries"`
	Path    string           `json:"path"`
}

// KnownHostsScanRequest defines model for KnownHostsScanRequest.
type KnownHostsScanRequest struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

// KnownHostsScanResponse defines model for KnownHostsScanResponse.
type KnownHostsScanResponse struct {
	Candidates []KnownHostCandidate `json:"candidates"`
	Notice     string               `json:"notice"`
}

// LoginItem defines model for LoginItem.
type LoginItem struct {
	Enabled   bool `json:"enabled"`
	Supported bool `json:"supported"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	EmbeddedTerminal *EmbeddedTerminal `json:"embeddedTerminal,omitempty"`
	Groups           *[]GroupMetadata  `json:"groups,omitempty"`
	GroupsFile       *string           `json:"groupsFile,omitempty"`
	Hosts            *[]HostMetadata   `json:"hosts,omitempty"`
	SchemaVersion    int               `json:"schemaVersion"`
}

// Notice defines model for Notice.
type Notice struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Line   *int    `json:"line,omitempty"`
	Path   *string `json:"path,omitempty"`
}

// OpenSSHFailure defines model for OpenSSHFailure.
type OpenSSHFailure struct {
	ExitCode  int    `json:"exitCode"`
	Failed    bool   `json:"failed"`
	Stderr    string `json:"stderr"`
	Truncated bool   `json:"truncated"`
}

// OpenTerminalSessionRequest defines model for OpenTerminalSessionRequest.
type OpenTerminalSessionRequest struct {
	Alias *string                        `json:"alias,omitempty"`
	Cols  *int                           `json:"cols,omitempty"`
	Kind  OpenTerminalSessionRequestKind `json:"kind"`
	Rows  *int                           `json:"rows,omitempty"`
}

// OpenTerminalSessionRequestKind defines model for OpenTerminalSessionRequest.Kind.
type OpenTerminalSessionRequestKind string

// OpenTerminalSessionResponse defines model for OpenTerminalSessionResponse.
type OpenTerminalSessionResponse struct {
	Session      TerminalSession `json:"session"`
	StreamTicket string          `json:"streamTicket"`
}

// Overview defines model for Overview.
type Overview struct {
	Diagnostics []Diagnostic          `json:"diagnostics"`
	Entry       FileRef               `json:"entry"`
	Files       []FileNode            `json:"files"`
	Groups      []GroupView           `json:"groups"`
	Hosts       []HostEntry           `json:"hosts"`
	Metadata    Metadata              `json:"metadata"`
	Notices     []Notice              `json:"notices"`
	Pending     *[]PendingTransaction `json:"pending,omitempty"`
}

// PassphraseRequest defines model for PassphraseRequest.
type PassphraseRequest struct {
	Passphrase string `json:"passphrase"`
}

// PasswordEligibility defines model for PasswordEligibility.
type PasswordEligibility struct {
	Alias    string   `json:"alias"`
	Blockers []Notice `json:"blockers"`
	HostName *string  `json:"hostName,omitempty"`
	Port     *string  `json:"port,omitempty"`
	Storable bool     `json:"storable"`
	Warnings []Notice `json:"warnings"`
}

// PasswordVaultStatus defines model for PasswordVaultStatus.
type PasswordVaultStatus struct {
	Aliases                 []string `json:"aliases"`
	DedicatedKeyPassphrases []string `json:"dedicatedKeyPassphrases"`
	Exists                  bool     `json:"exists"`
	MinPassphraseLength     *int     `json:"minPassphraseLength,omitempty"`
	Unlocked                bool     `json:"unlocked"`
}

// PendingTransaction defines model for PendingTransaction.
type PendingTransaction struct {
	CanComplete bool     `json:"canComplete"`
	Committed   int      `json:"committed"`
	Id          string   `json:"id"`
	Operation   string   `json:"operation"`
	Paths       []string `json:"paths"`
	StartedAt   string   `json:"startedAt"`
	Status      string   `json:"status"`
}

// Problem defines model for Problem.
type Problem struct {
	Code        string          `json:"code"`
	Column      *int            `json:"column,omitempty"`
	Conflict    *ConflictReport `json:"conflict,omitempty"`
	Detail      *string         `json:"detail,omitempty"`
	Diagnostics *[]Diagnostic   `json:"diagnostics,omitempty"`
	Line        *int            `json:"line,omitempty"`
	Message     string          `json:"message"`
	Path        *string         `json:"path,omitempty"`
}

// PublicKeyResponse defines model for PublicKeyResponse.
type PublicKeyResponse struct {
	Comment      string `json:"comment"`
	Fingerprint  string `json:"fingerprint"`
	Id           string `json:"id"`
	PublicKey    string `json:"publicKey"`
	RelativePath string `json:"relativePath"`
}

// PullRequest defines model for PullRequest.
type PullRequest struct {
	Apply      *bool  `json:"apply,omitempty"`
	Passphrase string `json:"passphrase"`
}

// PullResponse defines model for PullResponse.
type PullResponse struct {
	Applied         bool            `json:"applied"`
	CompletedAt     string          `json:"completedAt"`
	Conflicts       []SyncConflict  `json:"conflicts"`
	DownloadedBytes int64           `json:"downloadedBytes"`
	Origin          *string         `json:"origin,omitempty"`
	Removed         []string        `json:"removed"`
	Summary         SnapshotSummary `json:"summary"`
	Written         []string        `json:"written"`
}

// PurgeTrashResponse defines model for PurgeTrashResponse.
type PurgeTrashResponse struct {
	EntryId       string   `json:"entryId"`
	Removed       []string `json:"removed"`
	TransactionId string   `json:"transactionId"`
}

// PushResponse defines model for PushResponse.
type PushResponse struct {
	Result PushResult `json:"result"`
	Status SyncStatus `json:"status"`
}

// PushResult defines model for PushResult.
type PushResult struct {
	CompletedAt   string          `json:"completedAt"`
	ObjectCount   int             `json:"objectCount"`
	Summary       SnapshotSummary `json:"summary"`
	UploadedBytes int64           `json:"uploadedBytes"`
}

// ReachabilityResponse defines model for ReachabilityResponse.
type ReachabilityResponse struct {
	Address   string `json:"address"`
	Detail    string `json:"detail"`
	ElapsedMs int    `json:"elapsedMs"`
	Notice    string `json:"notice"`
	Outcome   string `json:"outcome"`
}

// RecoverRequest defines model for RecoverRequest.
type RecoverRequest struct {
	Action        string `json:"action"`
	TransactionId string `json:"transactionId"`
}

// RecoverResponse defines model for RecoverResponse.
type RecoverResponse struct {
	Status string `json:"status"`
}

// RegisterKeyRequest defines model for RegisterKeyRequest.
type RegisterKeyRequest struct {
	LifetimeSeconds int    `json:"lifetimeSeconds"`
	Passphrase      string `json:"passphrase"`
}

// RegisterKeyResponse defines model for RegisterKeyResponse.
type RegisterKeyResponse struct {
	Fingerprint     string          `json:"fingerprint"`
	Id              string          `json:"id"`
	Identities      []AgentIdentity `json:"identities"`
	LifetimeSeconds int             `json:"lifetimeSeconds"`
	RelativePath    string          `json:"relativePath"`
}

// RelocateKeyRequest defines model for RelocateKeyRequest.
type RelocateKeyRequest struct {
	Group   *string `json:"group,omitempty"`
	NewName *string `json:"newName,omitempty"`
}

// RelocateKeyResponse defines model for RelocateKeyResponse.
type RelocateKeyResponse struct {
	Blockers      []string                `json:"blockers"`
	Files         []RelocatedKeyFile      `json:"files"`
	Group         string                  `json:"group"`
	Id            string                  `json:"id"`
	Notes         []string                `json:"notes"`
	References    []RewrittenKeyReference `json:"references"`
	RelativePath  string                  `json:"relativePath"`
	Skipped       []string                `json:"skipped"`
	TransactionId string                  `json:"transactionId"`
}

// RelocatedKeyFile defines model for RelocatedKeyFile.
type RelocatedKeyFile struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// RemoteKeyPlan defines model for RemoteKeyPlan.
type RemoteKeyPlan struct {
	ActionExpiresAt      string                `json:"actionExpiresAt"`
	ActionToken          string                `json:"actionToken"`
	Alias                string                `json:"alias"`
	ExecutableDirectives []ExecutableDirective `json:"executableDirectives"`
	Fingerprint          string                `json:"fingerprint"`
	Hostname             string                `json:"hostname"`
	KeyLine              string                `json:"keyLine"`
	KeyPath              string                `json:"keyPath"`
	Manual               []string              `json:"manual"`
	Port                 string                `json:"port"`
	RemotePath           string                `json:"remotePath"`
	Routine              string                `json:"routine"`
	Supported            bool                  `json:"supported"`
	User                 string                `json:"user"`
	ValuesFrom           string                `json:"valuesFrom"`
}

// RemoteKeyPlanRequest defines model for RemoteKeyPlanRequest.
type RemoteKeyPlanRequest struct {
	Alias     string `json:"alias"`
	KeyPath   string `json:"keyPath"`
	PublicKey string `json:"publicKey"`
}

// RemoteKeyRegisterRequest defines model for RemoteKeyRegisterRequest.
type RemoteKeyRegisterRequest struct {
	AcknowledgeExecutable bool   `json:"acknowledgeExecutable"`
	Alias                 string `json:"alias"`
	KeyPath               string `json:"keyPath"`
	PublicKey             string `json:"publicKey"`
}

// RemoteKeyRegisterResponse defines model for RemoteKeyRegisterResponse.
type RemoteKeyRegisterResponse struct {
	ExitCode  int    `json:"exitCode"`
	Outcome   string `json:"outcome"`
	Stderr    string `json:"stderr"`
	Truncated bool   `json:"truncated"`
}

// RestoreRequest defines model for RestoreRequest.
type RestoreRequest struct {
	Path          string `json:"path"`
	TransactionId string `json:"transactionId"`
}

// RestoreTrashResponse defines model for RestoreTrashResponse.
type RestoreTrashResponse struct {
	Blockers      []string `json:"blockers"`
	EntryId       string   `json:"entryId"`
	Restored      []string `json:"restored"`
	TransactionId string   `json:"transactionId"`
}

// RevealPrivateKeyResponse defines model for RevealPrivateKeyResponse.
type RevealPrivateKeyResponse struct {
	Encrypted     bool   `json:"encrypted"`
	Fingerprint   string `json:"fingerprint"`
	Id            string `json:"id"`
	PrivateKey    string `json:"privateKey"`
	RelativePath  string `json:"relativePath"`
	TransactionId string `json:"transactionId"`
}

// RewrittenKeyReference defines model for RewrittenKeyReference.
type RewrittenKeyReference struct {
	ConfigPath string `json:"configPath"`
	Directive  string `json:"directive"`
	From       string `json:"from"`
	Line       int    `json:"line"`
	To         string `json:"to"`
}

// SavePreview defines model for SavePreview.
type SavePreview struct {
	Diffs     []FileDiff       `json:"diffs"`
	Effective *[]EffectiveDiff `json:"effective,omitempty"`
	Notices   *[]Notice        `json:"notices,omitempty"`
	Operation string           `json:"operation"`
}

// SaveResult defines model for SaveResult.
type SaveResult struct {
	Preview       SavePreview `json:"preview"`
	TransactionId string      `json:"transactionId"`
	Written       []string    `json:"written"`
}

// Setting defines model for Setting.
type Setting struct {
	Keyword string   `json:"keyword"`
	Values  []string `json:"values"`
}

// SnapshotSummary defines model for SnapshotSummary.
type SnapshotSummary struct {
	CreatedAt     string `json:"createdAt"`
	FileCount     int    `json:"fileCount"`
	SnapshotBytes int64  `json:"snapshotBytes"`
	SourceBytes   int64  `json:"sourceBytes"`
}

// Source defines model for Source.
type Source struct {
	Absolute  *string `json:"absolute,omitempty"`
	Condition *string `json:"condition,omitempty"`
	Line      *int    `json:"line,omitempty"`
	Path      *string `json:"path,omitempty"`
}

// StoreCredentialRequest defines model for StoreCredentialRequest.
type StoreCredentialRequest struct {
	Secret string `json:"secret"`
}

// StorePasswordRequest defines model for StorePasswordRequest.
type StorePasswordRequest struct {
	Password string `json:"password"`
}

// SyncConflict defines model for SyncConflict.
type SyncConflict struct {
	ChangedHere  bool   `json:"changedHere"`
	ChangedThere bool   `json:"changedThere"`
	Path         string `json:"path"`
}

// SyncDirection defines model for SyncDirection.
type SyncDirection string

// SyncOperation defines model for SyncOperation.
type SyncOperation struct {
	CompletedAt     string            `json:"completedAt"`
	DownloadedBytes *int64            `json:"downloadedBytes,omitempty"`
	Kind            SyncOperationKind `json:"kind"`
	ObjectCount     *int              `json:"objectCount,omitempty"`
	Removed         *int              `json:"removed,omitempty"`
	Summary         SnapshotSummary   `json:"summary"`
	UploadedBytes   *int64            `json:"uploadedBytes,omitempty"`
	Written         *int              `json:"written,omitempty"`
}

// SyncOperationKind defines model for SyncOperationKind.
type SyncOperationKind string

// SyncSettingsRequest defines model for SyncSettingsRequest.
type SyncSettingsRequest struct {
	AccessKeyId     string         `json:"accessKeyId"`
	Bucket          string         `json:"bucket"`
	Direction       *SyncDirection `json:"direction,omitempty"`
	Endpoint        string         `json:"endpoint"`
	Path            *string        `json:"path,omitempty"`
	Region          *string        `json:"region,omitempty"`
	SecretAccessKey string         `json:"secretAccessKey"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus struct {
	Bucket        string         `json:"bucket"`
	Configured    bool           `json:"configured"`
	Direction     SyncDirection  `json:"direction"`
	Endpoint      string         `json:"endpoint"`
	FileCount     *int           `json:"fileCount,omitempty"`
	LastOperation *SyncOperation `json:"lastOperation,omitempty"`
	LastSyncedAt  *string        `json:"lastSyncedAt,omitempty"`
	Locked        bool           `json:"locked"`
	Origin        *string        `json:"origin,omitempty"`
	Path          *string        `json:"path,omitempty"`
	Region        *string        `json:"region,omitempty"`
	Synced        bool           `json:"synced"`
}

// TerminalCommandResponse defines model for TerminalCommandResponse.
type TerminalCommandResponse struct {
	Command string `json:"command"`
	Warning string `json:"warning"`
}

// TerminalExit defines model for TerminalExit.
type TerminalExit struct {
	At     string `json:"at"`
	Code   int    `json:"code"`
	Signal string `json:"signal"`
}

// TerminalSession defines model for TerminalSession.
type TerminalSession struct {
	Alias     *string             `json:"alias,omitempty"`
	Exited    *TerminalExit       `json:"exited,omitempty"`
	Id        string              `json:"id"`
	Kind      TerminalSessionKind `json:"kind"`
	StartedAt string              `json:"startedAt"`
	Title     string              `json:"title"`
}

// TerminalSessionKind defines model for TerminalSession.Kind.
type TerminalSessionKind string

// TerminalSessionList defines model for TerminalSessionList.
type TerminalSessionList struct {
	MaxSessions int               `json:"maxSessions"`
	Sessions    []TerminalSession `json:"sessions"`
}

// TerminalStreamTicket defines model for TerminalStreamTicket.
type TerminalStreamTicket struct {
	StreamTicket string `json:"streamTicket"`
}

// TrashEntrySummary defines model for TrashEntrySummary.
type TrashEntrySummary struct {
	AgeDays    int                `json:"ageDays"`
	Blockers   []string           `json:"blockers"`
	DeletedAt  string             `json:"deletedAt"`
	Files      []TrashFileSummary `json:"files"`
	Id         string             `json:"id"`
	Restorable bool               `json:"restorable"`
	Stale      bool               `json:"stale"`
}

// TrashFileSummary defines model for TrashFileSummary.
type TrashFileSummary struct {
	Fingerprint          string `json:"fingerprint"`
	Kind                 string `json:"kind"`
	OriginalRelativePath string `json:"originalRelativePath"`
	Permission           string `json:"permission"`
	TrashRelativePath    string `json:"trashRelativePath"`
}

// TrashKeyResponse defines model for TrashKeyResponse.
type TrashKeyResponse struct {
	EntryId       string             `json:"entryId"`
	Files         []TrashFileSummary `json:"files"`
	Skipped       []string           `json:"skipped"`
	TransactionId string             `json:"transactionId"`
}

// TrashListResponse defines model for TrashListResponse.
type TrashListResponse struct {
	Entries       []TrashEntrySummary `json:"entries"`
	RetentionDays int                 `json:"retentionDays"`
}

// UnreadableFile defines model for UnreadableFile.
type UnreadableFile struct {
	Reason       string `json:"reason"`
	RelativePath string `json:"relativePath"`
}

// UnresolvedReference defines model for UnresolvedReference.
type UnresolvedReference struct {
	ConfigPath string `json:"configPath"`
	Directive  string `json:"directive"`
	Line       int    `json:"line"`
	Reason     string `json:"reason"`
	Value      string `json:"value"`
}

// UpdateConnectionKeyPassphrase defines model for UpdateConnectionKeyPassphrase.
type UpdateConnectionKeyPassphrase = json.RawMessage

// UpdateConnectionPassword defines model for UpdateConnectionPassword.
type UpdateConnectionPassword = json.RawMessage

// UpdateConnectionRequest defines model for UpdateConnectionRequest.
type UpdateConnectionRequest struct {
	Base          string                        `json:"base"`
	HostName      *ConnectionStringChange       `json:"hostName,omitempty"`
	Identity      HostIdentity                  `json:"identity"`
	IdentityFile  *ConnectionIdentityFileChange `json:"identityFile,omitempty"`
	KeyPassphrase UpdateConnectionKeyPassphrase `json:"keyPassphrase"`
	Password      UpdateConnectionPassword      `json:"password"`
	Port          *ConnectionPortChange         `json:"port,omitempty"`
	User          *ConnectionStringChange       `json:"user,omitempty"`
}

// UpdatePasswordRemove defines model for UpdatePasswordRemove.
type UpdatePasswordRemove struct {
	Kind string `json:"kind"`
}

// UpdatePasswordUnchanged defines model for UpdatePasswordUnchanged.
type UpdatePasswordUnchanged struct {
	Kind string `json:"kind"`
}

// UpdateStatus defines model for UpdateStatus.
type UpdateStatus struct {
	Available bool    `json:"available"`
	Current   string  `json:"current"`
	Latest    *string `json:"latest,omitempty"`
	PageUrl   *string `json:"pageUrl,omitempty"`
}

// ValueSource defines model for ValueSource.
type ValueSource struct {
	Condition string `json:"condition"`
	Keyword   string `json:"keyword"`
	Kind      string `json:"kind"`
	Line      int    `json:"line"`
	Path      string `json:"path"`
	Value     string `json:"value"`
	Winner    bool   `json:"winner"`
}

// GetConfigFileParams defines parameters for GetConfigFile.
type GetConfigFileParams struct {
	Path string `form:"path" json:"path"`
}

// GetConfigHostParams defines parameters for GetConfigHost.
type GetConfigHostParams struct {
	Path  string `form:"path" json:"path"`
	Alias string `form:"alias" json:"alias"`
}

// RevealPrivateKeyParams defines parameters for RevealPrivateKey.
type RevealPrivateKeyParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// ListKnownHostsParams defines parameters for ListKnownHosts.
type ListKnownHostsParams struct {
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// RegisterRemoteKeyParams defines parameters for RegisterRemoteKey.
type RegisterRemoteKeyParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// BootstrapSessionParams defines parameters for BootstrapSession.
type BootstrapSessionParams struct {
	XSSHCBootstrap string `json:"X-SSHC-Bootstrap"`
}

// PurgeTrashEntryParams defines parameters for PurgeTrashEntry.
type PurgeTrashEntryParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// IssueActionTokenJSONRequestBody defines body for IssueActionToken for application/json ContentType.
type IssueActionTokenJSONRequestBody = IssueActionRequest

// DeleteGroupJSONRequestBody defines body for DeleteGroup for application/json ContentType.
type DeleteGroupJSONRequestBody = GroupDeleteRequest

// RenameGroupJSONRequestBody defines body for RenameGroup for application/json ContentType.
type RenameGroupJSONRequestBody = GroupRenameRequest

// PreviewConfigEditJSONRequestBody defines body for PreviewConfigEdit for application/json ContentType.
type PreviewConfigEditJSONRequestBody = EditRequest

// SaveConfigEditJSONRequestBody defines body for SaveConfigEdit for application/json ContentType.
type SaveConfigEditJSONRequestBody = EditRequest

// UpdateConnectionJSONRequestBody defines body for UpdateConnection for application/json ContentType.
type UpdateConnectionJSONRequestBody = UpdateConnectionRequest

// CreateConnectionJSONRequestBody defines body for CreateConnection for application/json ContentType.
type CreateConnectionJSONRequestBody = CreateConnectionRequest

// AssignCredentialJSONRequestBody defines body for AssignCredential for application/json ContentType.
type AssignCredentialJSONRequestBody = AssignCredentialRequest

// StoreCredentialJSONRequestBody defines body for StoreCredential for application/json ContentType.
type StoreCredentialJSONRequestBody = StoreCredentialRequest

// TestAuthenticationJSONRequestBody defines body for TestAuthentication for application/json ContentType.
type TestAuthenticationJSONRequestBody = AuthenticationRequest

// InspectEffectiveConfigurationJSONRequestBody defines body for InspectEffectiveConfiguration for application/json ContentType.
type InspectEffectiveConfigurationJSONRequestBody = AliasRequest

// CheckReachabilityJSONRequestBody defines body for CheckReachability for application/json ContentType.
type CheckReachabilityJSONRequestBody = AliasRequest

// RecoverTransactionJSONRequestBody defines body for RecoverTransaction for application/json ContentType.
type RecoverTransactionJSONRequestBody = RecoverRequest

// RestoreHistoryEntryJSONRequestBody defines body for RestoreHistoryEntry for application/json ContentType.
type RestoreHistoryEntryJSONRequestBody = RestoreRequest

// GenerateKeyJSONRequestBody defines body for GenerateKey for application/json ContentType.
type GenerateKeyJSONRequestBody = GenerateKeyRequest

// BuildHardwareKeyCommandJSONRequestBody defines body for BuildHardwareKeyCommand for application/json ContentType.
type BuildHardwareKeyCommandJSONRequestBody = HardwareCommandRequest

// RegisterKeyWithAgentJSONRequestBody defines body for RegisterKeyWithAgent for application/json ContentType.
type RegisterKeyWithAgentJSONRequestBody = RegisterKeyRequest

// RelocateKeyJSONRequestBody defines body for RelocateKey for application/json ContentType.
type RelocateKeyJSONRequestBody = RelocateKeyRequest

// ChangeKeyPassphraseJSONRequestBody defines body for ChangeKeyPassphrase for application/json ContentType.
type ChangeKeyPassphraseJSONRequestBody = ChangePassphraseRequest

// AddKnownHostJSONRequestBody defines body for AddKnownHost for application/json ContentType.
type AddKnownHostJSONRequestBody = KnownHostsAddRequest

// DeleteKnownHostsJSONRequestBody defines body for DeleteKnownHosts for application/json ContentType.
type DeleteKnownHostsJSONRequestBody = KnownHostsDeleteRequest

// ScanKnownHostsJSONRequestBody defines body for ScanKnownHosts for application/json ContentType.
type ScanKnownHostsJSONRequestBody = KnownHostsScanRequest

// SetLoginItemJSONRequestBody defines body for SetLoginItem for application/json ContentType.
type SetLoginItemJSONRequestBody = LoginItem

// ChangeMasterPasswordJSONRequestBody defines body for ChangeMasterPassword for application/json ContentType.
type ChangeMasterPasswordJSONRequestBody = ChangeMasterPasswordRequest

// InitialisePasswordVaultJSONRequestBody defines body for InitialisePasswordVault for application/json ContentType.
type InitialisePasswordVaultJSONRequestBody = PassphraseRequest

// UnlockPasswordVaultJSONRequestBody defines body for UnlockPasswordVault for application/json ContentType.
type UnlockPasswordVaultJSONRequestBody = PassphraseRequest

// StorePasswordJSONRequestBody defines body for StorePassword for application/json ContentType.
type StorePasswordJSONRequestBody = StorePasswordRequest

// PlanRemoteKeyRegistrationJSONRequestBody defines body for PlanRemoteKeyRegistration for application/json ContentType.
type PlanRemoteKeyRegistrationJSONRequestBody = RemoteKeyPlanRequest

// RegisterRemoteKeyJSONRequestBody defines body for RegisterRemoteKey for application/json ContentType.
type RegisterRemoteKeyJSONRequestBody = RemoteKeyRegisterRequest

// PullSnapshotJSONRequestBody defines body for PullSnapshot for application/json ContentType.
type PullSnapshotJSONRequestBody = PullRequest

// PushSnapshotJSONRequestBody defines body for PushSnapshot for application/json ContentType.
type PushSnapshotJSONRequestBody = PassphraseRequest

// ConfigureSyncJSONRequestBody defines body for ConfigureSync for application/json ContentType.
type ConfigureSyncJSONRequestBody = SyncSettingsRequest

// GetTerminalCommandJSONRequestBody defines body for GetTerminalCommand for application/json ContentType.
type GetTerminalCommandJSONRequestBody = AliasRequest

// OpenTerminalSessionJSONRequestBody defines body for OpenTerminalSession for application/json ContentType.
type OpenTerminalSessionJSONRequestBody = OpenTerminalSessionRequest
