// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"
)

// Defines values for AutoSyncPhase.
const (
	AutoSyncPhaseBlocked AutoSyncPhase = "blocked"
	AutoSyncPhaseFailed  AutoSyncPhase = "failed"
	AutoSyncPhaseIdle    AutoSyncPhase = "idle"
	AutoSyncPhaseRunning AutoSyncPhase = "running"
)

// Valid indicates whether the value is a known member of the AutoSyncPhase enum.
func (e AutoSyncPhase) Valid() bool {
	switch e {
	case AutoSyncPhaseBlocked:
		return true
	case AutoSyncPhaseFailed:
		return true
	case AutoSyncPhaseIdle:
		return true
	case AutoSyncPhaseRunning:
		return true
	default:
		return false
	}
}

// Defines values for OpenTerminalSessionRequestKind.
const (
	OpenTerminalSessionRequestKindShell OpenTerminalSessionRequestKind = "shell"
	OpenTerminalSessionRequestKindSsh   OpenTerminalSessionRequestKind = "ssh"
)

// Valid indicates whether the value is a known member of the OpenTerminalSessionRequestKind enum.
func (e OpenTerminalSessionRequestKind) Valid() bool {
	switch e {
	case OpenTerminalSessionRequestKindShell:
		return true
	case OpenTerminalSessionRequestKindSsh:
		return true
	default:
		return false
	}
}

// Defines values for PullRequestResolve.
const (
	Local  PullRequestResolve = "local"
	Remote PullRequestResolve = "remote"
)

// Valid indicates whether the value is a known member of the PullRequestResolve enum.
func (e PullRequestResolve) Valid() bool {
	switch e {
	case Local:
		return true
	case Remote:
		return true
	default:
		return false
	}
}

// Defines values for SFTPCreateTransferJobRequestDirection.
const (
	SFTPCreateTransferJobRequestDirectionDownload SFTPCreateTransferJobRequestDirection = "download"
	SFTPCreateTransferJobRequestDirectionUpload   SFTPCreateTransferJobRequestDirection = "upload"
)

// Valid indicates whether the value is a known member of the SFTPCreateTransferJobRequestDirection enum.
func (e SFTPCreateTransferJobRequestDirection) Valid() bool {
	switch e {
	case SFTPCreateTransferJobRequestDirectionDownload:
		return true
	case SFTPCreateTransferJobRequestDirectionUpload:
		return true
	default:
		return false
	}
}

// Defines values for SFTPCreateTransferJobRequestKind.
const (
	SFTPCreateTransferJobRequestKindFile   SFTPCreateTransferJobRequestKind = "file"
	SFTPCreateTransferJobRequestKindFolder SFTPCreateTransferJobRequestKind = "folder"
)

// Valid indicates whether the value is a known member of the SFTPCreateTransferJobRequestKind enum.
func (e SFTPCreateTransferJobRequestKind) Valid() bool {
	switch e {
	case SFTPCreateTransferJobRequestKindFile:
		return true
	case SFTPCreateTransferJobRequestKindFolder:
		return true
	default:
		return false
	}
}

// Defines values for SFTPEntryType.
const (
	SFTPEntryTypeDirectory SFTPEntryType = "directory"
	SFTPEntryTypeFile      SFTPEntryType = "file"
	SFTPEntryTypeOther     SFTPEntryType = "other"
	SFTPEntryTypeSymlink   SFTPEntryType = "symlink"
)

// Valid indicates whether the value is a known member of the SFTPEntryType enum.
func (e SFTPEntryType) Valid() bool {
	switch e {
	case SFTPEntryTypeDirectory:
		return true
	case SFTPEntryTypeFile:
		return true
	case SFTPEntryTypeOther:
		return true
	case SFTPEntryTypeSymlink:
		return true
	default:
		return false
	}
}

// Defines values for SFTPMkdirRequestType.
const (
	Directory SFTPMkdirRequestType = "directory"
)

// Valid indicates whether the value is a known member of the SFTPMkdirRequestType enum.
func (e SFTPMkdirRequestType) Valid() bool {
	switch e {
	case Directory:
		return true
	default:
		return false
	}
}

// Defines values for SFTPTransferJobDirection.
const (
	SFTPTransferJobDirectionDownload SFTPTransferJobDirection = "download"
	SFTPTransferJobDirectionUpload   SFTPTransferJobDirection = "upload"
)

// Valid indicates whether the value is a known member of the SFTPTransferJobDirection enum.
func (e SFTPTransferJobDirection) Valid() bool {
	switch e {
	case SFTPTransferJobDirectionDownload:
		return true
	case SFTPTransferJobDirectionUpload:
		return true
	default:
		return false
	}
}

// Defines values for SFTPTransferJobKind.
const (
	File   SFTPTransferJobKind = "file"
	Folder SFTPTransferJobKind = "folder"
)

// Valid indicates whether the value is a known member of the SFTPTransferJobKind enum.
func (e SFTPTransferJobKind) Valid() bool {
	switch e {
	case File:
		return true
	case Folder:
		return true
	default:
		return false
	}
}

// Defines values for SFTPTransferJobStatus.
const (
	SFTPTransferJobStatusCancelled      SFTPTransferJobStatus = "cancelled"
	SFTPTransferJobStatusCompleted      SFTPTransferJobStatus = "completed"
	SFTPTransferJobStatusFailed         SFTPTransferJobStatus = "failed"
	SFTPTransferJobStatusNeedsOverwrite SFTPTransferJobStatus = "needs_overwrite"
	SFTPTransferJobStatusPaused         SFTPTransferJobStatus = "paused"
	SFTPTransferJobStatusQueued         SFTPTransferJobStatus = "queued"
	SFTPTransferJobStatusReattach       SFTPTransferJobStatus = "reattach"
	SFTPTransferJobStatusRunning        SFTPTransferJobStatus = "running"
)

// Valid indicates whether the value is a known member of the SFTPTransferJobStatus enum.
func (e SFTPTransferJobStatus) Valid() bool {
	switch e {
	case SFTPTransferJobStatusCancelled:
		return true
	case SFTPTransferJobStatusCompleted:
		return true
	case SFTPTransferJobStatusFailed:
		return true
	case SFTPTransferJobStatusNeedsOverwrite:
		return true
	case SFTPTransferJobStatusPaused:
		return true
	case SFTPTransferJobStatusQueued:
		return true
	case SFTPTransferJobStatusReattach:
		return true
	case SFTPTransferJobStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for SFTPTransferJobActionRequestAction.
const (
	Cancel         SFTPTransferJobActionRequestAction = "cancel"
	Complete       SFTPTransferJobActionRequestAction = "complete"
	Fail           SFTPTransferJobActionRequestAction = "fail"
	NeedsOverwrite SFTPTransferJobActionRequestAction = "needs_overwrite"
	Pause          SFTPTransferJobActionRequestAction = "pause"
	Progress       SFTPTransferJobActionRequestAction = "progress"
	Resume         SFTPTransferJobActionRequestAction = "resume"
	Retry          SFTPTransferJobActionRequestAction = "retry"
	Start          SFTPTransferJobActionRequestAction = "start"
)

// Valid indicates whether the value is a known member of the SFTPTransferJobActionRequestAction enum.
func (e SFTPTransferJobActionRequestAction) Valid() bool {
	switch e {
	case Cancel:
		return true
	case Complete:
		return true
	case Fail:
		return true
	case NeedsOverwrite:
		return true
	case Pause:
		return true
	case Progress:
		return true
	case Resume:
		return true
	case Retry:
		return true
	case Start:
		return true
	default:
		return false
	}
}

// Defines values for SnippetJobStatus.
const (
	SnippetJobStatusCancelled SnippetJobStatus = "cancelled"
	SnippetJobStatusCompleted SnippetJobStatus = "completed"
	SnippetJobStatusRunning   SnippetJobStatus = "running"
)

// Valid indicates whether the value is a known member of the SnippetJobStatus enum.
func (e SnippetJobStatus) Valid() bool {
	switch e {
	case SnippetJobStatusCancelled:
		return true
	case SnippetJobStatusCompleted:
		return true
	case SnippetJobStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for SnippetTargetResultStatus.
const (
	SnippetTargetResultStatusCancelled SnippetTargetResultStatus = "cancelled"
	SnippetTargetResultStatusFailed    SnippetTargetResultStatus = "failed"
	SnippetTargetResultStatusQueued    SnippetTargetResultStatus = "queued"
	SnippetTargetResultStatusRunning   SnippetTargetResultStatus = "running"
	SnippetTargetResultStatusSucceeded SnippetTargetResultStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the SnippetTargetResultStatus enum.
func (e SnippetTargetResultStatus) Valid() bool {
	switch e {
	case SnippetTargetResultStatusCancelled:
		return true
	case SnippetTargetResultStatusFailed:
		return true
	case SnippetTargetResultStatusQueued:
		return true
	case SnippetTargetResultStatusRunning:
		return true
	case SnippetTargetResultStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for SnippetVariableType.
const (
	Boolean SnippetVariableType = "boolean"
	Integer SnippetVariableType = "integer"
	Secret  SnippetVariableType = "secret"
	String  SnippetVariableType = "string"
)

// Valid indicates whether the value is a known member of the SnippetVariableType enum.
func (e SnippetVariableType) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Integer:
		return true
	case Secret:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for SyncDirection.
const (
	SyncDirectionBoth SyncDirection = "both"
	SyncDirectionPull SyncDirection = "pull"
	SyncDirectionPush SyncDirection = "push"
)

// Valid indicates whether the value is a known member of the SyncDirection enum.
func (e SyncDirection) Valid() bool {
	switch e {
	case SyncDirectionBoth:
		return true
	case SyncDirectionPull:
		return true
	case SyncDirectionPush:
		return true
	default:
		return false
	}
}

// Defines values for SyncOperationKind.
const (
	SyncOperationKindApply SyncOperationKind = "apply"
	SyncOperationKindPush  SyncOperationKind = "push"
)

// Valid indicates whether the value is a known member of the SyncOperationKind enum.
func (e SyncOperationKind) Valid() bool {
	switch e {
	case SyncOperationKindApply:
		return true
	case SyncOperationKindPush:
		return true
	default:
		return false
	}
}

// Defines values for TerminalSessionKind.
const (
	TerminalSessionKindShell TerminalSessionKind = "shell"
	TerminalSessionKindSsh   TerminalSessionKind = "ssh"
)

// Valid indicates whether the value is a known member of the TerminalSessionKind enum.
func (e TerminalSessionKind) Valid() bool {
	switch e {
	case TerminalSessionKindShell:
		return true
	case TerminalSessionKindSsh:
		return true
	default:
		return false
	}
}

// Defines values for TerminalSessionState.
const (
	Connected    TerminalSessionState = "connected"
	Connecting   TerminalSessionState = "connecting"
	Exited       TerminalSessionState = "exited"
	Reconnecting TerminalSessionState = "reconnecting"
)

// Valid indicates whether the value is a known member of the TerminalSessionState enum.
func (e TerminalSessionState) Valid() bool {
	switch e {
	case Connected:
		return true
	case Connecting:
		return true
	case Exited:
		return true
	case Reconnecting:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceReconnectPaneState.
const (
	ReconnectRequired WorkspaceReconnectPaneState = "reconnect_required"
)

// Valid indicates whether the value is a known member of the WorkspaceReconnectPaneState enum.
func (e WorkspaceReconnectPaneState) Valid() bool {
	switch e {
	case ReconnectRequired:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceSplitDirection.
const (
	Horizontal WorkspaceSplitDirection = "horizontal"
	Vertical   WorkspaceSplitDirection = "vertical"
)

// Valid indicates whether the value is a known member of the WorkspaceSplitDirection enum.
func (e WorkspaceSplitDirection) Valid() bool {
	switch e {
	case Horizontal:
		return true
	case Vertical:
		return true
	default:
		return false
	}
}

// AgentIdentitiesResponse defines model for AgentIdentitiesResponse.
type AgentIdentitiesResponse struct {
	AgentAvailable bool            `json:"agentAvailable"`
	Id             string          `json:"id"`
	Identities     []AgentIdentity `json:"identities"`
}

// AgentIdentity defines model for AgentIdentity.
type AgentIdentity struct {
	Algorithm   string `json:"algorithm"`
	Bits        int    `json:"bits"`
	Comment     string `json:"comment"`
	Fingerprint string `json:"fingerprint"`
}

// AliasRequest defines model for AliasRequest.
type AliasRequest struct {
	Alias string `json:"alias"`
}

// AssignCredentialRequest defines model for AssignCredentialRequest.
type AssignCredentialRequest struct {
	Name    string `json:"name"`
	Subject string `json:"subject"`
}

// AuthenticationRequest defines model for AuthenticationRequest.
type AuthenticationRequest struct {
	AcknowledgeExecutable bool   `json:"acknowledgeExecutable"`
	Alias                 string `json:"alias"`
}

// AuthenticationResponse defines model for AuthenticationResponse.
type AuthenticationResponse struct {
	Authenticated bool   `json:"authenticated"`
	Detail        string `json:"detail"`
	ElapsedMs     int    `json:"elapsedMs"`
	Method        string `json:"method"`
	Outcome       string `json:"outcome"`
	Truncated     bool   `json:"truncated"`
}

// AutoSync defines model for AutoSync.
type AutoSync struct {
	At      *string       `json:"at,omitempty"`
	Detail  *string       `json:"detail,omitempty"`
	Enabled bool          `json:"enabled"`
	Phase   AutoSyncPhase `json:"phase"`
}

// AutoSyncPhase defines model for AutoSync.Phase.
type AutoSyncPhase string

// AutoSyncRequest defines model for AutoSyncRequest.
type AutoSyncRequest struct {
	Enabled bool `json:"enabled"`
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// ChangeMasterPasswordRequest defines model for ChangeMasterPasswordRequest.
type ChangeMasterPasswordRequest struct {
	Current string `json:"current"`
	Next    string `json:"next"`
}

// ChangeMasterPasswordResult defines model for ChangeMasterPasswordResult.
type ChangeMasterPasswordResult struct {
	SnapshotProblem  *string             `json:"snapshotProblem,omitempty"`
	SnapshotResealed bool                `json:"snapshotResealed"`
	Vault            PasswordVaultStatus `json:"vault"`
}

// ChangePassphraseRequest defines model for ChangePassphraseRequest.
type ChangePassphraseRequest struct {
	CurrentPassphrase string `json:"currentPassphrase"`
	NewPassphrase     string `json:"newPassphrase"`
	Unencrypted       bool   `json:"unencrypted"`
}

// ChangePassphraseResponse defines model for ChangePassphraseResponse.
type ChangePassphraseResponse struct {
	Encrypted     bool     `json:"encrypted"`
	Id            string   `json:"id"`
	Notes         []string `json:"notes"`
	RelativePath  string   `json:"relativePath"`
	TransactionId string   `json:"transactionId"`
}

// ChangedResponse defines model for ChangedResponse.
type ChangedResponse struct {
	Changed bool `json:"changed"`
}

// ComplexityNote defines model for ComplexityNote.
type ComplexityNote struct {
	Code      string `json:"code"`
	Condition string `json:"condition"`
	Detail    string `json:"detail"`
	Line      int    `json:"line"`
	Path      string `json:"path"`
}

// ConfigCheckResponse defines model for ConfigCheckResponse.
type ConfigCheckResponse struct {
	Diagnostics []ConfigDiagnostic  `json:"diagnostics"`
	Files       []ConfigFileSummary `json:"files"`
	Root        string              `json:"root"`
}

// ConfigDiagnostic defines model for ConfigDiagnostic.
type ConfigDiagnostic struct {
	Code     string `json:"code"`
	Detail   string `json:"detail"`
	Line     int    `json:"line"`
	Path     string `json:"path"`
	Severity string `json:"severity"`
}

// ConfigFileSummary defines model for ConfigFileSummary.
type ConfigFileSummary struct {
	Editable bool   `json:"editable"`
	Includes int    `json:"includes"`
	Loads    int    `json:"loads"`
	Missing  bool   `json:"missing"`
	Path     string `json:"path"`
}

// ConflictReport defines model for ConflictReport.
type ConflictReport struct {
	BaseDigest     *string    `json:"baseDigest,omitempty"`
	DiskDigest     *string    `json:"diskDigest,omitempty"`
	ExternalChange []DiffLine `json:"externalChange"`
	LocalChange    []DiffLine `json:"localChange"`
	Path           string     `json:"path"`
}

// ConnectionIdentityFileChange defines model for ConnectionIdentityFileChange.
type ConnectionIdentityFileChange = json.RawMessage

// ConnectionIdentityFileSet defines model for ConnectionIdentityFileSet.
type ConnectionIdentityFileSet struct {
	Action string `json:"action"`
	KeyId  string `json:"keyId"`
}

// ConnectionInherit defines model for ConnectionInherit.
type ConnectionInherit struct {
	Action string `json:"action"`
}

// ConnectionKeyPassphraseSetDedicated defines model for ConnectionKeyPassphraseSetDedicated.
type ConnectionKeyPassphraseSetDedicated struct {
	KeyId      string `json:"keyId"`
	Kind       string `json:"kind"`
	Passphrase string `json:"passphrase"`
}

// ConnectionKeyPassphraseUnchanged defines model for ConnectionKeyPassphraseUnchanged.
type ConnectionKeyPassphraseUnchanged struct {
	Kind string `json:"kind"`
}

// ConnectionPortChange defines model for ConnectionPortChange.
type ConnectionPortChange = json.RawMessage

// ConnectionPortSet defines model for ConnectionPortSet.
type ConnectionPortSet struct {
	Action string `json:"action"`
	Value  int    `json:"value"`
}

// ConnectionStringChange defines model for ConnectionStringChange.
type ConnectionStringChange = json.RawMessage

// ConnectionStringSet defines model for ConnectionStringSet.
type ConnectionStringSet struct {
	Action string `json:"action"`
	Value  string `json:"value"`
}

// CreateConnectionAuthentication defines model for CreateConnectionAuthentication.
type CreateConnectionAuthentication = json.RawMessage

// CreateConnectionRequest defines model for CreateConnectionRequest.
type CreateConnectionRequest struct {
	Alias          string                         `json:"alias"`
	Authentication CreateConnectionAuthentication `json:"authentication"`
	Group          *string                        `json:"group,omitempty"`
	HostName       string                         `json:"hostName"`
	Port           *int                           `json:"port,omitempty"`
	User           *string                        `json:"user,omitempty"`
}

// CreateDedicatedPasswordAuthentication defines model for CreateDedicatedPasswordAuthentication.
type CreateDedicatedPasswordAuthentication struct {
	Kind     string `json:"kind"`
	Password string `json:"password"`
}

// CreateIdentityFileAuthentication defines model for CreateIdentityFileAuthentication.
type CreateIdentityFileAuthentication struct {
	KeyId string `json:"keyId"`
	Kind  string `json:"kind"`
}

// CreateNewSharedPasswordAuthentication defines model for CreateNewSharedPasswordAuthentication.
type CreateNewSharedPasswordAuthentication struct {
	Credential string `json:"credential"`
	Kind       string `json:"kind"`
	Password   string `json:"password"`
}

// CreateSavedPasswordAuthentication defines model for CreateSavedPasswordAuthentication.
type CreateSavedPasswordAuthentication struct {
	Credential string `json:"credential"`
	Kind       string `json:"kind"`
}

// Credential defines model for Credential.
type Credential struct {
	Hosts []string `json:"hosts"`
	Kind  string   `json:"kind"`
	Name  string   `json:"name"`
	Uses  []string `json:"uses"`
}

// CredentialList defines model for CredentialList.
type CredentialList struct {
	Credentials             []Credential                  `json:"credentials"`
	DedicatedKeyPassphrases []DedicatedKeyPassphraseUsage `json:"dedicatedKeyPassphrases"`
	KeyHostUsageComplete    bool                          `json:"keyHostUsageComplete"`
}

// DedicatedKeyPassphraseUsage defines model for DedicatedKeyPassphraseUsage.
type DedicatedKeyPassphraseUsage struct {
	Hosts []string `json:"hosts"`
	Key   string   `json:"key"`
}

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Absolute *string `json:"absolute,omitempty"`
	Code     string  `json:"code"`
	Detail   *string `json:"detail,omitempty"`
	External *bool   `json:"external,omitempty"`
	Line     *int    `json:"line,omitempty"`
	Path     *string `json:"path,omitempty"`
	Severity string  `json:"severity"`
}

// DiffLine defines model for DiffLine.
type DiffLine struct {
	NewLine *int   `json:"newLine,omitempty"`
	OldLine *int   `json:"oldLine,omitempty"`
	Op      string `json:"op"`
	Text    string `json:"text"`
}

// EditRequest defines model for EditRequest.
type EditRequest struct {
	Alias            *string      `json:"alias,omitempty"`
	Base             *string      `json:"base,omitempty"`
	Comment          *string      `json:"comment,omitempty"`
	DestinationBase  *string      `json:"destinationBase,omitempty"`
	DestinationGroup *string      `json:"destinationGroup,omitempty"`
	DestinationPath  *string      `json:"destinationPath,omitempty"`
	Fields           *[]FieldEdit `json:"fields,omitempty"`
	Kind             string       `json:"kind"`
	Metadata         *Metadata    `json:"metadata,omitempty"`
	NewAlias         *string      `json:"newAlias,omitempty"`
	Path             *string      `json:"path,omitempty"`
	Raw              *string      `json:"raw,omitempty"`
}

// EffectiveResponse defines model for EffectiveResponse.
type EffectiveResponse struct {
	Alias                string                `json:"alias"`
	Complexities         []ComplexityNote      `json:"complexities"`
	ExecutableDirectives []ExecutableDirective `json:"executableDirectives"`
	Route                []JumpStage           `json:"route"`
	Sources              []ValueSource         `json:"sources"`
	TokenWarning         string                `json:"tokenWarning"`
}

// EmbeddedTerminal defines model for EmbeddedTerminal.
type EmbeddedTerminal struct {
	Appearance      *TerminalAppearance `json:"appearance,omitempty"`
	CopyOnSelect    *bool               `json:"copyOnSelect,omitempty"`
	FontSize        *int                `json:"fontSize,omitempty"`
	MaxSessions     *int                `json:"maxSessions,omitempty"`
	Reconnect       *int                `json:"reconnect,omitempty"`
	RightClickPaste *bool               `json:"rightClickPaste,omitempty"`
	ScrollbackBytes *int                `json:"scrollbackBytes,omitempty"`
	StartDirectory  *string             `json:"startDirectory,omitempty"`
	Verbosity       *int                `json:"verbosity,omitempty"`
}

// EngineSettings defines model for EngineSettings.
type EngineSettings struct {
	Port *int `json:"port,omitempty"`
}

// ExecutableDirective defines model for ExecutableDirective.
type ExecutableDirective struct {
	Command     string `json:"command"`
	Condition   string `json:"condition"`
	Keyword     string `json:"keyword"`
	Line        int    `json:"line"`
	OnConnect   bool   `json:"onConnect"`
	OnEvaluate  bool   `json:"onEvaluate"`
	Overridable bool   `json:"overridable"`
	Path        string `json:"path"`
}

// FieldEdit defines model for FieldEdit.
type FieldEdit struct {
	Action  string    `json:"action"`
	Keyword *string   `json:"keyword,omitempty"`
	Line    *int      `json:"line,omitempty"`
	Values  *[]string `json:"values,omitempty"`
}

// GenerateKeyRequest defines model for GenerateKeyRequest.
type GenerateKeyRequest struct {
	Algorithm   string  `json:"algorithm"`
	Bits        *int    `json:"bits,omitempty"`
	Comment     string  `json:"comment"`
	FileName    string  `json:"fileName"`
	Group       *string `json:"group,omitempty"`
	Passphrase  string  `json:"passphrase"`
	Unencrypted bool    `json:"unencrypted"`
}

// GenerateKeyResponse defines model for GenerateKeyResponse.
type GenerateKeyResponse struct {
	Bits               int    `json:"bits"`
	Encrypted          bool   `json:"encrypted"`
	Fingerprint        string `json:"fingerprint"`
	Id                 string `json:"id"`
	KeyType            string `json:"keyType"`
	PublicRelativePath string `json:"publicRelativePath"`
	RelativePath       string `json:"relativePath"`
	TransactionId      string `json:"transactionId"`
}

// GroupDeleteRequest defines model for GroupDeleteRequest.
type GroupDeleteRequest struct {
	Destination *string `json:"destination,omitempty"`
	Name        string  `json:"name"`
}

// GroupMetadata defines model for GroupMetadata.
type GroupMetadata struct {
	Colour   *string    `json:"colour,omitempty"`
	Hidden   *bool      `json:"hidden,omitempty"`
	Name     string     `json:"name"`
	Note     *string    `json:"note,omitempty"`
	Order    *int       `json:"order,omitempty"`
	Settings *[]Setting `json:"settings,omitempty"`
}

// GroupRenameRequest defines model for GroupRenameRequest.
type GroupRenameRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// HardwareCommandRequest defines model for HardwareCommandRequest.
type HardwareCommandRequest struct {
	Algorithm string  `json:"algorithm"`
	Comment   string  `json:"comment"`
	FileName  string  `json:"fileName"`
	Group     *string `json:"group,omitempty"`
}

// HardwareCommandResponse defines model for HardwareCommandResponse.
type HardwareCommandResponse struct {
	Algorithm string   `json:"algorithm"`
	Command   []string `json:"command"`
	Note      string   `json:"note"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// HistoryEntry defines model for HistoryEntry.
type HistoryEntry struct {
	FinishedAt *string   `json:"finishedAt,omitempty"`
	Id         string    `json:"id"`
	Operation  string    `json:"operation"`
	Paths      []string  `json:"paths"`
	Restorable *[]string `json:"restorable,omitempty"`
	StartedAt  string    `json:"startedAt"`
	Status     string    `json:"status"`
}

// HistoryList defines model for HistoryList.
type HistoryList struct {
	Entries []HistoryEntry `json:"entries"`
}

// HostIdentity defines model for HostIdentity.
type HostIdentity struct {
	Alias string `json:"alias"`
	Path  string `json:"path"`
}

// HostMetadata defines model for HostMetadata.
type HostMetadata struct {
	Appearance *TerminalAppearance `json:"appearance,omitempty"`
	Colour     *string             `json:"colour,omitempty"`
	Favourite  *bool               `json:"favourite,omitempty"`
	Identity   HostIdentity        `json:"identity"`
	Note       *string             `json:"note,omitempty"`
	Order      *int                `json:"order,omitempty"`
	Orphan     *bool               `json:"orphan,omitempty"`
	Tags       *[]string           `json:"tags,omitempty"`
}

// IssueActionRequest defines model for IssueActionRequest.
type IssueActionRequest struct {
	Kind   string `json:"kind"`
	Target string `json:"target"`
}

// IssueActionResponse defines model for IssueActionResponse.
type IssueActionResponse struct {
	ExpiresAt string `json:"expiresAt"`
	Token     string `json:"token"`
}

// JumpStage defines model for JumpStage.
type JumpStage struct {
	Complex  bool   `json:"complex"`
	Depth    int    `json:"depth"`
	Hop      string `json:"hop"`
	Hostname string `json:"hostname"`
	Order    int    `json:"order"`
	Parent   string `json:"parent"`
	Port     string `json:"port"`
	User     string `json:"user"`
}

// KeyAlgorithmsResponse defines model for KeyAlgorithmsResponse.
type KeyAlgorithmsResponse struct {
	Source   string       `json:"source"`
	Variants []KeyVariant `json:"variants"`
}

// KeyCertificate defines model for KeyCertificate.
type KeyCertificate struct {
	KeyId                string   `json:"keyId"`
	NeverExpires         bool     `json:"neverExpires"`
	Principals           []string `json:"principals"`
	SignedKeyFingerprint string   `json:"signedKeyFingerprint"`
	SignedKeyType        string   `json:"signedKeyType"`
	ValidBefore          int      `json:"validBefore"`
}

// KeyInventoryResponse defines model for KeyInventoryResponse.
type KeyInventoryResponse struct {
	AgentAvailable       bool                  `json:"agentAvailable"`
	AgentDelegations     []KeyReference        `json:"agentDelegations"`
	AgentIdentities      []AgentIdentity       `json:"agentIdentities"`
	Items                []KeyItem             `json:"items"`
	Unreadable           []UnreadableFile      `json:"unreadable"`
	UnresolvedReferences []UnresolvedReference `json:"unresolvedReferences"`
}

// KeyItem defines model for KeyItem.
type KeyItem struct {
	Algorithm      string          `json:"algorithm"`
	Bits           int             `json:"bits"`
	Certificate    *KeyCertificate `json:"certificate,omitempty"`
	Comment        string          `json:"comment"`
	Container      string          `json:"container"`
	Encrypted      bool            `json:"encrypted"`
	Fingerprint    string          `json:"fingerprint"`
	Id             string          `json:"id"`
	KeyType        string          `json:"keyType"`
	Kind           string          `json:"kind"`
	Notes          []string        `json:"notes"`
	Permission     string          `json:"permission"`
	PermissionRisk bool            `json:"permissionRisk"`
	References     []KeyReference  `json:"references"`
	RelativePath   string          `json:"relativePath"`
	SizeBytes      int             `json:"sizeBytes"`
}

// KeyReference defines model for KeyReference.
type KeyReference struct {
	Condition    string   `json:"condition"`
	ConfigPath   string   `json:"configPath"`
	Directive    string   `json:"directive"`
	HostPatterns []string `json:"hostPatterns"`
	Line         int      `json:"line"`
	Value        string   `json:"value"`
}

// KeyVariant defines model for KeyVariant.
type KeyVariant struct {
	Algorithm string `json:"algorithm"`
	Bits      int    `json:"bits"`
	InProcess bool   `json:"inProcess"`
	Label     string `json:"label"`
	Reason    string `json:"reason"`
}

// KnownHostCandidate defines model for KnownHostCandidate.
type KnownHostCandidate struct {
	Fingerprint string `json:"fingerprint"`
	Host        string `json:"host"`
	Key         string `json:"key"`
	KeyType     string `json:"keyType"`
	Port        int    `json:"port"`
	Verified    bool   `json:"verified"`
}

// KnownHostEntry defines model for KnownHostEntry.
type KnownHostEntry struct {
	Comment     string   `json:"comment"`
	Digest      string   `json:"digest"`
	Fingerprint string   `json:"fingerprint"`
	Hashed      bool     `json:"hashed"`
	Hosts       []string `json:"hosts"`
	KeyType     string   `json:"keyType"`
	Line        int      `json:"line"`
	Marker      string   `json:"marker"`
}

// KnownHostTarget defines model for KnownHostTarget.
type KnownHostTarget struct {
	Digest string `json:"digest"`
	Line   int    `json:"line"`
}

// KnownHostsAddRequest defines model for KnownHostsAddRequest.
type KnownHostsAddRequest struct {
	Acknowledged        bool   `json:"acknowledged"`
	ExpectedFingerprint string `json:"expectedFingerprint"`
	Host                string `json:"host"`
	Key                 string `json:"key"`
	KeyType             string `json:"keyType"`
	Port                int    `json:"port"`
}

// KnownHostsChangeResponse defines model for KnownHostsChangeResponse.
type KnownHostsChangeResponse struct {
	Changed       bool   `json:"changed"`
	TransactionId string `json:"transactionId"`
}

// KnownHostsDeleteRequest defines model for KnownHostsDeleteRequest.
type KnownHostsDeleteRequest struct {
	Entries []KnownHostTarget `json:"entries"`
}

// KnownHostsResponse defines model for KnownHostsResponse.
type KnownHostsResponse struct {
	Entries []KnownHostEntry `json:"entries"`
	Path    string           `json:"path"`
}

// KnownHostsScanRequest defines model for KnownHostsScanRequest.
type KnownHostsScanRequest struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

// KnownHostsScanResponse defines model for KnownHostsScanResponse.
type KnownHostsScanResponse struct {
	Candidates []KnownHostCandidate `json:"candidates"`
	Notice     string               `json:"notice"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	EmbeddedTerminal *EmbeddedTerminal `json:"embeddedTerminal,omitempty"`
	Engine           *EngineSettings   `json:"engine,omitempty"`
	Groups           *[]GroupMetadata  `json:"groups,omitempty"`
	GroupsFile       *string           `json:"groupsFile,omitempty"`
	Hosts            *[]HostMetadata   `json:"hosts,omitempty"`
	SchemaVersion    int               `json:"schemaVersion"`
}

// Notice defines model for Notice.
type Notice struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Line   *int    `json:"line,omitempty"`
	Path   *string `json:"path,omitempty"`
}

// OpenTerminalSessionRequest defines model for OpenTerminalSessionRequest.
type OpenTerminalSessionRequest struct {
	Alias *string                        `json:"alias,omitempty"`
	Cols  *int                           `json:"cols,omitempty"`
	Kind  OpenTerminalSessionRequestKind `json:"kind"`
	Rows  *int                           `json:"rows,omitempty"`
}

// OpenTerminalSessionRequestKind defines model for OpenTerminalSessionRequest.Kind.
type OpenTerminalSessionRequestKind string

// OpenTerminalSessionResponse defines model for OpenTerminalSessionResponse.
type OpenTerminalSessionResponse struct {
	Session      TerminalSession `json:"session"`
	StreamTicket string          `json:"streamTicket"`
}

// PassphraseRequest defines model for PassphraseRequest.
type PassphraseRequest struct {
	Passphrase string `json:"passphrase"`
}

// PasswordEligibility defines model for PasswordEligibility.
type PasswordEligibility struct {
	Alias    string   `json:"alias"`
	Blockers []Notice `json:"blockers"`
	HostName *string  `json:"hostName,omitempty"`
	Port     *string  `json:"port,omitempty"`
	Storable bool     `json:"storable"`
	Warnings []Notice `json:"warnings"`
}

// PasswordVaultStatus defines model for PasswordVaultStatus.
type PasswordVaultStatus struct {
	Aliases                 []string `json:"aliases"`
	DedicatedKeyPassphrases []string `json:"dedicatedKeyPassphrases"`
	Exists                  bool     `json:"exists"`
	MinPassphraseLength     *int     `json:"minPassphraseLength,omitempty"`
	Unlocked                bool     `json:"unlocked"`
}

// Problem defines model for Problem.
type Problem struct {
	Blockers    *[]string       `json:"blockers,omitempty"`
	Code        string          `json:"code"`
	Column      *int            `json:"column,omitempty"`
	Conflict    *ConflictReport `json:"conflict,omitempty"`
	Detail      *string         `json:"detail,omitempty"`
	Diagnostics *[]Diagnostic   `json:"diagnostics,omitempty"`
	Line        *int            `json:"line,omitempty"`
	Message     string          `json:"message"`
	Path        *string         `json:"path,omitempty"`
}

// PublicKeyResponse defines model for PublicKeyResponse.
type PublicKeyResponse struct {
	Comment      string `json:"comment"`
	Fingerprint  string `json:"fingerprint"`
	Id           string `json:"id"`
	PublicKey    string `json:"publicKey"`
	RelativePath string `json:"relativePath"`
}

// PullRequest defines model for PullRequest.
type PullRequest struct {
	Apply   *bool               `json:"apply,omitempty"`
	Resolve *PullRequestResolve `json:"resolve,omitempty"`
}

// PullRequestResolve defines model for PullRequest.Resolve.
type PullRequestResolve string

// PullResponse defines model for PullResponse.
type PullResponse struct {
	Applied         bool            `json:"applied"`
	CompletedAt     string          `json:"completedAt"`
	Conflicts       []SyncConflict  `json:"conflicts"`
	DownloadedBytes int64           `json:"downloadedBytes"`
	Origin          *string         `json:"origin,omitempty"`
	Removed         []string        `json:"removed"`
	Summary         SnapshotSummary `json:"summary"`
	Written         []string        `json:"written"`
}

// PurgeTrashResponse defines model for PurgeTrashResponse.
type PurgeTrashResponse struct {
	EntryId       string   `json:"entryId"`
	Removed       []string `json:"removed"`
	TransactionId string   `json:"transactionId"`
}

// PushResponse defines model for PushResponse.
type PushResponse struct {
	Result PushResult `json:"result"`
	Status SyncStatus `json:"status"`
}

// PushResult defines model for PushResult.
type PushResult struct {
	CompletedAt   string          `json:"completedAt"`
	ObjectCount   int             `json:"objectCount"`
	Summary       SnapshotSummary `json:"summary"`
	UploadedBytes int64           `json:"uploadedBytes"`
}

// ReachabilityResponse defines model for ReachabilityResponse.
type ReachabilityResponse struct {
	Address   string `json:"address"`
	Detail    string `json:"detail"`
	ElapsedMs int    `json:"elapsedMs"`
	Notice    string `json:"notice"`
	Outcome   string `json:"outcome"`
}

// RecentConnection defines model for RecentConnection.
type RecentConnection struct {
	Alias           string    `json:"alias"`
	HostName        string    `json:"hostName"`
	LastConnectedAt time.Time `json:"lastConnectedAt"`
	Port            string    `json:"port"`
	User            string    `json:"user"`
}

// RecentConnectionList defines model for RecentConnectionList.
type RecentConnectionList struct {
	Connections []RecentConnection `json:"connections"`
}

// RecoverRequest defines model for RecoverRequest.
type RecoverRequest struct {
	Action        string `json:"action"`
	TransactionId string `json:"transactionId"`
}

// RecoverResponse defines model for RecoverResponse.
type RecoverResponse struct {
	Status string `json:"status"`
}

// RegisterKeyRequest defines model for RegisterKeyRequest.
type RegisterKeyRequest struct {
	LifetimeSeconds int    `json:"lifetimeSeconds"`
	Passphrase      string `json:"passphrase"`
}

// RegisterKeyResponse defines model for RegisterKeyResponse.
type RegisterKeyResponse struct {
	Fingerprint     string          `json:"fingerprint"`
	Id              string          `json:"id"`
	Identities      []AgentIdentity `json:"identities"`
	LifetimeSeconds int             `json:"lifetimeSeconds"`
	RelativePath    string          `json:"relativePath"`
}

// RelocateKeyRequest defines model for RelocateKeyRequest.
type RelocateKeyRequest struct {
	Group   *string `json:"group,omitempty"`
	NewName *string `json:"newName,omitempty"`
}

// RelocateKeyResponse defines model for RelocateKeyResponse.
type RelocateKeyResponse struct {
	Blockers      []string                `json:"blockers"`
	Files         []RelocatedKeyFile      `json:"files"`
	Group         string                  `json:"group"`
	Id            string                  `json:"id"`
	Notes         []string                `json:"notes"`
	References    []RewrittenKeyReference `json:"references"`
	RelativePath  string                  `json:"relativePath"`
	Skipped       []string                `json:"skipped"`
	TransactionId string                  `json:"transactionId"`
}

// RelocatedKeyFile defines model for RelocatedKeyFile.
type RelocatedKeyFile struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// RemoteKeyPlan defines model for RemoteKeyPlan.
type RemoteKeyPlan struct {
	ActionExpiresAt      string                `json:"actionExpiresAt"`
	ActionToken          string                `json:"actionToken"`
	Alias                string                `json:"alias"`
	ExecutableDirectives []ExecutableDirective `json:"executableDirectives"`
	Fingerprint          string                `json:"fingerprint"`
	Hostname             string                `json:"hostname"`
	KeyLine              string                `json:"keyLine"`
	KeyPath              string                `json:"keyPath"`
	Manual               []string              `json:"manual"`
	Port                 string                `json:"port"`
	RemotePath           string                `json:"remotePath"`
	Routine              string                `json:"routine"`
	Supported            bool                  `json:"supported"`
	User                 string                `json:"user"`
	ValuesFrom           string                `json:"valuesFrom"`
}

// RemoteKeyPlanRequest defines model for RemoteKeyPlanRequest.
type RemoteKeyPlanRequest struct {
	Alias     string `json:"alias"`
	KeyPath   string `json:"keyPath"`
	PublicKey string `json:"publicKey"`
}

// RemoteKeyRegisterRequest defines model for RemoteKeyRegisterRequest.
type RemoteKeyRegisterRequest struct {
	AcknowledgeExecutable bool   `json:"acknowledgeExecutable"`
	Alias                 string `json:"alias"`
	KeyPath               string `json:"keyPath"`
	PublicKey             string `json:"publicKey"`
}

// RemoteKeyRegisterResponse defines model for RemoteKeyRegisterResponse.
type RemoteKeyRegisterResponse struct {
	ExitCode  int    `json:"exitCode"`
	Outcome   string `json:"outcome"`
	Stderr    string `json:"stderr"`
	Truncated bool   `json:"truncated"`
}

// RenameTerminalSessionRequest defines model for RenameTerminalSessionRequest.
type RenameTerminalSessionRequest struct {
	Title string `json:"title"`
}

// RestoreRequest defines model for RestoreRequest.
type RestoreRequest struct {
	Path          string `json:"path"`
	TransactionId string `json:"transactionId"`
}

// RestoreTrashResponse defines model for RestoreTrashResponse.
type RestoreTrashResponse struct {
	Blockers      []string `json:"blockers"`
	EntryId       string   `json:"entryId"`
	Restored      []string `json:"restored"`
	TransactionId string   `json:"transactionId"`
}

// RevealPrivateKeyResponse defines model for RevealPrivateKeyResponse.
type RevealPrivateKeyResponse struct {
	Encrypted     bool   `json:"encrypted"`
	Fingerprint   string `json:"fingerprint"`
	Id            string `json:"id"`
	PrivateKey    string `json:"privateKey"`
	RelativePath  string `json:"relativePath"`
	TransactionId string `json:"transactionId"`
}

// RewrittenKeyReference defines model for RewrittenKeyReference.
type RewrittenKeyReference struct {
	ConfigPath string `json:"configPath"`
	Directive  string `json:"directive"`
	From       string `json:"from"`
	Line       int    `json:"line"`
	To         string `json:"to"`
}

// SFTPChmodRequest defines model for SFTPChmodRequest.
type SFTPChmodRequest struct {
	ExpectedRevision string `json:"expectedRevision"`
	Mode             string `json:"mode"`
	Path             string `json:"path"`
}

// SFTPCompleteUploadRequest defines model for SFTPCompleteUploadRequest.
type SFTPCompleteUploadRequest struct {
	ExpectedRevision string `json:"expectedRevision"`
	Path             string `json:"path"`
	Size             int64  `json:"size"`
}

// SFTPCreateTransferJobRequest defines model for SFTPCreateTransferJobRequest.
type SFTPCreateTransferJobRequest struct {
	Alias      string                                `json:"alias"`
	BatchId    string                                `json:"batchId"`
	Direction  SFTPCreateTransferJobRequestDirection `json:"direction"`
	Id         string                                `json:"id"`
	Kind       SFTPCreateTransferJobRequestKind      `json:"kind"`
	Name       string                                `json:"name"`
	RemotePath string                                `json:"remotePath"`
	TotalBytes int64                                 `json:"totalBytes"`
}

// SFTPCreateTransferJobRequestDirection defines model for SFTPCreateTransferJobRequest.Direction.
type SFTPCreateTransferJobRequestDirection string

// SFTPCreateTransferJobRequestKind defines model for SFTPCreateTransferJobRequest.Kind.
type SFTPCreateTransferJobRequestKind string

// SFTPEntry defines model for SFTPEntry.
type SFTPEntry struct {
	Mode       string        `json:"mode"`
	ModifiedAt time.Time     `json:"modifiedAt"`
	Name       string        `json:"name"`
	Path       string        `json:"path"`
	Revision   string        `json:"revision"`
	Size       int64         `json:"size"`
	Type       SFTPEntryType `json:"type"`
}

// SFTPEntryType defines model for SFTPEntry.Type.
type SFTPEntryType string

// SFTPListing defines model for SFTPListing.
type SFTPListing struct {
	Entries []SFTPEntry `json:"entries"`
	Path    string      `json:"path"`
}

// SFTPMkdirRequest defines model for SFTPMkdirRequest.
type SFTPMkdirRequest struct {
	Path string               `json:"path"`
	Type SFTPMkdirRequestType `json:"type"`
}

// SFTPMkdirRequestType defines model for SFTPMkdirRequest.Type.
type SFTPMkdirRequestType string

// SFTPRenameRequest defines model for SFTPRenameRequest.
type SFTPRenameRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// SFTPResumableUpload defines model for SFTPResumableUpload.
type SFTPResumableUpload struct {
	ExpectedRevision *string `json:"expectedRevision,omitempty"`
	Id               string  `json:"id"`
	Offset           int64   `json:"offset"`
	Path             string  `json:"path"`
	Size             int64   `json:"size"`
}

// SFTPSaveTextRequest defines model for SFTPSaveTextRequest.
type SFTPSaveTextRequest struct {
	Contents         string `json:"contents"`
	ExpectedRevision string `json:"expectedRevision"`
}

// SFTPStartUploadRequest defines model for SFTPStartUploadRequest.
type SFTPStartUploadRequest struct {
	ExpectedRevision *string `json:"expectedRevision,omitempty"`
	Overwrite        bool    `json:"overwrite"`
	Path             string  `json:"path"`
	Size             int64   `json:"size"`
}

// SFTPTextFile defines model for SFTPTextFile.
type SFTPTextFile struct {
	Contents string    `json:"contents"`
	Entry    SFTPEntry `json:"entry"`
	Revision string    `json:"revision"`
}

// SFTPTransfer defines model for SFTPTransfer.
type SFTPTransfer struct {
	Bytes    int64  `json:"bytes"`
	Path     string `json:"path"`
	Revision string `json:"revision"`
}

// SFTPTransferJob defines model for SFTPTransferJob.
type SFTPTransferJob struct {
	Alias            string                   `json:"alias"`
	Attempt          int                      `json:"attempt"`
	BatchId          string                   `json:"batchId"`
	BytesPerSecond   float64                  `json:"bytesPerSecond"`
	CreatedAt        time.Time                `json:"createdAt"`
	Direction        SFTPTransferJobDirection `json:"direction"`
	Id               string                   `json:"id"`
	Kind             SFTPTransferJobKind      `json:"kind"`
	Name             string                   `json:"name"`
	Problem          string                   `json:"problem"`
	RemainingSeconds int64                    `json:"remainingSeconds"`
	RemotePath       string                   `json:"remotePath"`
	Status           SFTPTransferJobStatus    `json:"status"`
	TotalBytes       int64                    `json:"totalBytes"`
	TransferredBytes int64                    `json:"transferredBytes"`
	UpdatedAt        time.Time                `json:"updatedAt"`
}

// SFTPTransferJobDirection defines model for SFTPTransferJob.Direction.
type SFTPTransferJobDirection string

// SFTPTransferJobKind defines model for SFTPTransferJob.Kind.
type SFTPTransferJobKind string

// SFTPTransferJobStatus defines model for SFTPTransferJob.Status.
type SFTPTransferJobStatus string

// SFTPTransferJobActionRequest defines model for SFTPTransferJobActionRequest.
type SFTPTransferJobActionRequest struct {
	Action           SFTPTransferJobActionRequestAction `json:"action"`
	Problem          *string                            `json:"problem,omitempty"`
	ResetProgress    *bool                              `json:"resetProgress,omitempty"`
	TransferredBytes *int64                             `json:"transferredBytes,omitempty"`
}

// SFTPTransferJobActionRequestAction defines model for SFTPTransferJobActionRequest.Action.
type SFTPTransferJobActionRequestAction string

// SFTPTransferJobList defines model for SFTPTransferJobList.
type SFTPTransferJobList struct {
	Jobs          []SFTPTransferJob `json:"jobs"`
	MaxConcurrent int               `json:"maxConcurrent"`
}

// Setting defines model for Setting.
type Setting struct {
	Keyword string   `json:"keyword"`
	Values  []string `json:"values"`
}

// SnapshotSummary defines model for SnapshotSummary.
type SnapshotSummary struct {
	CreatedAt     string `json:"createdAt"`
	FileCount     int    `json:"fileCount"`
	SnapshotBytes int64  `json:"snapshotBytes"`
	SourceBytes   int64  `json:"sourceBytes"`
}

// Snippet defines model for Snippet.
type Snippet struct {
	Command     string            `json:"command"`
	CreatedAt   time.Time         `json:"createdAt"`
	Description string            `json:"description"`
	Id          string            `json:"id"`
	Name        string            `json:"name"`
	UpdatedAt   time.Time         `json:"updatedAt"`
	Variables   []SnippetVariable `json:"variables"`
}

// SnippetDraft defines model for SnippetDraft.
type SnippetDraft struct {
	Command     string            `json:"command"`
	Description string            `json:"description"`
	Name        string            `json:"name"`
	Variables   []SnippetVariable `json:"variables"`
}

// SnippetExecuteRequest defines model for SnippetExecuteRequest.
type SnippetExecuteRequest struct {
	Aliases     *[]string                 `json:"aliases,omitempty"`
	Command     *string                   `json:"command,omitempty"`
	Concurrency int                       `json:"concurrency"`
	Evidence    string                    `json:"evidence"`
	Inputs      map[string]string         `json:"inputs"`
	SnippetId   *string                   `json:"snippetId,omitempty"`
	Targets     *[]SnippetExecutionTarget `json:"targets,omitempty"`
}

// SnippetExecutionTarget defines model for SnippetExecutionTarget.
type SnippetExecutionTarget struct {
	Alias    string `json:"alias"`
	TargetId string `json:"targetId"`
}

// SnippetJob defines model for SnippetJob.
type SnippetJob struct {
	FinishedAt *time.Time            `json:"finishedAt,omitempty"`
	Id         string                `json:"id"`
	Results    []SnippetTargetResult `json:"results"`
	StartedAt  time.Time             `json:"startedAt"`
	Status     SnippetJobStatus      `json:"status"`
}

// SnippetJobStatus defines model for SnippetJob.Status.
type SnippetJobStatus string

// SnippetLibrary defines model for SnippetLibrary.
type SnippetLibrary struct {
	Snippets []Snippet        `json:"snippets"`
	Startup  []StartupSnippet `json:"startup"`
}

// SnippetPreview defines model for SnippetPreview.
type SnippetPreview struct {
	ActionExpiresAt time.Time              `json:"actionExpiresAt"`
	ActionToken     string                 `json:"actionToken"`
	Evidence        string                 `json:"evidence"`
	SnippetId       string                 `json:"snippetId"`
	Targets         []SnippetPreviewTarget `json:"targets"`
}

// SnippetPreviewRequest Exactly one of snippetId or command and exactly one of aliases or targets must be supplied. targets permits repeated aliases when targetId values are distinct.
type SnippetPreviewRequest struct {
	Aliases   *[]string                 `json:"aliases,omitempty"`
	Command   *string                   `json:"command,omitempty"`
	Inputs    map[string]string         `json:"inputs"`
	SnippetId *string                   `json:"snippetId,omitempty"`
	Targets   *[]SnippetExecutionTarget `json:"targets,omitempty"`
}

// SnippetPreviewTarget defines model for SnippetPreviewTarget.
type SnippetPreviewTarget struct {
	Command string `json:"command"`
	Target  struct {
		Alias    string `json:"alias"`
		HostName string `json:"hostName"`
		Port     string `json:"port"`
		User     string `json:"user"`
	} `json:"target"`
	TargetId string `json:"targetId"`
}

// SnippetTargetResult defines model for SnippetTargetResult.
type SnippetTargetResult struct {
	Alias     string                    `json:"alias"`
	ExitCode  *int                      `json:"exitCode,omitempty"`
	Problem   *string                   `json:"problem,omitempty"`
	Status    SnippetTargetResultStatus `json:"status"`
	Stderr    *string                   `json:"stderr,omitempty"`
	Stdout    *string                   `json:"stdout,omitempty"`
	TargetId  string                    `json:"targetId"`
	Truncated *bool                     `json:"truncated,omitempty"`
}

// SnippetTargetResultStatus defines model for SnippetTargetResult.Status.
type SnippetTargetResultStatus string

// SnippetVariable defines model for SnippetVariable.
type SnippetVariable struct {
	Default     *string             `json:"default,omitempty"`
	Description *string             `json:"description,omitempty"`
	Name        string              `json:"name"`
	Required    *bool               `json:"required,omitempty"`
	Type        SnippetVariableType `json:"type"`
}

// SnippetVariableType defines model for SnippetVariable.Type.
type SnippetVariableType string

// StartupSnippet defines model for StartupSnippet.
type StartupSnippet struct {
	Alias     string             `json:"alias"`
	Inputs    *map[string]string `json:"inputs,omitempty"`
	SnippetId string             `json:"snippetId"`
}

// StartupSnippetRequest defines model for StartupSnippetRequest.
type StartupSnippetRequest struct {
	Inputs    map[string]string `json:"inputs"`
	SnippetId string            `json:"snippetId"`
}

// StoreCredentialRequest defines model for StoreCredentialRequest.
type StoreCredentialRequest struct {
	Secret string `json:"secret"`
}

// StorePasswordRequest defines model for StorePasswordRequest.
type StorePasswordRequest struct {
	Password string `json:"password"`
}

// SyncConflict defines model for SyncConflict.
type SyncConflict struct {
	ChangedHere  bool   `json:"changedHere"`
	ChangedThere bool   `json:"changedThere"`
	Path         string `json:"path"`
}

// SyncDirection defines model for SyncDirection.
type SyncDirection string

// SyncKeyRequest defines model for SyncKeyRequest.
type SyncKeyRequest struct {
	Key *string `json:"key,omitempty"`
}

// SyncKeyResponse defines model for SyncKeyResponse.
type SyncKeyResponse struct {
	Key string `json:"key"`
}

// SyncOperation defines model for SyncOperation.
type SyncOperation struct {
	CompletedAt     string            `json:"completedAt"`
	DownloadedBytes *int64            `json:"downloadedBytes,omitempty"`
	Kind            SyncOperationKind `json:"kind"`
	ObjectCount     *int              `json:"objectCount,omitempty"`
	Removed         *int              `json:"removed,omitempty"`
	Summary         SnapshotSummary   `json:"summary"`
	UploadedBytes   *int64            `json:"uploadedBytes,omitempty"`
	Written         *int              `json:"written,omitempty"`
}

// SyncOperationKind defines model for SyncOperationKind.
type SyncOperationKind string

// SyncSettingsRequest defines model for SyncSettingsRequest.
type SyncSettingsRequest struct {
	AccessKeyId     string         `json:"accessKeyId"`
	Bucket          string         `json:"bucket"`
	Direction       *SyncDirection `json:"direction,omitempty"`
	Endpoint        string         `json:"endpoint"`
	Path            *string        `json:"path,omitempty"`
	Region          *string        `json:"region,omitempty"`
	SecretAccessKey string         `json:"secretAccessKey"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus struct {
	Auto          AutoSync       `json:"auto"`
	Bucket        string         `json:"bucket"`
	Configured    bool           `json:"configured"`
	Direction     SyncDirection  `json:"direction"`
	Endpoint      string         `json:"endpoint"`
	FileCount     *int           `json:"fileCount,omitempty"`
	KeyConfigured bool           `json:"keyConfigured"`
	LastOperation *SyncOperation `json:"lastOperation,omitempty"`
	LastSyncedAt  *string        `json:"lastSyncedAt,omitempty"`
	Locked        bool           `json:"locked"`
	Origin        *string        `json:"origin,omitempty"`
	Path          *string        `json:"path,omitempty"`
	Region        *string        `json:"region,omitempty"`
	Synced        bool           `json:"synced"`
}

// TerminalAppearance defines model for TerminalAppearance.
type TerminalAppearance struct {
	Background     *string `json:"background,omitempty"`
	BackgroundTint *int    `json:"backgroundTint,omitempty"`
	Font           *string `json:"font,omitempty"`
	Palette        *string `json:"palette,omitempty"`
}

// TerminalBackground defines model for TerminalBackground.
type TerminalBackground struct {
	Bytes int    `json:"bytes"`
	Name  string `json:"name"`
	Type  string `json:"type"`
}

// TerminalBackgroundList defines model for TerminalBackgroundList.
type TerminalBackgroundList struct {
	Backgrounds    []TerminalBackground `json:"backgrounds"`
	RemainingBytes int                  `json:"remainingBytes"`
}

// TerminalExit defines model for TerminalExit.
type TerminalExit struct {
	At     string `json:"at"`
	Code   int    `json:"code"`
	Signal string `json:"signal"`
}

// TerminalForward defines model for TerminalForward.
type TerminalForward struct {
	Kind    string `json:"kind"`
	Listen  string `json:"listen"`
	Problem string `json:"problem"`
	To      string `json:"to"`
}

// TerminalReconnect defines model for TerminalReconnect.
type TerminalReconnect struct {
	Attempt int       `json:"attempt"`
	Limit   int       `json:"limit"`
	Problem string    `json:"problem"`
	RetryAt time.Time `json:"retryAt"`
}

// TerminalSession defines model for TerminalSession.
type TerminalSession struct {
	Alias     *string              `json:"alias,omitempty"`
	Exited    *TerminalExit        `json:"exited,omitempty"`
	Forwards  *[]TerminalForward   `json:"forwards,omitempty"`
	Id        string               `json:"id"`
	Kind      TerminalSessionKind  `json:"kind"`
	Problem   string               `json:"problem"`
	Reconnect *TerminalReconnect   `json:"reconnect,omitempty"`
	StartedAt string               `json:"startedAt"`
	State     TerminalSessionState `json:"state"`
	Title     string               `json:"title"`
}

// TerminalSessionKind defines model for TerminalSession.Kind.
type TerminalSessionKind string

// TerminalSessionState defines model for TerminalSession.State.
type TerminalSessionState string

// TerminalSessionList defines model for TerminalSessionList.
type TerminalSessionList struct {
	MaxSessions int               `json:"maxSessions"`
	Sessions    []TerminalSession `json:"sessions"`
}

// TerminalSettings defines model for TerminalSettings.
type TerminalSettings struct {
	Appearance      *TerminalAppearance `json:"appearance,omitempty"`
	CopyOnSelect    *bool               `json:"copyOnSelect,omitempty"`
	FontSize        *int                `json:"fontSize,omitempty"`
	MaxSessions     *int                `json:"maxSessions,omitempty"`
	Reconnect       *int                `json:"reconnect,omitempty"`
	RightClickPaste *bool               `json:"rightClickPaste,omitempty"`
	ScrollbackBytes *int                `json:"scrollbackBytes,omitempty"`
	StartDirectory  *string             `json:"startDirectory,omitempty"`
	Verbosity       *int                `json:"verbosity,omitempty"`
}

// TerminalStreamTicket defines model for TerminalStreamTicket.
type TerminalStreamTicket struct {
	StreamTicket string `json:"streamTicket"`
}

// TerminalWorkspace defines model for TerminalWorkspace.
type TerminalWorkspace struct {
	CreatedAt     time.Time     `json:"createdAt"`
	FocusedPaneId string        `json:"focusedPaneId"`
	Id            string        `json:"id"`
	Layout        WorkspaceNode `json:"layout"`
	Name          string        `json:"name"`
	UpdatedAt     time.Time     `json:"updatedAt"`
}

// TrashEntrySummary defines model for TrashEntrySummary.
type TrashEntrySummary struct {
	AgeDays    int                `json:"ageDays"`
	Blockers   []string           `json:"blockers"`
	DeletedAt  string             `json:"deletedAt"`
	Files      []TrashFileSummary `json:"files"`
	Id         string             `json:"id"`
	Restorable bool               `json:"restorable"`
	Stale      bool               `json:"stale"`
}

// TrashFileSummary defines model for TrashFileSummary.
type TrashFileSummary struct {
	Fingerprint          string `json:"fingerprint"`
	Kind                 string `json:"kind"`
	OriginalRelativePath string `json:"originalRelativePath"`
	Permission           string `json:"permission"`
	TrashRelativePath    string `json:"trashRelativePath"`
}

// TrashKeyResponse defines model for TrashKeyResponse.
type TrashKeyResponse struct {
	EntryId       string             `json:"entryId"`
	Files         []TrashFileSummary `json:"files"`
	Skipped       []string           `json:"skipped"`
	TransactionId string             `json:"transactionId"`
}

// TrashListResponse defines model for TrashListResponse.
type TrashListResponse struct {
	Entries       []TrashEntrySummary `json:"entries"`
	RetentionDays int                 `json:"retentionDays"`
}

// UnreadableFile defines model for UnreadableFile.
type UnreadableFile struct {
	Reason       string `json:"reason"`
	RelativePath string `json:"relativePath"`
}

// UnresolvedReference defines model for UnresolvedReference.
type UnresolvedReference struct {
	ConfigPath string `json:"configPath"`
	Directive  string `json:"directive"`
	Line       int    `json:"line"`
	Reason     string `json:"reason"`
	Value      string `json:"value"`
}

// UpdateConnectionKeyPassphrase defines model for UpdateConnectionKeyPassphrase.
type UpdateConnectionKeyPassphrase = json.RawMessage

// UpdateConnectionPassword defines model for UpdateConnectionPassword.
type UpdateConnectionPassword = json.RawMessage

// UpdateConnectionRequest defines model for UpdateConnectionRequest.
type UpdateConnectionRequest struct {
	Base          string                        `json:"base"`
	HostName      *ConnectionStringChange       `json:"hostName,omitempty"`
	Identity      HostIdentity                  `json:"identity"`
	IdentityFile  *ConnectionIdentityFileChange `json:"identityFile,omitempty"`
	KeyPassphrase UpdateConnectionKeyPassphrase `json:"keyPassphrase"`
	Password      UpdateConnectionPassword      `json:"password"`
	Port          *ConnectionPortChange         `json:"port,omitempty"`
	User          *ConnectionStringChange       `json:"user,omitempty"`
}

// UpdatePasswordRemove defines model for UpdatePasswordRemove.
type UpdatePasswordRemove struct {
	Kind string `json:"kind"`
}

// UpdatePasswordUnchanged defines model for UpdatePasswordUnchanged.
type UpdatePasswordUnchanged struct {
	Kind string `json:"kind"`
}

// UpdateStatus defines model for UpdateStatus.
type UpdateStatus struct {
	Available bool    `json:"available"`
	Current   string  `json:"current"`
	Latest    *string `json:"latest,omitempty"`
	PageUrl   *string `json:"pageUrl,omitempty"`
}

// ValueSource defines model for ValueSource.
type ValueSource struct {
	Condition string `json:"condition"`
	Keyword   string `json:"keyword"`
	Kind      string `json:"kind"`
	Line      int    `json:"line"`
	Path      string `json:"path"`
	Value     string `json:"value"`
	Winner    bool   `json:"winner"`
}

// WorkspaceDefinition defines model for WorkspaceDefinition.
type WorkspaceDefinition struct {
	FocusedPaneId string        `json:"focusedPaneId"`
	Layout        WorkspaceNode `json:"layout"`
	Name          string        `json:"name"`
}

// WorkspaceList defines model for WorkspaceList.
type WorkspaceList struct {
	Workspaces []TerminalWorkspace `json:"workspaces"`
}

// WorkspaceNode defines model for WorkspaceNode.
type WorkspaceNode struct {
	Pane  *WorkspacePane  `json:"pane,omitempty"`
	Split *WorkspaceSplit `json:"split,omitempty"`
}

// WorkspacePane defines model for WorkspacePane.
type WorkspacePane struct {
	Alias string `json:"alias"`
	Id    string `json:"id"`
}

// WorkspaceReconnectPane defines model for WorkspaceReconnectPane.
type WorkspaceReconnectPane struct {
	Alias  string                      `json:"alias"`
	PaneId string                      `json:"paneId"`
	State  WorkspaceReconnectPaneState `json:"state"`
}

// WorkspaceReconnectPaneState defines model for WorkspaceReconnectPane.State.
type WorkspaceReconnectPaneState string

// WorkspaceRestorePlan defines model for WorkspaceRestorePlan.
type WorkspaceRestorePlan struct {
	Panes     []WorkspaceReconnectPane `json:"panes"`
	Workspace TerminalWorkspace        `json:"workspace"`
}

// WorkspaceSplit defines model for WorkspaceSplit.
type WorkspaceSplit struct {
	Direction WorkspaceSplitDirection `json:"direction"`
	First     WorkspaceNode           `json:"first"`
	Ratio     int                     `json:"ratio"`
	Second    WorkspaceNode           `json:"second"`
}

// WorkspaceSplitDirection defines model for WorkspaceSplit.Direction.
type WorkspaceSplitDirection string

// GetConfigFileParams defines parameters for GetConfigFile.
type GetConfigFileParams struct {
	Path string `form:"path" json:"path"`
}

// GetConfigHostParams defines parameters for GetConfigHost.
type GetConfigHostParams struct {
	Path  string `form:"path" json:"path"`
	Alias string `form:"alias" json:"alias"`
}

// RevealPrivateKeyParams defines parameters for RevealPrivateKey.
type RevealPrivateKeyParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// ListKnownHostsParams defines parameters for ListKnownHosts.
type ListKnownHostsParams struct {
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// RegisterRemoteKeyParams defines parameters for RegisterRemoteKey.
type RegisterRemoteKeyParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// BootstrapSessionParams defines parameters for BootstrapSession.
type BootstrapSessionParams struct {
	XSSHCBootstrap string `json:"X-SSHC-Bootstrap"`
}

// DownloadSFTPDirectoryArchiveParams defines parameters for DownloadSFTPDirectoryArchive.
type DownloadSFTPDirectoryArchiveParams struct {
	Path string `form:"path" json:"path"`
}

// DownloadSFTPFileParams defines parameters for DownloadSFTPFile.
type DownloadSFTPFileParams struct {
	Path  string  `form:"path" json:"path"`
	Range *string `json:"Range,omitempty"`
}

// ListSFTPEntriesParams defines parameters for ListSFTPEntries.
type ListSFTPEntriesParams struct {
	Path string `form:"path" json:"path"`
}

// DeleteSFTPEntryParams defines parameters for DeleteSFTPEntry.
type DeleteSFTPEntryParams struct {
	Path        string `form:"path" json:"path"`
	XSSHCAction string `json:"X-SSHC-Action"`
}

// ChmodSFTPEntryParams defines parameters for ChmodSFTPEntry.
type ChmodSFTPEntryParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// ReadSFTPTextParams defines parameters for ReadSFTPText.
type ReadSFTPTextParams struct {
	Path string `form:"path" json:"path"`
}

// SaveSFTPTextParams defines parameters for SaveSFTPText.
type SaveSFTPTextParams struct {
	Path string `form:"path" json:"path"`
}

// UploadSFTPFileParams defines parameters for UploadSFTPFile.
type UploadSFTPFileParams struct {
	Path      string `form:"path" json:"path"`
	Overwrite bool   `form:"overwrite" json:"overwrite"`
}

// CancelSFTPResumableUploadParams defines parameters for CancelSFTPResumableUpload.
type CancelSFTPResumableUploadParams struct {
	Path string `form:"path" json:"path"`
}

// AppendSFTPResumableUploadParams defines parameters for AppendSFTPResumableUpload.
type AppendSFTPResumableUploadParams struct {
	Path   string `form:"path" json:"path"`
	Offset int64  `form:"offset" json:"offset"`
	Total  int64  `form:"total" json:"total"`
}

// ExecuteSnippetParams defines parameters for ExecuteSnippet.
type ExecuteSnippetParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// AddTerminalBackgroundParams defines parameters for AddTerminalBackground.
type AddTerminalBackgroundParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// PurgeTrashEntryParams defines parameters for PurgeTrashEntry.
type PurgeTrashEntryParams struct {
	XSSHCAction string `json:"X-SSHC-Action"`
}

// IssueActionTokenJSONRequestBody defines body for IssueActionToken for application/json ContentType.
type IssueActionTokenJSONRequestBody = IssueActionRequest

// DeleteGroupJSONRequestBody defines body for DeleteGroup for application/json ContentType.
type DeleteGroupJSONRequestBody = GroupDeleteRequest

// RenameGroupJSONRequestBody defines body for RenameGroup for application/json ContentType.
type RenameGroupJSONRequestBody = GroupRenameRequest

// PreviewConfigEditJSONRequestBody defines body for PreviewConfigEdit for application/json ContentType.
type PreviewConfigEditJSONRequestBody = EditRequest

// SaveConfigEditJSONRequestBody defines body for SaveConfigEdit for application/json ContentType.
type SaveConfigEditJSONRequestBody = EditRequest

// UpdateConnectionJSONRequestBody defines body for UpdateConnection for application/json ContentType.
type UpdateConnectionJSONRequestBody = UpdateConnectionRequest

// CreateConnectionJSONRequestBody defines body for CreateConnection for application/json ContentType.
type CreateConnectionJSONRequestBody = CreateConnectionRequest

// AssignCredentialJSONRequestBody defines body for AssignCredential for application/json ContentType.
type AssignCredentialJSONRequestBody = AssignCredentialRequest

// StoreCredentialJSONRequestBody defines body for StoreCredential for application/json ContentType.
type StoreCredentialJSONRequestBody = StoreCredentialRequest

// TestAuthenticationJSONRequestBody defines body for TestAuthentication for application/json ContentType.
type TestAuthenticationJSONRequestBody = AuthenticationRequest

// InspectEffectiveConfigurationJSONRequestBody defines body for InspectEffectiveConfiguration for application/json ContentType.
type InspectEffectiveConfigurationJSONRequestBody = AliasRequest

// CheckReachabilityJSONRequestBody defines body for CheckReachability for application/json ContentType.
type CheckReachabilityJSONRequestBody = AliasRequest

// RecoverTransactionJSONRequestBody defines body for RecoverTransaction for application/json ContentType.
type RecoverTransactionJSONRequestBody = RecoverRequest

// RestoreHistoryEntryJSONRequestBody defines body for RestoreHistoryEntry for application/json ContentType.
type RestoreHistoryEntryJSONRequestBody = RestoreRequest

// GenerateKeyJSONRequestBody defines body for GenerateKey for application/json ContentType.
type GenerateKeyJSONRequestBody = GenerateKeyRequest

// BuildHardwareKeyCommandJSONRequestBody defines body for BuildHardwareKeyCommand for application/json ContentType.
type BuildHardwareKeyCommandJSONRequestBody = HardwareCommandRequest

// RegisterKeyWithAgentJSONRequestBody defines body for RegisterKeyWithAgent for application/json ContentType.
type RegisterKeyWithAgentJSONRequestBody = RegisterKeyRequest

// RelocateKeyJSONRequestBody defines body for RelocateKey for application/json ContentType.
type RelocateKeyJSONRequestBody = RelocateKeyRequest

// ChangeKeyPassphraseJSONRequestBody defines body for ChangeKeyPassphrase for application/json ContentType.
type ChangeKeyPassphraseJSONRequestBody = ChangePassphraseRequest

// AddKnownHostJSONRequestBody defines body for AddKnownHost for application/json ContentType.
type AddKnownHostJSONRequestBody = KnownHostsAddRequest

// DeleteKnownHostsJSONRequestBody defines body for DeleteKnownHosts for application/json ContentType.
type DeleteKnownHostsJSONRequestBody = KnownHostsDeleteRequest

// ScanKnownHostsJSONRequestBody defines body for ScanKnownHosts for application/json ContentType.
type ScanKnownHostsJSONRequestBody = KnownHostsScanRequest

// SetEngineSettingsJSONRequestBody defines body for SetEngineSettings for application/json ContentType.
type SetEngineSettingsJSONRequestBody = EngineSettings

// SetTerminalSettingsJSONRequestBody defines body for SetTerminalSettings for application/json ContentType.
type SetTerminalSettingsJSONRequestBody = TerminalSettings

// ChangeMasterPasswordJSONRequestBody defines body for ChangeMasterPassword for application/json ContentType.
type ChangeMasterPasswordJSONRequestBody = ChangeMasterPasswordRequest

// InitialisePasswordVaultJSONRequestBody defines body for InitialisePasswordVault for application/json ContentType.
type InitialisePasswordVaultJSONRequestBody = PassphraseRequest

// UnlockPasswordVaultJSONRequestBody defines body for UnlockPasswordVault for application/json ContentType.
type UnlockPasswordVaultJSONRequestBody = PassphraseRequest

// StorePasswordJSONRequestBody defines body for StorePassword for application/json ContentType.
type StorePasswordJSONRequestBody = StorePasswordRequest

// PlanRemoteKeyRegistrationJSONRequestBody defines body for PlanRemoteKeyRegistration for application/json ContentType.
type PlanRemoteKeyRegistrationJSONRequestBody = RemoteKeyPlanRequest

// RegisterRemoteKeyJSONRequestBody defines body for RegisterRemoteKey for application/json ContentType.
type RegisterRemoteKeyJSONRequestBody = RemoteKeyRegisterRequest

// CreateSFTPTransferJobJSONRequestBody defines body for CreateSFTPTransferJob for application/json ContentType.
type CreateSFTPTransferJobJSONRequestBody = SFTPCreateTransferJobRequest

// UpdateSFTPTransferJobJSONRequestBody defines body for UpdateSFTPTransferJob for application/json ContentType.
type UpdateSFTPTransferJobJSONRequestBody = SFTPTransferJobActionRequest

// CreateSFTPDirectoryJSONRequestBody defines body for CreateSFTPDirectory for application/json ContentType.
type CreateSFTPDirectoryJSONRequestBody = SFTPMkdirRequest

// RenameSFTPEntryJSONRequestBody defines body for RenameSFTPEntry for application/json ContentType.
type RenameSFTPEntryJSONRequestBody = SFTPRenameRequest

// ChmodSFTPEntryJSONRequestBody defines body for ChmodSFTPEntry for application/json ContentType.
type ChmodSFTPEntryJSONRequestBody = SFTPChmodRequest

// SaveSFTPTextJSONRequestBody defines body for SaveSFTPText for application/json ContentType.
type SaveSFTPTextJSONRequestBody = SFTPSaveTextRequest

// StartSFTPResumableUploadJSONRequestBody defines body for StartSFTPResumableUpload for application/json ContentType.
type StartSFTPResumableUploadJSONRequestBody = SFTPStartUploadRequest

// CompleteSFTPResumableUploadJSONRequestBody defines body for CompleteSFTPResumableUpload for application/json ContentType.
type CompleteSFTPResumableUploadJSONRequestBody = SFTPCompleteUploadRequest

// CreateSnippetJSONRequestBody defines body for CreateSnippet for application/json ContentType.
type CreateSnippetJSONRequestBody = SnippetDraft

// ExecuteSnippetJSONRequestBody defines body for ExecuteSnippet for application/json ContentType.
type ExecuteSnippetJSONRequestBody = SnippetExecuteRequest

// PreviewSnippetExecutionJSONRequestBody defines body for PreviewSnippetExecution for application/json ContentType.
type PreviewSnippetExecutionJSONRequestBody = SnippetPreviewRequest

// SetStartupSnippetJSONRequestBody defines body for SetStartupSnippet for application/json ContentType.
type SetStartupSnippetJSONRequestBody = StartupSnippetRequest

// UpdateSnippetJSONRequestBody defines body for UpdateSnippet for application/json ContentType.
type UpdateSnippetJSONRequestBody = SnippetDraft

// SetAutoSyncJSONRequestBody defines body for SetAutoSync for application/json ContentType.
type SetAutoSyncJSONRequestBody = AutoSyncRequest

// SetSyncKeyJSONRequestBody defines body for SetSyncKey for application/json ContentType.
type SetSyncKeyJSONRequestBody = SyncKeyRequest

// PullSnapshotJSONRequestBody defines body for PullSnapshot for application/json ContentType.
type PullSnapshotJSONRequestBody = PullRequest

// RekeySnapshotJSONRequestBody defines body for RekeySnapshot for application/json ContentType.
type RekeySnapshotJSONRequestBody = PassphraseRequest

// ConfigureSyncJSONRequestBody defines body for ConfigureSync for application/json ContentType.
type ConfigureSyncJSONRequestBody = SyncSettingsRequest

// OpenTerminalSessionJSONRequestBody defines body for OpenTerminalSession for application/json ContentType.
type OpenTerminalSessionJSONRequestBody = OpenTerminalSessionRequest

// RenameTerminalSessionJSONRequestBody defines body for RenameTerminalSession for application/json ContentType.
type RenameTerminalSessionJSONRequestBody = RenameTerminalSessionRequest

// CreateTerminalWorkspaceJSONRequestBody defines body for CreateTerminalWorkspace for application/json ContentType.
type CreateTerminalWorkspaceJSONRequestBody = WorkspaceDefinition

// UpdateTerminalWorkspaceJSONRequestBody defines body for UpdateTerminalWorkspace for application/json ContentType.
type UpdateTerminalWorkspaceJSONRequestBody = WorkspaceDefinition
