// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"
)

// Defines values for AutoSyncPhase.
const (
	Blocked AutoSyncPhase = "blocked"
	Failed  AutoSyncPhase = "failed"
	Idle    AutoSyncPhase = "idle"
	Running AutoSyncPhase = "running"
)

// Valid indicates whether the value is a known member of the AutoSyncPhase enum.
func (e AutoSyncPhase) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Failed:
		return true
	case Idle:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for OpenTerminalSessionRequestKind.
const (
	OpenTerminalSessionRequestKindShell OpenTerminalSessionRequestKind = "shell"
	OpenTerminalSessionRequestKindSsh   OpenTerminalSessionRequestKind = "ssh"
)

// Valid indicates whether the value is a known member of the OpenTerminalSessionRequestKind enum.
func (e OpenTerminalSessionRequestKind) Valid() bool {
	switch e {
	case OpenTerminalSessionRequestKindShell:
		return true
	case OpenTerminalSessionRequestKindSsh:
		return true
	default:
		return false
	}
}

// Defines values for PullRequestResolve.
const (
	Local  PullRequestResolve = "local"
	Remote PullRequestResolve = "remote"
)

// Valid indicates whether the value is a known member of the PullRequestResolve enum.
func (e PullRequestResolve) Valid() bool {
	switch e {
	case Local:
		return true
	case Remote:
		return true
	default:
		return false
	}
}

// Defines values for SyncDirection.
const (
	SyncDirectionBoth SyncDirection = "both"
	SyncDirectionPull SyncDirection = "pull"
	SyncDirectionPush SyncDirection = "push"
)

// Valid indicates whether the value is a known member of the SyncDirection enum.
func (e SyncDirection) Valid() bool {
	switch e {
	case SyncDirectionBoth:
		return true
	case SyncDirectionPull:
		return true
	case SyncDirectionPush:
		return true
	default:
		return false
	}
}

// Defines values for SyncHistoryRelation.
const (
	Ancestor SyncHistoryRelation = "ancestor"
	Branch   SyncHistoryRelation = "branch"
	Head     SyncHistoryRelation = "head"
)

// Valid indicates whether the value is a known member of the SyncHistoryRelation enum.
func (e SyncHistoryRelation) Valid() bool {
	switch e {
	case Ancestor:
		return true
	case Branch:
		return true
	case Head:
		return true
	default:
		return false
	}
}

// Defines values for SyncOperationKind.
const (
	SyncOperationKindApply SyncOperationKind = "apply"
	SyncOperationKindPush  SyncOperationKind = "push"
)

// Valid indicates whether the value is a known member of the SyncOperationKind enum.
func (e SyncOperationKind) Valid() bool {
	switch e {
	case SyncOperationKindApply:
		return true
	case SyncOperationKindPush:
		return true
	default:
		return false
	}
}

// Defines values for SyncSetupTargetState.
const (
	Empty      SyncSetupTargetState = "empty"
	Existing   SyncSetupTargetState = "existing"
	Incomplete SyncSetupTargetState = "incomplete"
)

// Valid indicates whether the value is a known member of the SyncSetupTargetState enum.
func (e SyncSetupTargetState) Valid() bool {
	switch e {
	case Empty:
		return true
	case Existing:
		return true
	case Incomplete:
		return true
	default:
		return false
	}
}

// Defines values for TerminalSessionKind.
const (
	TerminalSessionKindShell TerminalSessionKind = "shell"
	TerminalSessionKindSsh   TerminalSessionKind = "ssh"
)

// Valid indicates whether the value is a known member of the TerminalSessionKind enum.
func (e TerminalSessionKind) Valid() bool {
	switch e {
	case TerminalSessionKindShell:
		return true
	case TerminalSessionKindSsh:
		return true
	default:
		return false
	}
}

// Defines values for TerminalSessionState.
const (
	Connected    TerminalSessionState = "connected"
	Connecting   TerminalSessionState = "connecting"
	Exited       TerminalSessionState = "exited"
	Reconnecting TerminalSessionState = "reconnecting"
)

// Valid indicates whether the value is a known member of the TerminalSessionState enum.
func (e TerminalSessionState) Valid() bool {
	switch e {
	case Connected:
		return true
	case Connecting:
		return true
	case Exited:
		return true
	case Reconnecting:
		return true
	default:
		return false
	}
}

// AgentIdentitiesResponse defines model for AgentIdentitiesResponse.
type AgentIdentitiesResponse struct {
	AgentAvailable bool            `json:"agentAvailable"`
	Id             string          `json:"id"`
	Identities     []AgentIdentity `json:"identities"`
}

// AgentIdentity defines model for AgentIdentity.
type AgentIdentity struct {
	Algorithm   string `json:"algorithm"`
	Bits        int    `json:"bits"`
	Comment     string `json:"comment"`
	Fingerprint string `json:"fingerprint"`
}

// AliasRequest defines model for AliasRequest.
type AliasRequest struct {
	Alias string `json:"alias"`
}

// AssignCredentialRequest defines model for AssignCredentialRequest.
type AssignCredentialRequest struct {
	Name    string `json:"name"`
	Subject string `json:"subject"`
}

// AuthenticationRequest defines model for AuthenticationRequest.
type AuthenticationRequest struct {
	AcknowledgeExecutable bool   `json:"acknowledgeExecutable"`
	Alias                 string `json:"alias"`
}

// AuthenticationResponse defines model for AuthenticationResponse.
type AuthenticationResponse struct {
	Authenticated bool   `json:"authenticated"`
	Detail        string `json:"detail"`
	ElapsedMs     int    `json:"elapsedMs"`
	Method        string `json:"method"`
	Outcome       string `json:"outcome"`
	Truncated     bool   `json:"truncated"`
}

// AutoSync defines model for AutoSync.
type AutoSync struct {
	At      *string       `json:"at,omitempty"`
	Detail  *string       `json:"detail,omitempty"`
	Enabled bool          `json:"enabled"`
	Phase   AutoSyncPhase `json:"phase"`
}

// AutoSyncPhase defines model for AutoSync.Phase.
type AutoSyncPhase string

// AutoSyncRequest defines model for AutoSyncRequest.
type AutoSyncRequest struct {
	Enabled bool `json:"enabled"`
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// ChangeMasterPasswordRequest defines model for ChangeMasterPasswordRequest.
type ChangeMasterPasswordRequest struct {
	Current string `json:"current"`
	Next    string `json:"next"`
}

// ChangeMasterPasswordResult defines model for ChangeMasterPasswordResult.
type ChangeMasterPasswordResult struct {
	Vault PasswordVaultStatus `json:"vault"`
}

// ChangePassphraseRequest defines model for ChangePassphraseRequest.
type ChangePassphraseRequest struct {
	CurrentPassphrase string `json:"currentPassphrase"`
	NewPassphrase     string `json:"newPassphrase"`
	Unencrypted       bool   `json:"unencrypted"`
}

// ChangePassphraseResponse defines model for ChangePassphraseResponse.
type ChangePassphraseResponse struct {
	Encrypted     bool     `json:"encrypted"`
	Id            string   `json:"id"`
	Notes         []string `json:"notes"`
	RelativePath  string   `json:"relativePath"`
	TransactionId string   `json:"transactionId"`
}

// ComplexityNote defines model for ComplexityNote.
type ComplexityNote struct {
	Code      string `json:"code"`
	Condition string `json:"condition"`
	Detail    string `json:"detail"`
	Line      int    `json:"line"`
	Path      string `json:"path"`
}

// ConfigCheckResponse defines model for ConfigCheckResponse.
type ConfigCheckResponse struct {
	Diagnostics []ConfigDiagnostic  `json:"diagnostics"`
	Files       []ConfigFileSummary `json:"files"`
	Root        string              `json:"root"`
}

// ConfigDiagnostic defines model for ConfigDiagnostic.
type ConfigDiagnostic struct {
	Code     string `json:"code"`
	Detail   string `json:"detail"`
	Line     int    `json:"line"`
	Path     string `json:"path"`
	Severity string `json:"severity"`
}

// ConfigFileSummary defines model for ConfigFileSummary.
type ConfigFileSummary struct {
	Editable bool   `json:"editable"`
	Includes int    `json:"includes"`
	Loads    int    `json:"loads"`
	Missing  bool   `json:"missing"`
	Path     string `json:"path"`
}

// ConflictReport defines model for ConflictReport.
type ConflictReport struct {
	BaseDigest     *string    `json:"baseDigest,omitempty"`
	DiskDigest     *string    `json:"diskDigest,omitempty"`
	ExternalChange []DiffLine `json:"externalChange"`
	LocalChange    []DiffLine `json:"localChange"`
	Path           string     `json:"path"`
}

// ConnectionIdentityFileChange defines model for ConnectionIdentityFileChange.
type ConnectionIdentityFileChange = json.RawMessage

// ConnectionIdentityFileSet defines model for ConnectionIdentityFileSet.
type ConnectionIdentityFileSet struct {
	Action string `json:"action"`
	KeyId  string `json:"keyId"`
}

// ConnectionInherit defines model for ConnectionInherit.
type ConnectionInherit struct {
	Action string `json:"action"`
}

// ConnectionKeyPassphraseSetDedicated defines model for ConnectionKeyPassphraseSetDedicated.
type ConnectionKeyPassphraseSetDedicated struct {
	KeyId      string `json:"keyId"`
	Kind       string `json:"kind"`
	Passphrase string `json:"passphrase"`
}

// ConnectionKeyPassphraseUnchanged defines model for ConnectionKeyPassphraseUnchanged.
type ConnectionKeyPassphraseUnchanged struct {
	Kind string `json:"kind"`
}

// ConnectionPortChange defines model for ConnectionPortChange.
type ConnectionPortChange = json.RawMessage

// ConnectionPortSet defines model for ConnectionPortSet.
type ConnectionPortSet struct {
	Action string `json:"action"`
	Value  int    `json:"value"`
}

// ConnectionStringChange defines model for ConnectionStringChange.
type ConnectionStringChange = json.RawMessage

// ConnectionStringSet defines model for ConnectionStringSet.
type ConnectionStringSet struct {
	Action string `json:"action"`
	Value  string `json:"value"`
}

// CreateConnectionAuthentication defines model for CreateConnectionAuthentication.
type CreateConnectionAuthentication = json.RawMessage

// CreateConnectionRequest defines model for CreateConnectionRequest.
type CreateConnectionRequest struct {
	Alias          string                         `json:"alias"`
	Authentication CreateConnectionAuthentication `json:"authentication"`
	Group          *string                        `json:"group,omitempty"`
	HostName       string                         `json:"hostName"`
	Port           *int                           `json:"port,omitempty"`
	User           *string                        `json:"user,omitempty"`
}

// CreateDedicatedPasswordAuthentication defines model for CreateDedicatedPasswordAuthentication.
type CreateDedicatedPasswordAuthentication struct {
	Kind     string `json:"kind"`
	Password string `json:"password"`
}

// CreateIdentityFileAuthentication defines model for CreateIdentityFileAuthentication.
type CreateIdentityFileAuthentication struct {
	KeyId string `json:"keyId"`
	Kind  string `json:"kind"`
}

// CreateNewSharedPasswordAuthentication defines model for CreateNewSharedPasswordAuthentication.
type CreateNewSharedPasswordAuthentication struct {
	Credential string `json:"credential"`
	Kind       string `json:"kind"`
	Password   string `json:"password"`
}

// CreateSavedPasswordAuthentication defines model for CreateSavedPasswordAuthentication.
type CreateSavedPasswordAuthentication struct {
	Credential string `json:"credential"`
	Kind       string `json:"kind"`
}

// Credential defines model for Credential.
type Credential struct {
	Hosts []string `json:"hosts"`
	Kind  string   `json:"kind"`
	Name  string   `json:"name"`
	Uses  []string `json:"uses"`
}

// CredentialList defines model for CredentialList.
type CredentialList struct {
	Credentials             []Credential                  `json:"credentials"`
	DedicatedKeyPassphrases []DedicatedKeyPassphraseUsage `json:"dedicatedKeyPassphrases"`
	KeyHostUsageComplete    bool                          `json:"keyHostUsageComplete"`
}

// DedicatedKeyPassphraseUsage defines model for DedicatedKeyPassphraseUsage.
type DedicatedKeyPassphraseUsage struct {
	Hosts []string `json:"hosts"`
	Key   string   `json:"key"`
}

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Absolute *string `json:"absolute,omitempty"`
	Code     string  `json:"code"`
	Detail   *string `json:"detail,omitempty"`
	External *bool   `json:"external,omitempty"`
	Line     *int    `json:"line,omitempty"`
	Path     *string `json:"path,omitempty"`
	Severity string  `json:"severity"`
}

// DiffLine defines model for DiffLine.
type DiffLine struct {
	NewLine *int   `json:"newLine,omitempty"`
	OldLine *int   `json:"oldLine,omitempty"`
	Op      string `json:"op"`
	Text    string `json:"text"`
}

// EffectiveResponse defines model for EffectiveResponse.
type EffectiveResponse struct {
	Alias                string                `json:"alias"`
	Complexities         []ComplexityNote      `json:"complexities"`
	ExecutableDirectives []ExecutableDirective `json:"executableDirectives"`
	Route                []JumpStage           `json:"route"`
	Sources              []ValueSource         `json:"sources"`
	TokenWarning         string                `json:"tokenWarning"`
}

// EngineSettings defines model for EngineSettings.
type EngineSettings struct {
	Port *int `json:"port,omitempty"`
}

// ExecutableDirective defines model for ExecutableDirective.
type ExecutableDirective struct {
	Command     string `json:"command"`
	Condition   string `json:"condition"`
	Keyword     string `json:"keyword"`
	Line        int    `json:"line"`
	OnConnect   bool   `json:"onConnect"`
	OnEvaluate  bool   `json:"onEvaluate"`
	Overridable bool   `json:"overridable"`
	Path        string `json:"path"`
}

// GenerateKeyRequest defines model for GenerateKeyRequest.
type GenerateKeyRequest struct {
	Algorithm   string  `json:"algorithm"`
	Bits        *int    `json:"bits,omitempty"`
	Comment     string  `json:"comment"`
	FileName    string  `json:"fileName"`
	Group       *string `json:"group,omitempty"`
	Passphrase  string  `json:"passphrase"`
	Unencrypted bool    `json:"unencrypted"`
}

// GenerateKeyResponse defines model for GenerateKeyResponse.
type GenerateKeyResponse struct {
	Bits               int    `json:"bits"`
	Encrypted          bool   `json:"encrypted"`
	Fingerprint        string `json:"fingerprint"`
	Id                 string `json:"id"`
	KeyType            string `json:"keyType"`
	PublicRelativePath string `json:"publicRelativePath"`
	RelativePath       string `json:"relativePath"`
	TransactionId      string `json:"transactionId"`
}

// GroupDeleteRequest defines model for GroupDeleteRequest.
type GroupDeleteRequest struct {
	Destination *string `json:"destination,omitempty"`
	Name        string  `json:"name"`
}

// GroupRenameRequest defines model for GroupRenameRequest.
type GroupRenameRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// HardwareCommandRequest defines model for HardwareCommandRequest.
type HardwareCommandRequest struct {
	Algorithm string  `json:"algorithm"`
	Comment   string  `json:"comment"`
	FileName  string  `json:"fileName"`
	Group     *string `json:"group,omitempty"`
}

// HardwareCommandResponse defines model for HardwareCommandResponse.
type HardwareCommandResponse struct {
	Algorithm string   `json:"algorithm"`
	Command   []string `json:"command"`
	Note      string   `json:"note"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// HostIdentity defines model for HostIdentity.
type HostIdentity struct {
	Alias string `json:"alias"`
	Path  string `json:"path"`
}

// IssueActionRequest defines model for IssueActionRequest.
type IssueActionRequest struct {
	Kind   string `json:"kind"`
	Target string `json:"target"`
}

// IssueActionResponse defines model for IssueActionResponse.
type IssueActionResponse struct {
	ExpiresAt string `json:"expiresAt"`
	Token     string `json:"token"`
}

// JumpStage defines model for JumpStage.
type JumpStage struct {
	Complex  bool   `json:"complex"`
	Depth    int    `json:"depth"`
	Hop      string `json:"hop"`
	Hostname string `json:"hostname"`
	Order    int    `json:"order"`
	Parent   string `json:"parent"`
	Port     string `json:"port"`
	User     string `json:"user"`
}

// KeyAlgorithmsResponse defines model for KeyAlgorithmsResponse.
type KeyAlgorithmsResponse struct {
	Source   string       `json:"source"`
	Variants []KeyVariant `json:"variants"`
}

// KeyCertificate defines model for KeyCertificate.
type KeyCertificate struct {
	KeyId                string   `json:"keyId"`
	NeverExpires         bool     `json:"neverExpires"`
	Principals           []string `json:"principals"`
	SignedKeyFingerprint string   `json:"signedKeyFingerprint"`
	SignedKeyType        string   `json:"signedKeyType"`
	ValidBefore          int      `json:"validBefore"`
}

// KeyInventoryResponse defines model for KeyInventoryResponse.
type KeyInventoryResponse struct {
	AgentAvailable       bool                  `json:"agentAvailable"`
	AgentDelegations     []KeyReference        `json:"agentDelegations"`
	AgentIdentities      []AgentIdentity       `json:"agentIdentities"`
	Items                []KeyItem             `json:"items"`
	Unreadable           []UnreadableFile      `json:"unreadable"`
	UnresolvedReferences []UnresolvedReference `json:"unresolvedReferences"`
}

// KeyItem defines model for KeyItem.
type KeyItem struct {
	Algorithm      string          `json:"algorithm"`
	Bits           int             `json:"bits"`
	Certificate    *KeyCertificate `json:"certificate,omitempty"`
	Comment        string          `json:"comment"`
	Container      string          `json:"container"`
	Encrypted      bool            `json:"encrypted"`
	Fingerprint    string          `json:"fingerprint"`
	Id             string          `json:"id"`
	KeyType        string          `json:"keyType"`
	Kind           string          `json:"kind"`
	Notes          []string        `json:"notes"`
	Permission     string          `json:"permission"`
	PermissionRisk bool            `json:"permissionRisk"`
	References     []KeyReference  `json:"references"`
	RelativePath   string          `json:"relativePath"`
	SizeBytes      int             `json:"sizeBytes"`
}

// KeyReference defines model for KeyReference.
type KeyReference struct {
	Condition    string   `json:"condition"`
	ConfigPath   string   `json:"configPath"`
	Directive    string   `json:"directive"`
	HostPatterns []string `json:"hostPatterns"`
	Line         int      `json:"line"`
	Value        string   `json:"value"`
}

// KeyVariant defines model for KeyVariant.
type KeyVariant struct {
	Algorithm string `json:"algorithm"`
	Bits      int    `json:"bits"`
	InProcess bool   `json:"inProcess"`
	Label     string `json:"label"`
	Reason    string `json:"reason"`
}

// KnownHostCandidate defines model for KnownHostCandidate.
type KnownHostCandidate struct {
	Fingerprint string `json:"fingerprint"`
	Host        string `json:"host"`
	Key         string `json:"key"`
	KeyType     string `json:"keyType"`
	Port        int    `json:"port"`
	Verified    bool   `json:"verified"`
}

// KnownHostEntry defines model for KnownHostEntry.
type KnownHostEntry struct {
	Comment     string   `json:"comment"`
	Digest      string   `json:"digest"`
	Fingerprint string   `json:"fingerprint"`
	Hashed      bool     `json:"hashed"`
	Hosts       []string `json:"hosts"`
	KeyType     string   `json:"keyType"`
	Line        int      `json:"line"`
	Marker      string   `json:"marker"`
}

// KnownHostTarget defines model for KnownHostTarget.
type KnownHostTarget struct {
	Digest string `json:"digest"`
	Line   int    `json:"line"`
}

// KnownHostsAddRequest defines model for KnownHostsAddRequest.
type KnownHostsAddRequest struct {
	Acknowledged        bool   `json:"acknowledged"`
	ExpectedFingerprint string `json:"expectedFingerprint"`
	Host                string `json:"host"`
	Key                 string `json:"key"`
	KeyType             string `json:"keyType"`
	Port                int    `json:"port"`
}

// KnownHostsChangeResponse defines model for KnownHostsChangeResponse.
type KnownHostsChangeResponse struct {
	Changed       bool   `json:"changed"`
	TransactionId string `json:"transactionId"`
}

// KnownHostsDeleteRequest defines model for KnownHostsDeleteRequest.
type KnownHostsDeleteRequest struct {
	Entries []KnownHostTarget `json:"entries"`
}

// KnownHostsResponse defines model for KnownHostsResponse.
type KnownHostsResponse struct {
	Entries []KnownHostEntry `json:"entries"`
	Path    string           `json:"path"`
}

// KnownHostsScanRequest defines model for KnownHostsScanRequest.
type KnownHostsScanRequest struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

// KnownHostsScanResponse defines model for KnownHostsScanResponse.
type KnownHostsScanResponse struct {
	Candidates []KnownHostCandidate `json:"candidates"`
	Notice     string               `json:"notice"`
}

// Notice defines model for Notice.
type Notice struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Line   *int    `json:"line,omitempty"`
	Path   *string `json:"path,omitempty"`
}

// OpenTerminalSessionRequest defines model for OpenTerminalSessionRequest.
type OpenTerminalSessionRequest struct {
	Alias *string                        `json:"alias,omitempty"`
	Cols  *int                           `json:"cols,omitempty"`
	Kind  OpenTerminalSessionRequestKind `json:"kind"`
	Rows  *int                           `json:"rows,omitempty"`
}

// OpenTerminalSessionRequestKind defines model for OpenTerminalSessionRequest.Kind.
type OpenTerminalSessionRequestKind string

// OpenTerminalSessionResponse defines model for OpenTerminalSessionResponse.
type OpenTerminalSessionResponse struct {
	Session      TerminalSession `json:"session"`
	StreamTicket string          `json:"streamTicket"`
}

// PassphraseRequest defines model for PassphraseRequest.
type PassphraseRequest struct {
	Passphrase string `json:"passphrase"`
}

// PasswordEligibility defines model for PasswordEligibility.
type PasswordEligibility struct {
	Alias    string   `json:"alias"`
	Blockers []Notice `json:"blockers"`
	HostName *string  `json:"hostName,omitempty"`
	Port     *string  `json:"port,omitempty"`
	Storable bool     `json:"storable"`
	Warnings []Notice `json:"warnings"`
}

// PasswordVaultStatus defines model for PasswordVaultStatus.
type PasswordVaultStatus struct {
	Aliases                 []string `json:"aliases"`
	DedicatedKeyPassphrases []string `json:"dedicatedKeyPassphrases"`
	Exists                  bool     `json:"exists"`
	MigratedFromVersion     *int     `json:"migratedFromVersion,omitempty"`
	MigratedToVersion       *int     `json:"migratedToVersion,omitempty"`
	MinPassphraseLength     *int     `json:"minPassphraseLength,omitempty"`
	Unlocked                bool     `json:"unlocked"`
}

// Problem defines model for Problem.
type Problem struct {
	Blockers        *[]string       `json:"blockers,omitempty"`
	Code            string          `json:"code"`
	Column          *int            `json:"column,omitempty"`
	Conflict        *ConflictReport `json:"conflict,omitempty"`
	CurrentVersion  *int            `json:"currentVersion,omitempty"`
	Detail          *string         `json:"detail,omitempty"`
	Diagnostics     *[]Diagnostic   `json:"diagnostics,omitempty"`
	Line            *int            `json:"line,omitempty"`
	Message         string          `json:"message"`
	Path            *string         `json:"path,omitempty"`
	RequiredVersion *int            `json:"requiredVersion,omitempty"`
}

// PublicKeyResponse defines model for PublicKeyResponse.
type PublicKeyResponse struct {
	Comment      string `json:"comment"`
	Fingerprint  string `json:"fingerprint"`
	Id           string `json:"id"`
	PublicKey    string `json:"publicKey"`
	RelativePath string `json:"relativePath"`
}

// PullRequest defines model for PullRequest.
type PullRequest struct {
	Apply            *bool               `json:"apply,omitempty"`
	ExpectedETag     *string             `json:"expectedETag,omitempty"`
	ExpectedRevision *string             `json:"expectedRevision,omitempty"`
	HistoryKey       *string             `json:"historyKey,omitempty"`
	Resolve          *PullRequestResolve `json:"resolve,omitempty"`
}

// PullRequestResolve defines model for PullRequest.Resolve.
type PullRequestResolve string

// PullResponse defines model for PullResponse.
type PullResponse struct {
	Applied         bool            `json:"applied"`
	CompletedAt     string          `json:"completedAt"`
	Conflicts       []SyncConflict  `json:"conflicts"`
	DownloadedBytes int64           `json:"downloadedBytes"`
	Origin          *string         `json:"origin,omitempty"`
	RemoteETag      string          `json:"remoteETag"`
	RemoteRevision  string          `json:"remoteRevision"`
	Removed         []string        `json:"removed"`
	Summary         SnapshotSummary `json:"summary"`
	Written         []string        `json:"written"`
}

// PurgeTrashResponse defines model for PurgeTrashResponse.
type PurgeTrashResponse struct {
	EntryId       string   `json:"entryId"`
	Removed       []string `json:"removed"`
	TransactionId string   `json:"transactionId"`
}

// PushResponse defines model for PushResponse.
type PushResponse struct {
	Result PushResult `json:"result"`
	Status SyncStatus `json:"status"`
}

// PushResult defines model for PushResult.
type PushResult struct {
	CompletedAt   string          `json:"completedAt"`
	ObjectCount   int             `json:"objectCount"`
	Summary       SnapshotSummary `json:"summary"`
	UploadedBytes int64           `json:"uploadedBytes"`
}

// ReachabilityResponse defines model for ReachabilityResponse.
type ReachabilityResponse struct {
	Address   string `json:"address"`
	Detail    string `json:"detail"`
	ElapsedMs int    `json:"elapsedMs"`
	Notice    string `json:"notice"`
	Outcome   string `json:"outcome"`
}

// RecentConnection defines model for RecentConnection.
type RecentConnection struct {
	Alias           string    `json:"alias"`
	HostName        string    `json:"hostName"`
	LastConnectedAt time.Time `json:"lastConnectedAt"`
	Port            string    `json:"port"`
	User            string    `json:"user"`
}

// RecentConnectionList defines model for RecentConnectionList.
type RecentConnectionList struct {
	Connections []RecentConnection `json:"connections"`
}

// RecoverRequest defines model for RecoverRequest.
type RecoverRequest struct {
	Action        string `json:"action"`
	TransactionId string `json:"transactionId"`
}

// RecoverResponse defines model for RecoverResponse.
type RecoverResponse struct {
	Status string `json:"status"`
}

// RegisterKeyRequest defines model for RegisterKeyRequest.
type RegisterKeyRequest struct {
	LifetimeSeconds int    `json:"lifetimeSeconds"`
	Passphrase      string `json:"passphrase"`
}

// RegisterKeyResponse defines model for RegisterKeyResponse.
type RegisterKeyResponse struct {
	Fingerprint     string          `json:"fingerprint"`
	Id              string          `json:"id"`
	Identities      []AgentIdentity `json:"identities"`
	LifetimeSeconds int             `json:"lifetimeSeconds"`
	RelativePath    string          `json:"relativePath"`
}

// RelocateKeyRequest defines model for RelocateKeyRequest.
type RelocateKeyRequest struct {
	Group   *string `json:"group,omitempty"`
	NewName *string `json:"newName,omitempty"`
}

// RelocateKeyResponse defines model for RelocateKeyResponse.
type RelocateKeyResponse struct {
	Blockers      []string                `json:"blockers"`
	Files         []RelocatedKeyFile      `json:"files"`
	Group         string                  `json:"group"`
	Id            string                  `json:"id"`
	Notes         []string                `json:"notes"`
	References    []RewrittenKeyReference `json:"references"`
	RelativePath  string                  `json:"relativePath"`
	Skipped       []string                `json:"skipped"`
	TransactionId string                  `json:"transactionId"`
}

// RelocatedKeyFile defines model for RelocatedKeyFile.
type RelocatedKeyFile struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// RemoteKeyPlan defines model for RemoteKeyPlan.
type RemoteKeyPlan struct {
	ActionExpiresAt      string                `json:"actionExpiresAt"`
	ActionToken          string                `json:"actionToken"`
	Alias                string                `json:"alias"`
	ExecutableDirectives []ExecutableDirective `json:"executableDirectives"`
	Fingerprint          string                `json:"fingerprint"`
	Hostname             string                `json:"hostname"`
	KeyLine              string                `json:"keyLine"`
	KeyPath              string                `json:"keyPath"`
	Manual               []string              `json:"manual"`
	Port                 string                `json:"port"`
	RemotePath           string                `json:"remotePath"`
	Routine              string                `json:"routine"`
	Supported            bool                  `json:"supported"`
	User                 string                `json:"user"`
	ValuesFrom           string                `json:"valuesFrom"`
}

// RemoteKeyPlanRequest defines model for RemoteKeyPlanRequest.
type RemoteKeyPlanRequest struct {
	Alias     string `json:"alias"`
	KeyPath   string `json:"keyPath"`
	PublicKey string `json:"publicKey"`
}

// RemoteKeyRegisterRequest defines model for RemoteKeyRegisterRequest.
type RemoteKeyRegisterRequest struct {
	AcknowledgeExecutable bool   `json:"acknowledgeExecutable"`
	Alias                 string `json:"alias"`
	KeyPath               string `json:"keyPath"`
	PublicKey             string `json:"publicKey"`
}

// RemoteKeyRegisterResponse defines model for RemoteKeyRegisterResponse.
type RemoteKeyRegisterResponse struct {
	ExitCode  int    `json:"exitCode"`
	Outcome   string `json:"outcome"`
	Stderr    string `json:"stderr"`
	Truncated bool   `json:"truncated"`
}

// RenameTerminalSessionRequest defines model for RenameTerminalSessionRequest.
type RenameTerminalSessionRequest struct {
	Title string `json:"title"`
}

// ResetUnsupportedVaultRequest defines model for ResetUnsupportedVaultRequest.
type ResetUnsupportedVaultRequest struct {
	Acknowledged bool   `json:"acknowledged"`
	Passphrase   string `json:"passphrase"`
}

// RestoreRequest defines model for RestoreRequest.
type RestoreRequest struct {
	Path          string `json:"path"`
	TransactionId string `json:"transactionId"`
}

// RestoreTrashResponse defines model for RestoreTrashResponse.
type RestoreTrashResponse struct {
	Blockers      []string `json:"blockers"`
	EntryId       string   `json:"entryId"`
	Restored      []string `json:"restored"`
	TransactionId string   `json:"transactionId"`
}

// RevealPrivateKeyResponse defines model for RevealPrivateKeyResponse.
type RevealPrivateKeyResponse struct {
	Encrypted     bool   `json:"encrypted"`
	Fingerprint   string `json:"fingerprint"`
	Id            string `json:"id"`
	PrivateKey    string `json:"privateKey"`
	RelativePath  string `json:"relativePath"`
	TransactionId string `json:"transactionId"`
}

// RewrittenKeyReference defines model for RewrittenKeyReference.
type RewrittenKeyReference struct {
	ConfigPath string `json:"configPath"`
	Directive  string `json:"directive"`
	From       string `json:"from"`
	Line       int    `json:"line"`
	To         string `json:"to"`
}

// SnapshotSummary defines model for SnapshotSummary.
type SnapshotSummary struct {
	CreatedAt     string `json:"createdAt"`
	FileCount     int    `json:"fileCount"`
	SnapshotBytes int64  `json:"snapshotBytes"`
	SourceBytes   int64  `json:"sourceBytes"`
}

// StoreCredentialRequest defines model for StoreCredentialRequest.
type StoreCredentialRequest struct {
	Secret string `json:"secret"`
}

// StorePasswordRequest defines model for StorePasswordRequest.
type StorePasswordRequest struct {
	Password string `json:"password"`
}

// SyncBucketObject defines model for SyncBucketObject.
type SyncBucketObject struct {
	Key          string  `json:"key"`
	LastModified *string `json:"lastModified,omitempty"`
	Size         int64   `json:"size"`
}

// SyncBucketStatus defines model for SyncBucketStatus.
type SyncBucketStatus struct {
	CheckedAt        string             `json:"checkedAt"`
	History          []SyncBucketObject `json:"history"`
	HistoryTruncated bool               `json:"historyTruncated"`
	Live             *SyncBucketObject  `json:"live,omitempty"`
	LocalIsLive      bool               `json:"localIsLive"`
}

// SyncConflict defines model for SyncConflict.
type SyncConflict struct {
	ChangedHere  bool   `json:"changedHere"`
	ChangedThere bool   `json:"changedThere"`
	Path         string `json:"path"`
}

// SyncDirection defines model for SyncDirection.
type SyncDirection string

// SyncHistory defines model for SyncHistory.
type SyncHistory struct {
	CheckedAt         string                `json:"checkedAt"`
	DownloadTruncated bool                  `json:"downloadTruncated"`
	DownloadedBytes   int64                 `json:"downloadedBytes"`
	HeadRevision      string                `json:"headRevision"`
	HistoryTruncated  bool                  `json:"historyTruncated"`
	Revisions         []SyncHistoryRevision `json:"revisions"`
	Skipped           int                   `json:"skipped"`
}

// SyncHistoryDiff defines model for SyncHistoryDiff.
type SyncHistoryDiff struct {
	Added           []string `json:"added"`
	DownloadedBytes int64    `json:"downloadedBytes"`
	FromRevision    string   `json:"fromRevision"`
	Modified        []string `json:"modified"`
	Removed         []string `json:"removed"`
	ToRevision      string   `json:"toRevision"`
}

// SyncHistoryDiffRequest defines model for SyncHistoryDiffRequest.
type SyncHistoryDiffRequest struct {
	Key string `json:"key"`
}

// SyncHistoryRelation defines model for SyncHistoryRelation.
type SyncHistoryRelation string

// SyncHistoryRevision defines model for SyncHistoryRevision.
type SyncHistoryRevision struct {
	CreatedAt      string              `json:"createdAt"`
	FileCount      int                 `json:"fileCount"`
	Key            string              `json:"key"`
	LastModified   *string             `json:"lastModified,omitempty"`
	Message        string              `json:"message"`
	Origin         string              `json:"origin"`
	ParentRevision *string             `json:"parentRevision,omitempty"`
	Relation       SyncHistoryRelation `json:"relation"`
	Revision       string              `json:"revision"`
	Size           int64               `json:"size"`
}

// SyncKeyRequest defines model for SyncKeyRequest.
type SyncKeyRequest struct {
	ConfirmHistoryLoss *bool   `json:"confirmHistoryLoss,omitempty"`
	Key                *string `json:"key,omitempty"`
}

// SyncKeyResponse defines model for SyncKeyResponse.
type SyncKeyResponse struct {
	Key string `json:"key"`
}

// SyncOperation defines model for SyncOperation.
type SyncOperation struct {
	CompletedAt     string            `json:"completedAt"`
	DownloadedBytes *int64            `json:"downloadedBytes,omitempty"`
	Kind            SyncOperationKind `json:"kind"`
	ObjectCount     *int              `json:"objectCount,omitempty"`
	Removed         *int              `json:"removed,omitempty"`
	Summary         SnapshotSummary   `json:"summary"`
	UploadedBytes   *int64            `json:"uploadedBytes,omitempty"`
	Written         *int              `json:"written,omitempty"`
}

// SyncOperationKind defines model for SyncOperationKind.
type SyncOperationKind string

// SyncPushDraft defines model for SyncPushDraft.
type SyncPushDraft struct {
	Added    int    `json:"added"`
	Message  string `json:"message"`
	Modified int    `json:"modified"`
	Removed  int    `json:"removed"`
}

// SyncPushRequest defines model for SyncPushRequest.
type SyncPushRequest struct {
	Message string `json:"message"`
}

// SyncSettingsRequest defines model for SyncSettingsRequest.
type SyncSettingsRequest struct {
	AccessKeyId     string        `json:"accessKeyId"`
	Bucket          string        `json:"bucket"`
	Direction       SyncDirection `json:"direction"`
	Endpoint        string        `json:"endpoint"`
	Path            *string       `json:"path,omitempty"`
	Region          *string       `json:"region,omitempty"`
	SecretAccessKey string        `json:"secretAccessKey"`
}

// SyncSetupCheckRequest defines model for SyncSetupCheckRequest.
type SyncSetupCheckRequest struct {
	AccessKeyId     string  `json:"accessKeyId"`
	Bucket          string  `json:"bucket"`
	Endpoint        string  `json:"endpoint"`
	Path            *string `json:"path,omitempty"`
	Region          *string `json:"region,omitempty"`
	SecretAccessKey string  `json:"secretAccessKey"`
}

// SyncSetupCheckResponse defines model for SyncSetupCheckResponse.
type SyncSetupCheckResponse struct {
	CheckedAt      string               `json:"checkedAt"`
	Etag           *string              `json:"etag,omitempty"`
	HistoryPresent bool                 `json:"historyPresent"`
	State          SyncSetupTargetState `json:"state"`
}

// SyncSetupRequest defines model for SyncSetupRequest.
type SyncSetupRequest struct {
	AccessKeyId     string               `json:"accessKeyId"`
	Bucket          string               `json:"bucket"`
	Direction       SyncDirection        `json:"direction"`
	Endpoint        string               `json:"endpoint"`
	ExpectedETag    *string              `json:"expectedETag,omitempty"`
	ExpectedState   SyncSetupTargetState `json:"expectedState"`
	HistoryPresent  bool                 `json:"historyPresent"`
	Key             string               `json:"key"`
	Path            *string              `json:"path,omitempty"`
	Region          *string              `json:"region,omitempty"`
	SecretAccessKey string               `json:"secretAccessKey"`
}

// SyncSetupResponse defines model for SyncSetupResponse.
type SyncSetupResponse struct {
	GeneratedKey *string    `json:"generatedKey,omitempty"`
	Status       SyncStatus `json:"status"`
}

// SyncSetupTargetState defines model for SyncSetupTargetState.
type SyncSetupTargetState string

// SyncStatus defines model for SyncStatus.
type SyncStatus struct {
	Auto          AutoSync       `json:"auto"`
	Bucket        string         `json:"bucket"`
	Configured    bool           `json:"configured"`
	Direction     SyncDirection  `json:"direction"`
	Endpoint      string         `json:"endpoint"`
	FileCount     *int           `json:"fileCount,omitempty"`
	KeyConfigured bool           `json:"keyConfigured"`
	LastOperation *SyncOperation `json:"lastOperation,omitempty"`
	LastSyncedAt  *string        `json:"lastSyncedAt,omitempty"`
	Locked        bool           `json:"locked"`
	Origin        *string        `json:"origin,omitempty"`
	Path          *string        `json:"path,omitempty"`
	Region        *string        `json:"region,omitempty"`
	Synced        bool           `json:"synced"`
}

// TerminalAppearance defines model for TerminalAppearance.
type TerminalAppearance struct {
	Background     *string `json:"background,omitempty"`
	BackgroundTint *int    `json:"backgroundTint,omitempty"`
	Font           *string `json:"font,omitempty"`
	Palette        *string `json:"palette,omitempty"`
}

// TerminalExit defines model for TerminalExit.
type TerminalExit struct {
	At     string `json:"at"`
	Code   int    `json:"code"`
	Signal string `json:"signal"`
}

// TerminalForward defines model for TerminalForward.
type TerminalForward struct {
	Kind    string `json:"kind"`
	Listen  string `json:"listen"`
	Problem string `json:"problem"`
	To      string `json:"to"`
}

// TerminalReconnect defines model for TerminalReconnect.
type TerminalReconnect struct {
	Attempt int       `json:"attempt"`
	Limit   int       `json:"limit"`
	Problem string    `json:"problem"`
	RetryAt time.Time `json:"retryAt"`
}

// TerminalSession defines model for TerminalSession.
type TerminalSession struct {
	Alias     *string              `json:"alias,omitempty"`
	Exited    *TerminalExit        `json:"exited,omitempty"`
	Forwards  *[]TerminalForward   `json:"forwards,omitempty"`
	Id        string               `json:"id"`
	Kind      TerminalSessionKind  `json:"kind"`
	Problem   string               `json:"problem"`
	Reconnect *TerminalReconnect   `json:"reconnect,omitempty"`
	StartedAt string               `json:"startedAt"`
	State     TerminalSessionState `json:"state"`
	Title     string               `json:"title"`
}

// TerminalSessionKind defines model for TerminalSession.Kind.
type TerminalSessionKind string

// TerminalSessionState defines model for TerminalSession.State.
type TerminalSessionState string

// TerminalSessionList defines model for TerminalSessionList.
type TerminalSessionList struct {
	MaxSessions int               `json:"maxSessions"`
	Sessions    []TerminalSession `json:"sessions"`
}

// TerminalSettings defines model for TerminalSettings.
type TerminalSettings struct {
	Appearance      *TerminalAppearance `json:"appearance,omitempty"`
	CopyOnSelect    *bool               `json:"copyOnSelect,omitempty"`
	FontSize        *int                `json:"fontSize,omitempty"`
	MaxSessions     *int                `json:"maxSessions,omitempty"`
	Reconnect       *int                `json:"reconnect,omitempty"`
	RightClickPaste *bool               `json:"rightClickPaste,omitempty"`
	ScrollbackBytes *int                `json:"scrollbackBytes,omitempty"`
	StartDirectory  *string             `json:"startDirectory,omitempty"`
	Verbosity       *int                `json:"verbosity,omitempty"`
}

// TerminalStreamTicket defines model for TerminalStreamTicket.
type TerminalStreamTicket struct {
	StreamTicket string `json:"streamTicket"`
}

// TrashEntrySummary defines model for TrashEntrySummary.
type TrashEntrySummary struct {
	AgeDays    int                `json:"ageDays"`
	Blockers   []string           `json:"blockers"`
	DeletedAt  string             `json:"deletedAt"`
	Files      []TrashFileSummary `json:"files"`
	Id         string             `json:"id"`
	Restorable bool               `json:"restorable"`
	Stale      bool               `json:"stale"`
}

// TrashFileSummary defines model for TrashFileSummary.
type TrashFileSummary struct {
	Fingerprint          string `json:"fingerprint"`
	Kind                 string `json:"kind"`
	OriginalRelativePath string `json:"originalRelativePath"`
	Permission           string `json:"permission"`
	TrashRelativePath    string `json:"trashRelativePath"`
}

// TrashKeyResponse defines model for TrashKeyResponse.
type TrashKeyResponse struct {
	EntryId       string             `json:"entryId"`
	Files         []TrashFileSummary `json:"files"`
	Skipped       []string           `json:"skipped"`
	TransactionId string             `json:"transactionId"`
}

// TrashListResponse defines model for TrashListResponse.
type TrashListResponse struct {
	Entries       []TrashEntrySummary `json:"entries"`
	RetentionDays int                 `json:"retentionDays"`
}

// UnreadableFile defines model for UnreadableFile.
type UnreadableFile struct {
	Reason       string `json:"reason"`
	RelativePath string `json:"relativePath"`
}

// UnresolvedReference defines model for UnresolvedReference.
type UnresolvedReference struct {
	ConfigPath string `json:"configPath"`
	Directive  string `json:"directive"`
	Line       int    `json:"line"`
	Reason     string `json:"reason"`
	Value      string `json:"value"`
}

// UpdateConnectionKeyPassphrase defines model for UpdateConnectionKeyPassphrase.
type UpdateConnectionKeyPassphrase = json.RawMessage

// UpdateConnectionPassword defines model for UpdateConnectionPassword.
type UpdateConnectionPassword = json.RawMessage

// UpdateConnectionRequest defines model for UpdateConnectionRequest.
type UpdateConnectionRequest struct {
	Base          string                        `json:"base"`
	HostName      *ConnectionStringChange       `json:"hostName,omitempty"`
	Identity      HostIdentity                  `json:"identity"`
	IdentityFile  *ConnectionIdentityFileChange `json:"identityFile,omitempty"`
	KeyPassphrase UpdateConnectionKeyPassphrase `json:"keyPassphrase"`
	Password      UpdateConnectionPassword      `json:"password"`
	Port          *ConnectionPortChange         `json:"port,omitempty"`
	User          *ConnectionStringChange       `json:"user,omitempty"`
}

// UpdatePasswordRemove defines model for UpdatePasswordRemove.
type UpdatePasswordRemove struct {
	Kind string `json:"kind"`
}

// UpdatePasswordUnchanged defines model for UpdatePasswordUnchanged.
type UpdatePasswordUnchanged struct {
	Kind string `json:"kind"`
}

// UpdateStatus defines model for UpdateStatus.
type UpdateStatus struct {
	Available bool    `json:"available"`
	Current   string  `json:"current"`
	Latest    *string `json:"latest,omitempty"`
	PageUrl   *string `json:"pageUrl,omitempty"`
}

// ValueSource defines model for ValueSource.
type ValueSource struct {
	Condition string `json:"condition"`
	Keyword   string `json:"keyword"`
	Kind      string `json:"kind"`
	Line      int    `json:"line"`
	Path      string `json:"path"`
	Value     string `json:"value"`
	Winner    bool   `json:"winner"`
}
