package knownhosts_test

import (
	"bytes"
	"testing"

	"sshc/internal/knownhosts"
)

const (
	fixtureKeyType     = "ssh-ed25519"
	fixtureKey         = "AAAAC3NzaC1lZDI1NTE5AAAAIPr0nHGmQb99GXmUofxJM4BXGwGzO0jGsQFBspODbkvS"
	fixtureFingerprint = "SHA256:bytFrSjxj2qRszG8sHhWN+YO3b9vDSU3gQtMorwKpEs"
	fixtureHashedHost  = "|1|u94nmAngiqvuJf3A9CcExCUb2oE=|tDiE1i4vIaZJu8QmzSCwb54jMP4="
)

const fixtureFile = "# generated by hand\n" +
	"bastion.example.com,203.0.113.10 " + fixtureKeyType + " " + fixtureKey + " admin@example\n" +
	"\n" +
	"[db.example.com]:2222 " + fixtureKeyType + " " + fixtureKey + "\n" +
	"@cert-authority *.example.com " + fixtureKeyType + " " + fixtureKey + "\n" +
	fixtureHashedHost + " " + fixtureKeyType + " " + fixtureKey + "\n" +
	"this line is not a known_hosts entry\n"

func TestParseFileRoundTripsAndClassifiesEveryLine(t *testing.T) {
	file := knownhosts.ParseFile([]byte(fixtureFile))
	if rendered := file.Render(); !bytes.Equal(rendered, []byte(fixtureFile)) {
		t.Fatalf("render changed bytes:\n%q\n%q", rendered, fixtureFile)
	}
	if len(file.Lines) != 7 {
		t.Fatalf("lines = %d", len(file.Lines))
	}

	plain := file.Lines[1]
	if plain.Entry == nil {
		t.Fatal("line 2 was not parsed as an entry")
	}
	if len(plain.Entry.Hosts) != 2 || plain.Entry.Hosts[1] != "203.0.113.10" {
		t.Errorf("hosts = %#v", plain.Entry.Hosts)
	}
	if plain.Entry.KeyType != fixtureKeyType || plain.Entry.Fingerprint != fixtureFingerprint {
		t.Errorf("entry = %#v", plain.Entry)
	}
	if plain.Entry.Comment != "admin@example" || plain.Number != 2 {
		t.Errorf("entry = %#v, number = %d", plain.Entry, plain.Number)
	}

	if bracketed := file.Lines[3].Entry; bracketed == nil || bracketed.Hosts[0] != "[db.example.com]:2222" {
		t.Errorf("bracketed entry = %#v", bracketed)
	}
	if authority := file.Lines[4].Entry; authority == nil || authority.Marker != "@cert-authority" {
		t.Errorf("marker entry = %#v", authority)
	}
	if hashed := file.Lines[5].Entry; hashed == nil || !hashed.Hashed {
		t.Errorf("hashed entry = %#v", hashed)
	}
	if unparsable := file.Lines[6]; unparsable.Entry != nil || unparsable.Problem == "" {
		t.Errorf("unparsable line = %#v", unparsable)
	}
}

func TestFingerprintMatchesOpenSSHAndRejectsGarbage(t *testing.T) {
	fingerprint, err := knownhosts.Fingerprint(fixtureKey)
	if err != nil {
		t.Fatalf("Fingerprint = %v", err)
	}
	if fingerprint != fixtureFingerprint {
		t.Fatalf("Fingerprint = %q, want %q", fingerprint, fixtureFingerprint)
	}
	if _, err := knownhosts.Fingerprint("not base64!"); err == nil {
		t.Error("Fingerprint accepted a value that is not base64")
	}
}

func TestMatchesHostCoversPlainPatternsAndHashedEntries(t *testing.T) {
	file := knownhosts.ParseFile([]byte(fixtureFile))

	plain := file.Lines[1].Entry
	if !plain.MatchesHost("bastion.example.com") || !plain.MatchesHost("203.0.113.10") {
		t.Error("plain entry did not match its own hosts")
	}
	if plain.MatchesHost("other.example.com") {
		t.Error("plain entry matched an unrelated host")
	}
	if wildcard := file.Lines[4].Entry; !wildcard.MatchesHost("api.example.com") {
		t.Error("wildcard pattern did not match")
	}

	hashed := file.Lines[5].Entry
	if !hashed.MatchesHost("bastion.example.com") {
		t.Error("hashed entry did not match the host it was generated from")
	}
	if hashed.MatchesHost("other.example.com") {
		t.Error("hashed entry matched an unrelated host")
	}
}

func TestSearchFindsHostsKeyTypesAndFingerprints(t *testing.T) {
	file := knownhosts.ParseFile([]byte(fixtureFile))

	if found := knownhosts.Search(file, "bastion"); len(found) != 1 || found[0].Number != 2 {
		t.Errorf("host search = %#v", found)
	}
	if found := knownhosts.Search(file, "bytFrSjx"); len(found) != 4 {
		t.Errorf("fingerprint search = %d entries, want every entry", len(found))
	}
	if found := knownhosts.Search(file, ""); len(found) != 4 {
		t.Errorf("empty query = %d entries, want every entry", len(found))
	}
	if found := knownhosts.Search(file, "ED25519"); len(found) != 4 {
		t.Errorf("key type search is case-insensitive: %#v", found)
	}
}

func TestMatchesHostHonoursNegatedPatternsLikeOpenSSH(t *testing.T) {
	file := knownhosts.ParseFile([]byte("*.corp,!special.corp ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOsSkw6xSsvW0qbp1a1EVJLiuvJf2jn5ITuTaMlBdET\n"))
	entry := file.Lines[0].Entry
	if entry == nil {
		t.Fatal("the negated line did not parse as an entry")
	}
	if !entry.MatchesHost("build.corp") {
		t.Error("the wildcard did not match a host it covers")
	}
	// OpenSSH's match_hostname: a negated match excludes the host from the whole
	// entry even though the wildcard also matches it.
	if entry.MatchesHost("special.corp") {
		t.Error("the negated host matched the entry")
	}
	if entry.MatchesHost("elsewhere.example") {
		t.Error("an unrelated host matched")
	}
}
