package knownhosts_test

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"sshc/internal/knownhosts"
	"sshc/internal/storage"
)

func newTestService(t *testing.T, contents string, collector *recordingCollector) *knownhosts.Service {
	t.Helper()
	home := t.TempDir()
	root := filepath.Join(home, ".ssh")
	if err := os.MkdirAll(root, 0o700); err != nil {
		t.Fatal(err)
	}
	if contents != "" {
		if err := os.WriteFile(filepath.Join(root, "known_hosts"), []byte(contents), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	workspace, err := storage.NewWorkspace(storage.OSFileSystem{}, home)
	if err != nil {
		t.Fatal(err)
	}
	manager := storage.NewManager(workspace, time.Now, bytes.NewReader(bytes.Repeat([]byte{0x2f}, 4096)))
	return knownhosts.NewService(workspace, manager, knownhosts.Scanner{Collect: collector.collect})
}

func TestDeleteRemovesOnlyTheRequestedLinesThroughTheTransactionManager(t *testing.T) {
	service := newTestService(t, fixtureFile, &recordingCollector{})

	listing, err := service.Listing("")
	if err != nil {
		t.Fatal(err)
	}
	if len(listing.Lines) != 4 {
		t.Fatalf("entries = %#v", listing.Lines)
	}

	target := knownhosts.Target{Line: listing.Lines[0].Number, Digest: storage.Digest([]byte(listing.Lines[0].Raw))}
	result, err := service.Delete([]knownhosts.Target{target})
	if err != nil {
		t.Fatalf("Delete = %v", err)
	}
	if result.BackupDir == "" || len(result.Written) != 1 {
		t.Fatalf("result = %#v", result)
	}

	after, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(after), "bastion.example.com,203.0.113.10") {
		t.Error("the requested entry was not removed")
	}
	if !strings.Contains(string(after), "# generated by hand") ||
		!strings.Contains(string(after), "this line is not a known_hosts entry") {
		t.Error("unrelated lines were not preserved")
	}

	// 削除を復元可能にするのはバックアップであり、再生可能にするのはジャーナルで
	// ある。どちらもマネージャ経由でコミットすることから得られる。
	backup, err := os.ReadFile(filepath.Join(result.BackupDir, "known_hosts"))
	if err != nil || !bytes.Equal(backup, []byte(fixtureFile)) {
		t.Fatalf("backup = %q, %v", backup, err)
	}
	history, err := service.Manager.History()
	if err != nil {
		t.Fatal(err)
	}
	if len(history) != 1 || history[0].Operation != "known_hosts.delete" {
		t.Fatalf("history = %#v", history)
	}
}

// TestDeleteRefusesWhenTheLineOnDiskChanged は事前条件が古くなった場合のケース。
// ユーザーは、その後に編集された行に対して削除を確認した。したがってリクエストは、
// いまその行を占めているものを取り除くのではなく、拒否されなければならない。
func TestDeleteRefusesWhenTheLineOnDiskChanged(t *testing.T) {
	service := newTestService(t, fixtureFile, &recordingCollector{})

	listing, err := service.Listing("")
	if err != nil {
		t.Fatal(err)
	}
	target := knownhosts.Target{Line: listing.Lines[0].Number, Digest: storage.Digest([]byte(listing.Lines[0].Raw))}

	// ユーザーにその行を見せたあとで、別の何かがファイルを書き直す。
	edited := strings.Replace(fixtureFile, "admin@example", "someone@else", 1)
	if err := os.WriteFile(service.Path(), []byte(edited), 0o600); err != nil {
		t.Fatal(err)
	}

	if _, err := service.Delete([]knownhosts.Target{target}); !errors.Is(err, knownhosts.ErrEntryChanged) {
		t.Fatalf("Delete = %v, want ErrEntryChanged", err)
	}
	unchanged, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if string(unchanged) != edited {
		t.Fatal("a refused deletion still wrote to the file")
	}

	stale := knownhosts.Target{Line: 2, Digest: storage.Digest([]byte("a line that is not there"))}
	if _, err := service.Delete([]knownhosts.Target{stale}); !errors.Is(err, knownhosts.ErrEntryChanged) {
		t.Fatalf("Delete = %v, want ErrEntryChanged", err)
	}
	missing := knownhosts.Target{Line: 999, Digest: storage.Digest([]byte("x"))}
	if _, err := service.Delete([]knownhosts.Target{missing}); !errors.Is(err, knownhosts.ErrNoSuchEntry) {
		t.Fatalf("Delete = %v, want ErrNoSuchEntry", err)
	}
}

func TestAddRequiresAFingerprintOrAnExplicitAcknowledgement(t *testing.T) {
	service := newTestService(t, "", &recordingCollector{})
	candidate := knownhosts.Candidate{
		Host: "bastion.example.com", Port: 22, KeyType: fixtureKeyType, Key: fixtureKey,
	}

	if _, err := service.Add(candidate, "", false); !errors.Is(err, knownhosts.ErrUnverifiedCandidate) {
		t.Fatalf("Add = %v, want ErrUnverifiedCandidate", err)
	}
	if _, err := service.Add(candidate, "SHA256:someoneelse", false); !errors.Is(err, knownhosts.ErrUnverifiedCandidate) {
		t.Fatalf("Add with a wrong fingerprint = %v, want ErrUnverifiedCandidate", err)
	}
	if _, err := os.Stat(service.Path()); !os.IsNotExist(err) {
		t.Fatal("an unverified candidate was written")
	}

	if _, err := service.Add(candidate, fixtureFingerprint, false); err != nil {
		t.Fatalf("Add with the out-of-band fingerprint = %v", err)
	}
	contents, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	want := "bastion.example.com " + fixtureKeyType + " " + fixtureKey + "\n"
	if string(contents) != want {
		t.Fatalf("known_hosts = %q, want %q", contents, want)
	}

	// 追加の繰り返しは、重複行ではなく何もしない操作になる。
	if _, err := service.Add(candidate, fixtureFingerprint, false); err != nil {
		t.Fatalf("repeated Add = %v", err)
	}
	repeated, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if string(repeated) != want {
		t.Fatalf("repeated Add changed the file: %q", repeated)
	}

	nonDefaultPort := knownhosts.Candidate{Host: "db.example.com", Port: 2222, KeyType: fixtureKeyType, Key: fixtureKey}
	if _, err := service.Add(nonDefaultPort, "", true); err != nil {
		t.Fatalf("acknowledged Add = %v", err)
	}
	withPort, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(withPort), "[db.example.com]:2222 ") {
		t.Errorf("known_hosts = %q, want a bracketed host for a non-default port", withPort)
	}
}

func TestAddRejectsAKeyTypeOrBlobItDoesNotUnderstand(t *testing.T) {
	service := newTestService(t, "", &recordingCollector{})

	invalidType := knownhosts.Candidate{Host: "a.example.com", Port: 22, KeyType: "rm -rf /", Key: fixtureKey}
	if _, err := service.Add(invalidType, "", true); !errors.Is(err, knownhosts.ErrUnsupportedKeyType) {
		t.Fatalf("Add = %v, want ErrUnsupportedKeyType", err)
	}
	invalidKey := knownhosts.Candidate{Host: "a.example.com", Port: 22, KeyType: fixtureKeyType, Key: "not base64!"}
	if _, err := service.Add(invalidKey, "", true); !errors.Is(err, knownhosts.ErrInvalidKey) {
		t.Fatalf("Add = %v, want ErrInvalidKey", err)
	}
	if _, err := os.Stat(service.Path()); !os.IsNotExist(err) {
		t.Fatal("a rejected candidate created the file")
	}
}

func TestEvidenceChangesWithTheFile(t *testing.T) {
	service := newTestService(t, fixtureFile, &recordingCollector{})

	before, err := service.Evidence()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(service.Path(), []byte(fixtureFile+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	after, err := service.Evidence()
	if err != nil {
		t.Fatal(err)
	}
	if before == after {
		t.Fatal("an edited known_hosts produced the same evidence")
	}
}
