package httpserver

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/labstack/echo/v5"
	"golang.org/x/crypto/ssh"

	"sshc/internal/api"
	"sshc/internal/knownhosts"
	"sshc/internal/session"
	"sshc/internal/storage"
)

const (
	knownHostKeyType     = "ssh-ed25519"
	knownHostKey         = "AAAAC3NzaC1lZDI1NTE5AAAAIPr0nHGmQb99GXmUofxJM4BXGwGzO0jGsQFBspODbkvS"
	knownHostFingerprint = "SHA256:bytFrSjxj2qRszG8sHhWN+YO3b9vDSU3gQtMorwKpEs"
)

const knownHostsFixture = "# generated by hand\n" +
	"bastion.example.com,203.0.113.10 " + knownHostKeyType + " " + knownHostKey + " admin@example\n" +
	"[db.example.com]:2222 " + knownHostKeyType + " " + knownHostKey + "\n"

func newKnownHostsServer(t *testing.T) (*echo.Echo, session.Credentials, *int, *knownhosts.Service) {
	t.Helper()

	home := t.TempDir()
	root := filepath.Join(home, ".ssh")
	if err := os.MkdirAll(root, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "known_hosts"), []byte(knownHostsFixture), 0o600); err != nil {
		t.Fatal(err)
	}
	workspace, err := storage.NewWorkspace(storage.OSFileSystem{}, home)
	if err != nil {
		t.Fatal(err)
	}
	manager := storage.NewManager(workspace, time.Now, bytes.NewReader(bytes.Repeat([]byte{0x2f}, 8192)))

	// 鍵を集める継ぎ目は差し替える。本物の握手を見るのは internal/sshclient である。
	blob, err := base64.StdEncoding.DecodeString(knownHostKey)
	if err != nil {
		t.Fatal(err)
	}
	scanned, err := ssh.ParsePublicKey(blob)
	if err != nil {
		t.Fatal(err)
	}
	// 集めに行った回数を数える。確認の無いスキャンがネットワークへ届かない
	// ことを、これで言う。
	collected := 0
	service := knownhosts.NewService(workspace, manager, knownhosts.Scanner{
		Collect: func(context.Context, string, time.Duration) ([]ssh.PublicKey, error) {
			collected++
			return []ssh.PublicKey{scanned}, nil
		},
	})

	sessions, bootstrap, err := session.NewManager(bytes.NewReader(bytes.Repeat([]byte{0x4d}, 8192)))
	if err != nil {
		t.Fatal(err)
	}
	credentials, err := sessions.Bootstrap(bootstrap)
	if err != nil {
		t.Fatal(err)
	}

	engine := echo.New()
	engine.Use((Security{ExpectedHost: keyTestHost, ExpectedOrigin: "http://" + keyTestHost, Sessions: sessions, Unlocked: alwaysUnlocked}).Middleware)
	registry := actionRegistry{}
	addKnownHostsActions(registry, service)
	actions := ActionHandlers{Sessions: sessions, Kinds: registry}
	registerActionRoutes(engine, actions)
	registerKnownHostsRoutes(engine, KnownHostsHandlers{Service: service, Actions: actions})
	return engine, credentials, &collected, service
}

func TestKnownHostsListingIsReadableWithoutAConfirmation(t *testing.T) {
	engine, credentials, _, _ := newKnownHostsServer(t)

	response := sendKeyRequest(t, engine, credentials, http.MethodGet, "/api/v1/known-hosts?query=bastion", nil, "")
	if response.Code != http.StatusOK {
		t.Fatalf("list = %d: %s", response.Code, response.Body.String())
	}
	var payload api.KnownHostsResponse
	if err := json.Unmarshal(response.Body.Bytes(), &payload); err != nil {
		t.Fatal(err)
	}
	if len(payload.Entries) != 1 {
		t.Fatalf("entries = %#v", payload.Entries)
	}
	entry := payload.Entries[0]
	if entry.Fingerprint != knownHostFingerprint || entry.Line != 2 || entry.Digest == "" {
		t.Errorf("entry = %#v", entry)
	}
}

func TestKnownHostsDeleteNeedsAConfirmationAndIsJournalled(t *testing.T) {
	engine, credentials, _, service := newKnownHostsServer(t)

	listing, err := service.Listing("bastion")
	if err != nil {
		t.Fatal(err)
	}
	target := api.KnownHostTarget{
		Line:   listing.Lines[0].Number,
		Digest: storage.Digest([]byte(listing.Lines[0].Raw)),
	}
	body := mustMarshal(t, api.KnownHostsDeleteRequest{Entries: []api.KnownHostTarget{target}})

	refused := sendKeyRequest(t, engine, credentials, http.MethodPost, "/api/v1/known-hosts/delete", body, "")
	if refused.Code != http.StatusForbidden {
		t.Fatalf("delete without a confirmation = %d, want 403", refused.Code)
	}
	unchanged, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if string(unchanged) != knownHostsFixture {
		t.Fatal("an unconfirmed delete changed the file")
	}

	token := diagnosticsToken(t, engine, credentials, session.ActionKnownHostsDelete, service.Path())
	accepted := sendKeyRequest(t, engine, credentials, http.MethodPost, "/api/v1/known-hosts/delete", body, token)
	if accepted.Code != http.StatusOK {
		t.Fatalf("delete = %d: %s", accepted.Code, accepted.Body.String())
	}
	var changed api.KnownHostsChangeResponse
	if err := json.Unmarshal(accepted.Body.Bytes(), &changed); err != nil {
		t.Fatal(err)
	}
	if !changed.Changed || changed.TransactionId == "" {
		t.Fatalf("response = %#v", changed)
	}

	after, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(after), "bastion.example.com") {
		t.Error("the entry was not removed")
	}
	if !strings.Contains(string(after), "# generated by hand") {
		t.Error("an unrelated line was lost")
	}
}

// TestKnownHostsDeleteRejectsAStaleTargetWithAConflict は事前条件の
// ケースである。ユーザーが確認した後にファイルが変わったので、
// リクエストはその行の今の中身を消さず、409 を返す。
func TestKnownHostsDeleteRejectsAStaleTargetWithAConflict(t *testing.T) {
	engine, credentials, _, service := newKnownHostsServer(t)

	listing, err := service.Listing("bastion")
	if err != nil {
		t.Fatal(err)
	}
	target := api.KnownHostTarget{
		Line:   listing.Lines[0].Number,
		Digest: storage.Digest([]byte(listing.Lines[0].Raw)),
	}

	edited := strings.Replace(knownHostsFixture, "admin@example", "someone@else", 1)
	if err := os.WriteFile(service.Path(), []byte(edited), 0o600); err != nil {
		t.Fatal(err)
	}

	token := diagnosticsToken(t, engine, credentials, session.ActionKnownHostsDelete, service.Path())
	response := sendKeyRequest(t, engine, credentials, http.MethodPost, "/api/v1/known-hosts/delete",
		mustMarshal(t, api.KnownHostsDeleteRequest{Entries: []api.KnownHostTarget{target}}), token)
	if response.Code != http.StatusConflict {
		t.Fatalf("stale target = %d, want 409: %s", response.Code, response.Body.String())
	}
	if code := problemCode(t, response.Body.Bytes()); code != "entry_changed" {
		t.Fatalf("problem code = %q, want entry_changed", code)
	}

	unchanged, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if string(unchanged) != edited {
		t.Fatal("a conflicting delete overwrote the file")
	}
}

func TestKnownHostsScanMarksEveryCandidateUnverified(t *testing.T) {
	engine, credentials, collected, _ := newKnownHostsServer(t)

	noToken := sendKeyRequest(t, engine, credentials, http.MethodPost, "/api/v1/known-hosts/scan",
		mustMarshal(t, api.KnownHostsScanRequest{Host: "bastion.example.com", Port: 22}), "")
	if noToken.Code != http.StatusForbidden {
		t.Fatalf("scan without a confirmation = %d, want 403", noToken.Code)
	}
	if *collected != 0 {
		t.Fatal("an unconfirmed scan reached the network")
	}

	token := diagnosticsToken(t, engine, credentials, session.ActionKnownHostsScan, "bastion.example.com")
	response := sendKeyRequest(t, engine, credentials, http.MethodPost, "/api/v1/known-hosts/scan",
		mustMarshal(t, api.KnownHostsScanRequest{Host: "bastion.example.com", Port: 22}), token)
	if response.Code != http.StatusOK {
		t.Fatalf("scan = %d: %s", response.Code, response.Body.String())
	}
	var payload api.KnownHostsScanResponse
	if err := json.Unmarshal(response.Body.Bytes(), &payload); err != nil {
		t.Fatal(err)
	}
	if payload.Notice == "" {
		t.Error("a scan result must carry the notice that it proves no identity")
	}
	if len(payload.Candidates) == 0 {
		t.Fatal("no candidates")
	}
	for _, candidate := range payload.Candidates {
		if candidate.Verified {
			t.Errorf("candidate reported as verified: %#v", candidate)
		}
	}
}

func TestKnownHostsAddRefusesAnUnverifiedKeyUntilItIsProvenOrAcknowledged(t *testing.T) {
	engine, credentials, _, service := newKnownHostsServer(t)

	request := api.KnownHostsAddRequest{
		Host: "new.example.com", Port: 22, KeyType: knownHostKeyType, Key: knownHostKey,
		ExpectedFingerprint: "", Acknowledged: false,
	}
	token := diagnosticsToken(t, engine, credentials, session.ActionKnownHostsAdd, "new.example.com")
	refused := sendKeyRequest(t, engine, credentials, http.MethodPost, "/api/v1/known-hosts/add",
		mustMarshal(t, request), token)
	if refused.Code != http.StatusConflict {
		t.Fatalf("unverified add = %d, want 409: %s", refused.Code, refused.Body.String())
	}
	if code := problemCode(t, refused.Body.Bytes()); code != "unverified_candidate" {
		t.Fatalf("problem code = %q, want unverified_candidate", code)
	}
	contents, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(contents), "new.example.com") {
		t.Fatal("an unverified key was written")
	}

	// ユーザーが別経路で得たフィンガープリントが鍵を証明する。
	request.ExpectedFingerprint = knownHostFingerprint
	proven := diagnosticsToken(t, engine, credentials, session.ActionKnownHostsAdd, "new.example.com")
	accepted := sendKeyRequest(t, engine, credentials, http.MethodPost, "/api/v1/known-hosts/add",
		mustMarshal(t, request), proven)
	if accepted.Code != http.StatusOK {
		t.Fatalf("proven add = %d: %s", accepted.Code, accepted.Body.String())
	}
	written, err := os.ReadFile(service.Path())
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(written), "new.example.com "+knownHostKeyType) {
		t.Errorf("known_hosts = %q", written)
	}
}
